
# Aim:
How to link the rule-based extracted CI_TYPE-GEO pairs with the respective Ci failure impacts

**Idea**\
Test using prompt engineering by passing table of CIGEO pairs to GPT-J model.
Steps:
* Load model and apply it always on one chunk of the document to extract CI failure impacts 
* Use prompt engineering to extract time and location of the CI failure (origin) the CI impacts (impact location)
or 
* Pass dataframe of pairs as input to the model
or
* Use few shot prompting with example answers

**Finally:**
* Compaire all approaches of spatial and temporal linking CI failure impacts

In [12]:
# %env CUDA_DEVICE_ORDER=PCI_BUS_ID
# %env CUDA_VISIBLE_DEVICES=0  # nvidia gpu
# %env PYTORCH_ALLOC_CONF=expandable_segments:True
# # %env TORCH_CUDA_ARCH_LIST=8.6

# # settings for distributed computing
# %env WORLD_SIZE=1
# %env RANK=0
# %env LOCAL_RANK=0

# # NOTE: # WORLD_SIZE: each GPU corresponds to one process (world = no. of processes within a group), processes communicate with each other enabling eg., distributed training
# # NOTE: # RANK: IDs of the processes, ranging from 0 up to WORLD_SIZE - 1

In [ ]:
import os
import sys
import argparse
import re
from datetime import datetime
import subprocess
from glob import glob
from pathlib import Path
from itertools import chain

import pandas as pd 
import numpy as np
import spacy
import textwrap
print("Loading packages for lx...")
from docling.datamodel.pipeline_options import PdfPipelineOptions
from langchain_docling import DoclingLoader
from huggingface_hub import login
import langextract as lx

# need for Langchain-Docling
pipeline_options = PdfPipelineOptions()
pipeline_options.allow_external_plugins = True 

print("Loading settings")
sys.path.append("./")
from src.settings import settings as s
import src.document_cleaning as dc


# set default location to store model before loading transformers
# os.environ["HF_HOME"] = s.HF_HOME_DIR

# login(token=os.environ.get("HF_TOKEN"))
login(token=os.getenv("HUGGINGFACE_TOKEN"))

test_mode = False
testing_limit = 25  # only process first n documents in test mode

:

:

In [14]:
print("Loading user args")
MODEL_CHOICE = "llama3"  # default ollama model

try:
    # load user arguments Ollama server and model
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--host_port",
        type=str,
        default="11434",
        help="The host and port of the llama server",
    )
    parser.add_argument(
        "--model_name",
        type=str,
        default=MODEL_CHOICE,
        help="The name of the llama model to use",
    )
    args = parser.parse_args()

    host_port = args.host_port
    model_name = args.model_name

except:
    host_port = "11434"
    model_name = MODEL_CHOICE
    
print("Using host and port:", host_port)
print("Using model:", model_name)

Loading user args
Using host and port: 11434
Using model: llama3

usage: ipykernel_launcher.py [-h] [--host_port HOST_PORT]
                             [--model_name MODEL_NAME]
ipykernel_launcher.py: error: unrecognized arguments: -f /beegfs/home/users/a/a-buch/.local/share/jupyter/runtime/kernel-21ecff36-3b74-45c0-9e72-fe728871be9a.json

In [15]:
## NOTE: make sure to set project root as working dir

# Input paths
PARSED_TEXT_DIR = "./" + s.PATH_DATA + "parsed_documents/"

# CI GEO pairs
filename_ci_geo_entities = "extracted_ci_geo_entities.csv"
CI_GEO_FILEPATH = Path("./"  + s.PATH_DATA) / filename_ci_geo_entities
NER_PATTERNS_FILEPATH = s.NER_PATTERNS_FILEPATH

## LX outputs
LX_OUTPUTS_DIR = s.PATH_LX_DATA

## document to process
docs_list = glob(PARSED_TEXT_DIR + "*_cleaned.md")
lx_response_filename = s.LX_DATA_FILENAME.replace(".csv", ".jsonl")
lx_response_filename_df = s.LX_DATA_FILENAME
LX_OUTPUTS_FILEPATH = Path(LX_OUTPUTS_DIR, lx_response_filename)
LX_OUTPUTS_DF_FILEPATH = Path(
    LX_OUTPUTS_DIR, lx_response_filename_df
)  # TODO make as part of OUTPUT_LX_FILEPATH and replaced suffix


if test_mode:
    print("Test mode is ON. Using only a small sample of documents for testing.")
    docs_list_sample = [
        # Path(PARSED_TEXT_DIR, "Keller 2014 - Mapping Natural Hazard Impacts on Road Infrastructure—The Extreme Precipitation in Baden-Württemberg_cleaned.md"),
        Path(PARSED_TEXT_DIR,"Rozendaal 2021 - Infrabel_ Flood damage to railway track worth tens of millions of euros _ SpoorPro - incomplete_cleaned.md",),
        Path(PARSED_TEXT_DIR,"The Guardian 2018 - Freezing weather costs UK economy £1bn a day _ UK weather_cleaned.md",),
        Path(PARSED_TEXT_DIR, "Brown 2010 - Economy feels chill as UK grinds to a halt _ The Independent_cleaned.md"),
        #Path(PARSED_TEXT_DIR, "Artemis 2015 - PERILS finalises Storm Desmond UK flood loss estimate at £604m_cleaned.md"),
        #Path(PARSED_TEXT_DIR, "Treanor 2015 - Storm Desmond damage across Cumbria estimated at £500m _ Storm Desmond _The Guardian_cleaned.md"),
        #Path(PARSED_TEXT_DIR, "PWC 2015 - Updated estimates on cost of Storm Desmond_cleaned.md"),
    ]

# Generate CI_GEO pairs

In [16]:

# %%
print("Try loading spaCy language model for remote instance (e.g., cluster)")
try:
    nlp = spacy.load(s.SPACY_MODEL)
except (OSError, ValueError):
    print(f"spaCy language model '{s.SPACY_MODEL}' not found. Downloading ...")
    subprocess.check_call(["uv", "pip", "install", "spacy-transformers"])
    subprocess.check_call(
        ["uv", "run", "python", "-m", "spacy", "download", s.SPACY_MODEL]
    )
    nlp = spacy.load(s.SPACY_MODEL)


# %%
## see for more info: https://spacy.io/usage/rule-based-matching#entityruler
## NOTE EntityRuler is hidden inside .add_pipe()


## call nlp model and create pipeline with new entity pattern
# NOTE Creation of the new entity (CI_TYPE) solves the issue that FAC entities (buildings, airports, highways, bridges, etc.) refer only to the name of the facility (e.g. A76, Ahrtalbahn)
config = {"spans_key": None, "annotate_ents": True, "overwrite": False}
try:
    ruler = nlp.add_pipe("span_ruler", config=config)
    ruler.from_disk(NER_PATTERNS_FILEPATH)
except ValueError:
    print("SpanRuler already exists in pipeline.")
    ruler = nlp.get_pipe("span_ruler")
    ruler.from_disk(NER_PATTERNS_FILEPATH)


# %%

Try loading spaCy language model for remote instance (e.g., cluster)

In [ ]:


## load docs
docs_list = glob(PARSED_TEXT_DIR + "*_cleaned.md")
print(f"Found {len(docs_list)} cleaned documents.")


if test_mode:
    docs_list = docs_list_sample

## DataFrame to store CI-GEO entity pairs
df_ci_geo = pd.DataFrame(  ## TODO make as pydantic class with fixed attributes
    columns=[
        "document_id",
        "chunk_id",
        "ci_entity",
        "ci_entity_label",
        "geo_entity",
        "geo_entity_label",
        "token_distance",
    ]
)


## iterate over all cleaned documents and extract CI-GEO entity pairs
# but first check if output file already exists
if CI_GEO_FILEPATH.exists():
    print(
        f"\nCI-Geo entities already exists, see file:  {CI_GEO_FILEPATH}. \nLoading file from disk"
    )

    with open(CI_GEO_FILEPATH, "r") as f:
        df_ci_geo = pd.read_csv(f)

else:
    for FILE_PATH in docs_list:
        print(f"\n\n------- Loading  - {Path(FILE_PATH).name} -------- ")
        loader = DoclingLoader(FILE_PATH)  # use chunks from Docling.Loader
        doc = loader.load()

        ## get most likely geolocation for each CI entity based on distance
        for i, chunk in enumerate(doc):
            nlp_chunk = nlp(chunk.page_content)
            all_ents = [ent for ent in nlp_chunk.ents]
            ci_type_ents = [
                ent for ent in nlp_chunk.ents if ent.label_ in ["CI_TYPE", "FAC"]
            ]
            ci_type_ents_info = [
                ent for ent in nlp_chunk.ents if ent.label_ in ["CI_TYPE"]
            ]
            fac_ents_info = [ent for ent in nlp_chunk.ents if ent.label_ in ["FAC"]]

            # check if chunk contains CI_TYPE entities
            if len(ci_type_ents) > 0:
                print(
                    f"\nChunk [{i}], No. CI_TYPE and FAC entities: {len(ci_type_ents)}"
                )
                print(
                    f"Contains following entities for CI_TYPE: {ci_type_ents_info}, FAC: {fac_ents_info}"
                )
                print(f"Chunk text [{i}]:", chunk.page_content)
                # print(f"{ {(ci_type_ents[i].text, ci_type_ents[i].label_) for i in range(len(ci_type_ents))} } ")

                # iterate over all entities within chunk
                for ent_idx in range(len(all_ents)):
                    # when entity is CI_TYPE or FAC (i.e. buidling, airports, highways) do following ...
                    if all_ents[ent_idx].label_ in ["CI_TYPE", "FAC"]:
                        ci_idx = ent_idx

                        ## .. calculate distances between CI_TYPE entity and  all GEO entities in chunk based on index position
                        distance_list = []
                        idx_in_chunk = []
                        try:
                            for ent_idx in range(len(all_ents)):
                                # TODO calc distances between CI_TYPE ~ GEO entities based on word numbers and not entities
                                if all_ents[ent_idx].label_ in ["GPE", "LOC"]:
                                    geo_idx = ent_idx
                                    dist_ent_pair = np.abs(ci_idx - geo_idx)
                                    distance_list.append(dist_ent_pair)
                                    idx_in_chunk.append((ent_idx))
                                    closest_pair_idx = np.argmin(
                                        distance_list
                                    )  # idx of closest GEO entity
                                    distance_closest_pair = distance_list[
                                        closest_pair_idx
                                    ]

                            threshold = (
                                5  # max token distance between CI_TYPE and GEO entity
                            )
                            if distance_closest_pair > threshold:
                                print(
                                    f""" Token distance between CI_TYPE/FAR and next GEO entity is {distance_closest_pair} and thus larger than the allowed distance of {threshold} tokens """
                                )
                                continue
                            else:
                                print(
                                    f"""  Closest GEO entity to CI_TYPE/FAC entity "{all_ents[ci_idx]}" is "{all_ents[idx_in_chunk[closest_pair_idx]]}" at distance {distance_closest_pair}"""
                                )  # TODO constrain min.distance to max value (eg. 5 tokens), issue: likely when distance value is high that geolocation of Ci_type is mentioned in previous sentences or chunk

                            ## write as dict entry incl chunk_id, ci_entity, geo_entity, distance
                            result_dict = {
                                "document_id": Path(FILE_PATH).stem,
                                "chunk_id": i,
                                "ci_entity": all_ents[ci_idx].text,
                                "ci_entity_label": all_ents[ci_idx].label_,
                                "geo_entity": all_ents[
                                    idx_in_chunk[closest_pair_idx]
                                ].text,
                                "geo_entity_label": all_ents[
                                    idx_in_chunk[closest_pair_idx]
                                ].label_,
                                "token_distance": distance_closest_pair,
                            }
                            df_ci_geo = pd.concat(
                                [df_ci_geo, pd.DataFrame([result_dict])],
                                ignore_index=True,
                            )

                        except IndexError:
                            print("No GEO entities found in this chunk.")
                            continue
                        # print("\nidx_in_chunk, closest pair idx", idx_in_chunk, closest_pair_idx)

                        # spacy.displacy.render(
                        #     nlp_chunk, style="ent",
                        #     options={"ents": ["CI_TYPE", "GPE", "LOC", "FAC"], "colors": {"CI_TYPE": "violet"}}
                        # )

                else:
                    print("\nNo CI_TYPE or FAC entities found in this chunk.")
                    continue

    # save to disk when not existing
    with (CI_GEO_FILEPATH).open("w") as f:
        df_ci_geo.to_csv(f, index=False)
    print(f"\nSaved extracted CI-GEO entity pairs to {CI_GEO_FILEPATH}")

Found 45 cleaned documents.

CI-Geo entities already exists, see file:  ../data/extracted_ci_geo_entities.csv.
Loading file from disk

# LLama with LangExtract

## Prompt text

In [18]:
# Prompt and extraction rules

prompt_with_cigeo = textwrap.dedent(
    """
    Extract information from the context about the affected infrastructure_type, its damage, its geolocation.

    Use the exact text for extractions. DO NOT paraphrase or overlap entities.
    Provide meaningful attributes for each entity to add context.


    Provide in the field "infrastructure_type" the type of infrastructure that was affected.
    If no information about the infrastructure type is found, then return for this field a "NAN" value.

    Provide in the field "geolocation" the location of the affected infrastructure.
    If no information about the location of the affected infrastructure is found, then return for this field a "NAN" value.

    Provide in the field "damage" the type of damage of the affected infrastructure.
    Use for example phrases like [partly closed, outages, largely destroyed, heavily destroyed, contaminated, out of service, severely damaged, largely destroyed, due to water/debris/risk aquaplaning on road, dam failure, closures, derailed, impassable, debris, destroyed, indirectly affected (through disrupted road and rail traffic), disrupted, blocked (through trees, roofs), damaged, affected, little to no]
    If no information about the damage type is found, then return for this field a "NAN" value.

    Provide in the field "name" the name of the affected infrastructure facility, such as a name of an airport or the highway number (e.g. A-3, A5, AP-7).
    If no information about the name of the affected infrastructure is found, then return for this field a "NAN" value.


    Finally, evaluate and improve your answer.
    In particular, for the fields ""infrastructure_type" and "geolocation" you should evaluate and improve your answer based on the information mentioned in CI locations.
    
    CI locations:
    {% for item in context %}
    - ("ci_entity" and "geo_entity":\n {{ item["ci_locations"][["ci_entity", "geo_entity"]] }})
    {% endfor %}


    """
)

In [19]:

prompt_no_cigeo = textwrap.dedent(
    """
    Extract information from the context about the affected infrastructure_type, its damage, its geolocation.

    Use the exact text for extractions. DO NOT paraphrase or overlap entities.
    Provide meaningful attributes for each entity to add context.


    Provide in the field "infrastructure_type" the type of infrastructure that was affected.
    If no information about the infrastructure type is found, then return for this field a "NAN" value.

    Provide in the field "geolocation" the location of the affected infrastructure.
    If no information about the location of the affected infrastructure is found, then return for this field a "NAN" value.

    Provide in the field "damage" the type of damage of the affected infrastructure.
    Use for example phrases like [partly closed, outages, largely destroyed, heavily destroyed, contaminated, out of service, severely damaged, largely destroyed, due to water/debris/risk aquaplaning on road, dam failure, closures, derailed, impassable, debris, destroyed, indirectly affected (through disrupted road and rail traffic), disrupted, blocked (through trees, roofs), damaged, affected, little to no]
    If no information about the damage type is found, then return for this field a "NAN" value.

    Provide in the field "name" the name of the affected infrastructure facility, such as a name of an airport or the highway number (e.g. A-3, A5, AP-7).
    If no information about the name of the affected infrastructure is found, then return for this field a "NAN" value.

    Finally, evaluate and improve your answer.


    """
)

In [20]:
## Few shot examples


few_shot_examples = [
    ## Skounding 2023
    lx.data.ExampleData(
        text="Elsewhere, the Mediterranean country has been battered by severe storms. On overnight storm in Milan on Monday tore off roofs and uprooted trees, blocking roads and disrupting overground transportation in Italy’s financial capital.",
        extractions=[
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="roads",
                attributes={"damage": "blocked", "geolocation": "Milan (city)"},
            ),
        ],
    ),
    ## Ferlita 2023
    lx.data.ExampleData(
        text="Another fire broke out in Pioppo, a hamlet of Monreale in the Palermo area, where a fire threatened several homes in Casaboli and destroyed much of the vegetation in that area."
        "The Partinico area was also not spared: the fire broke out a few days ago on State highway 113.",
        extractions=[
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="highway",
                attributes={
                    "damage": "affected",
                    "geolocation": "Partinico area",
                    "name": "State highway 113",
                },
            ),
        ],
    ),
    lx.data.ExampleData(
        text="Further damage occurred in recent days at Catania airport, considered the fifth most important in Italy. Following a fire that broke out inside the terminals, the access areas were promptly closed to travelers, causing enormous damage to the local economy, the tourism sector, and various professionals. In monetary terms, the damage is enormous: the National Civil Aviation Authority estimates a total investment for facilities and maintenance of around €200,000. The MEC (Consumer Voters Movement), on the other hand, estimates a cost of around €40 million per day due to the closure of the airport as a result of the fire. The total damage is estimated at more than €80 million. The fire broke out last Sunday night at Vincenzo Bellini Airport in Catania and, after two days of relentless work to extinguish the fire, arrivals and departures resumed from Terminal C.",
        extractions=[
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="terminals",
                attributes={
                    "damage": "damaged",
                    "geolocation": "Catania",
                    "name": "Vincenzo Bellini Airport",
                },
            ),
            #         lx.data.Extraction(
            #             extraction_class="impacts_to_other_infrastructure_assets",
            #             extraction_text="airport",
            #             attributes={"damage": "closure", "geolocation": "Catania"
            #             },
            #         ),
            #         lx.data.Extraction(
            #             extraction_class="economic_impact",
            #             extraction_text="€200,000",
            #             attributes={
            #                 "damage": "total investment costs for facilities and maintenance",
            #                 "geolocation": "Catania Airport"
            #             },
            #         ),
            #         lx.data.Extraction(
            #             extraction_class="economic_impact",
            #             extraction_text="€80 million",
            #             attributes={
            #                 "damage": "total damage",
            #                 "geolocation": "Catania Airport"
            #             },
            #         )
        ],
    ),
    ## EFE 2024
    lx.data.ExampleData(
        text="The most serious disruptions are on roads in Valencia, with closures on several sections of the A-3, the A-7 and the AP-7, as well as on the roads that connect it with Alicante and the N-3, N-322, N-330 and N-332 roads as they pass through the towns of Picassent, La Alcudia, Requena, Utiel, Buñol, Sueca, Algemesí, Guadassuar, Alzira or Chiva (Valencia), among other municipalities.",
        extractions=[
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="roads",
                attributes={
                    "damage": "closures",
                    "geolocation": "Valencia area",
                    "name": "A-3",
                    # "impacts_to_other_infrastructure_assets": "traffic disrupted"
                },
            ),
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="roads",
                attributes={
                    "damage": "closures",
                    "geolocation": "Valencia area",
                    "name": "A-7",
                    # "impacts_to_other_infrastructure_assets": "traffic disrupted",
                },
            ),
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="roads",
                attributes={
                    "damage": "closures",
                    "geolocation": "Valencia area",
                    "name": "AP-7",
                    # "impacts_to_other_infrastructure_assets": "traffic disrupted"
                },
            ),
            # lx.data.Extraction(
            #     extraction_class="impacts_to_other_infrastructure_assets",
            #     extraction_text="traffic",
            #     attributes={"damage": "disrupted", "geolocation": "Valencia area"},
            # ),
        ],
    ),
    ## Containerlift 2024
    lx.data.ExampleData(
        text="Nevertheless, the reopening of Valencia and Sagunto ports for maritime traffic marks a significant step forward for the region’s recovery.",
        extractions=[
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="ports",  # "Port operability",
                attributes={
                    "damage": "temporarily closed",
                    "geolocation": "Valencia and Sagunto ports",
                },
            ),
            # lx.data.Extraction(
            #     extraction_class="impacts_to_other_infrastructure_assets",
            #     extraction_text="reopening", #" Port operability",
            #     attributes={"damage": "temporarily closed", "geolocation": "Sagunto port"},
            # )
        ],
    ),
    ## Khazai et al 2013
    lx.data.ExampleData(
        text="Durch einen Deichbruch am 10.06. mussten im Landkreis Stendal Fernverkehrsstrecken der Deutschen Bahn AG gesperrt werden, sodass es zu Zugausfällen und langen Verspätungen kommt.",
        extractions=[  # tricky extraction due to non-English language
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="Deichbruch",
                attributes={
                    "damage": "dam failure",
                    "geolocation": "Stendal (Landkreis)",
                },
            ),
            # lx.data.Extraction(
            #     extraction_class="impacts_to_other_infrastructure_assets",
            #     extraction_text="Verspätungen",   # train service
            #     attributes={"damage": "disrupted"},
            # ),
        ],
    ),
    ## Koks et al., 2022
    lx.data.ExampleData(
        text="In Belgium, several towns experienced disruptions in water supply (in particular as a result of pollution).",
        extractions=[
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="water supply",
                attributes={"damage": "polluted", "geolocation": "Belgium"},
            ),
            #         lx.data.Extraction(
            #             extraction_class="impacts_to_other_infrastructure_assets",
            #             extraction_text="water supply",
            #             attributes={"damage": "disrupted"},
            #         ),
        ],
    ),
    # # 1. LAST ONE CHANGED:
    lx.data.ExampleData(
        text="In Belgium, several towns experienced disruptions in water supply (in particular as a result of pollution)."
        "Directly after the event, approximately 3400 families had no access to potable water.",
        extractions=[
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="water supply",
                attributes={"damage": "polluted", "geolocation": "Belgium"},
            ),
            #         # lx.data.Extraction(
            #         #     extraction_class="impacts_to_other_infrastructure_assets",
            #         #     extraction_text="water supply",
            #         #     attributes={"damage": "disrupted"},
            #         # ),
            #         lx.data.Extraction(
            #             extraction_class="societal_impact",
            #             extraction_text="3400 families",
            #             attributes={"damage": "affected"},
            #         ),
        ],
    ),
    lx.data.ExampleData(
        text="Within the region of Rhineland-Palatinate, it took 2 weeks to ensure 100 % coverage again through emergency communication masts."
        "Within 1 month, most of the network was restored to pre-disaster service provision."
        "After 5 months, broadband has also been restored in the most affected areas, which started in most areas only after power infrastructure was rebuilt.",
        extractions=[
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="power infrastructure",
                attributes={
                    "damage": "affected",
                    "geolocation": "Rhineland-Palatinate",
                },  # tricky extraction of location-info
            ),
            # lx.data.Extraction(
            #     extraction_class="impacts_to_other_infrastructure_assets",
            #     extraction_text="broadband",
            #     attributes={"geolocation": "most areas only after power infrastructure was rebuilt"},
            # ),
        ],
    ),
    lx.data.ExampleData(
        text="More than 130 km of motorways were closed directly after the event, of which 50 km were still closed two months later, with an estimated repair cost of EUR100 million (Hauser, 2021). ",
        extractions=[
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="motorways",
                attributes={"damage": "closure"},
            ),
        ],
    ),
    lx.data.ExampleData(
        text="Of the 112 bridges in the flooded 40 km of the Ahr valley (Rhineland-Palatinate), 62 bridges were destroyed, 13 were severely damaged and only 35 were in operation a month after the flood event (MDR, 2021).",
        extractions=[
            lx.data.Extraction(
                extraction_class="infrastructure_type",
                extraction_text="62 bridges",
                attributes={
                    "damage": "destroyed",
                    "geolocation": "Ahr valley",
                    "region": "Rhineland-Palatinate",
                },
            ),
        ],
    ),
]

## Apply LangExtract

In [21]:
## extract CI failure impacts via LangExtract

## load docs
docs_list = glob(PARSED_TEXT_DIR + "*_cleaned.md")

if test_mode:
    docs_list = docs_list_sample


print(f"Found {len(docs_list)} cleaned documents ready for LangExtract.")


responses_all_docs = []
responses_citations = []
responses_chunk_text = []

## iterate over all cleaned documents and extract CI-GEO entity pairs
for i, FILE_PATH in enumerate(docs_list):
    filename_stem = Path(FILE_PATH).stem

    print(
        f"\n\n -------- Processing document [{i + 1}]: {Path(FILE_PATH).name} -------- \n"
    )

    ## extract authors, publication year and title
    citation_pattern = r"(.*?)(\d{4})(.*)"  # split at first occurrence of year
    try:
        authors, year, title = re.findall(citation_pattern, filename_stem)[0]
        citation = f"{authors} {year}"
    except AttributeError as e:
        print(f"Could not extract citation from title: {e}")
        citation = filename_stem

    # ## load doc
    # with open(FILE_PATH, "r") as file:
    #     content = file.read()
    # doc = [lx.data.Document(content)]  # wrap content in Document object
    loader = DoclingLoader(FILE_PATH)  # use chunks from Docling.Loader
    doc = loader.load()

    ## TODO loop makes use of the chunking in docling, however, the implemented chunking strategy in LX might be better,
    ## however, then `[lx.data.Document(content)]` object needs to be splitted into smaller chunks (currently entire text is 1 chunk)

    ## NOTE for multiple documents / long text use batch processing (threading, character buffer, number of model passes on the text)
    responses = []

    # iterate over chunks per document
    for j, chunk_text in enumerate(doc):

        
        # remove URLs
        chunk_text.page_content = dc.remove_urls(chunk_text.page_content)

        if chunk_text.page_content.strip() == "":
            print(f"----------- Skipping empty chunk id {j} ---------")
            continue

        try:
            df_ci_geo_doc = df_ci_geo.loc[df_ci_geo["document_id"] == filename_stem]
            

            # if Ci-geo pair exists for chunk
            if not df_ci_geo_doc.loc[df_ci_geo_doc["chunk_id"] == j].empty:
                
                df_ci_geo_doc.loc[df_ci_geo_doc["chunk_id"] == j]

                context = [{
                    "prompt": prompt_with_cigeo, 
                    "ci_locations": df_ci_geo_doc.loc[df_ci_geo_doc["chunk_id"] == j],
                },]

                response = lx.extract(
                    text_or_documents=chunk_text.page_content,
                    prompt_description=context, # context (prompt_old) = 3 (1) error-missing exxtraton key; prompt_incl ci_geo=nearly only Errors
                    examples=few_shot_examples,
                    model_id=model_name,
                    model_url=os.getenv("OLLAMA_HOST", f"http://localhost:{host_port}"),
                    # language_model_type=lx.inference.OllamaLanguageModel,
                    temperature=0.2,
                    extraction_passes=1,  # decrease recall -> faster processing
                    # max_workers=4,   # invalid option for ollama
                    max_char_buffer=1024,  # NOTE testing 1042, with 512 (same as for LLM1) no error messages,  not increase due to TImeOutError:       # adapt to max. token sequence length of model
                )

            # Ci-geo pair not exists for chunk
            else:
                response = lx.extract(
                    text_or_documents=chunk_text.page_content,
                    prompt_description=prompt_no_cigeo,
                    examples=few_shot_examples,
                    model_id=model_name,
                    model_url=os.getenv("OLLAMA_HOST", f"http://localhost:{host_port}"),
                    # language_model_type=lx.inference.OllamaLanguageModel,
                    temperature=0.2,
                    extraction_passes=1,  # decrease recall -> faster processing
                    # max_workers=4,   # invalid option for ollama
                    max_char_buffer=1024,  # NOTE testing 1042, with 512 (same as for LLM1) no error messages,  not increase due to TImeOutError:       # adapt to max. token sequence length of model
                )

            responses.append(response)
            responses_citations.append(filename_stem)  # "citation_id" for each response
            responses_chunk_text.append(chunk_text.page_content)  # chunk text to traceback info for each response


        except ValueError as e:
            print("\n------- chunk id", j)
            print(f"Error when applying LangExtract on document {filename_stem}, text block {j}: {e}")
            print("Probably one of the few-shot examples does not match.")
            pass
        except (lx.resolver.ResolverParsingError, lx.core.exceptions.FormatParseError,) as e:
            print("\n------- chunk id", j)
            print(f"Error when applying LangExtract on document {filename_stem}, text block {j}: {e}")
            print("Probably content does not contain an 'extractions' key.")
            print("Respective chunk text:", chunk_text.page_content)
            pass
        except (TimeoutError, lx.core.exceptions.InferenceRuntimeError, AttributeError,) as e:
            print("\n------- chunk id", j)
            print(f"Error when applying LangExtract on document {filename_stem}, text block {j}: {e}")
            print("Probably Timeout threshold for calling Ollama API needs to be increased")
            pass
        except Exception as e:
            print("\n------- chunk id", j)
            print(f"Any other Error when applying LangExtract on document {filename_stem}, text block {j}: {e}")
            pass
    

    responses_all_docs.append(responses)

Found 45 cleaned documents ready for LangExtract.


 -------- Processing document [1]: Stamataki 2023 - Greece’s record rainfall and flash floods are part of a trend _ PreventionWeb_cleaned.md --------

LangExtract: Processing, current=795 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=717 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=757 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=266 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=943 chars, processed=0 chars:  [00:21]
LangExtract: Processing, current=670 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=729 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=574 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=633 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=654 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=746 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=407 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=419 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=240 chars, processed=0 chars:  [00:03]

 -------- Processing document [2]: AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned.md --------

Token indices sequence length is longer than the specified maximum sequence length for this model (540 > 512). Running this sequence through the model will result in indexing errors
LangExtract: Processing, current=354 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=692 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=710 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=556 chars, processed=0 chars:  [00:21]
LangExtract: Processing, current=571 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=806 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=170 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=766 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=810 chars, processed=0 chars:  [00:05]

------- chunk id 8
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 8: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: A las 2:00 horas del día 24 se apreciaba sobre el flanco derecho del chorro de salida de este núcleo frío una extensa  hoja  baroclina,  síntoma  de  la  existencia  de  un  forzamiento  dinámico  a  gran escala que elevaba las masas de aire sobre el océano hacia los niveles medio-altos de la atmósfera, transportando así humedad desde latitudes más bajas hacia latitudes más altas. En las imágenes de vapor de agua se aprecia como la extensa hoja baroclina (figura 1, arriba) fue evolucionando a lo largo del día 24, adquiriendo una mayor curvatura en su  punto  de  inflexión,  síntoma  de  que  se  estaba  produciendo  la  formación  de  una borrasca  en  superficie  y  que  a  primeras  horas  del  día  25  ya  estaba  completamente desarrollada al suroeste de las islas británicas (figura 2.1, abajo).

LangExtract: Processing, current=656 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=372 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=511 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=426 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=810 chars, processed=0 chars:  [00:05]

------- chunk id 13
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 13: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Durante  el  día  27  la  dorsal  existente  aguas  arriba  avanzaba  hacia  el  noreste manteniendo la  intensidad  del chorro de entrada a la  dana, pero haciendo que este fuera cambiando a componente noreste, por lo que empezó a producirse un cambio en la  dirección  de  desplazamiento  de  esta  hacia  el  suroeste.  De  este  modo,  el  día  28  a mediodía, la dana se localizaba sobre la vertical del golfo de Cádiz, todavía sin una región de bajas presiones con centro claramente definido. En la tarde del 28, su desplazamiento continuó  hacia  el  sur  localizándose  sobre  la  vertical  de  la  costa  norte  marroquí  a primeras horas del día 29. En este momento el chorro de entrada de la dorsal se debilitó rolando  a  oeste-noroeste,  mientras  que  su  chorro  de  salida  se  intensificó  por

LangExtract: Processing, current=370 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=717 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=442 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=851 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=336 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=804 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=280 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=536 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=716 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=735 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=733 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=330 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=567 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=451 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=674 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=279 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=637 chars, processed=0 chars:  [00:05]

------- chunk id 30
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 30: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: o  Líneas de turbonada sin precipitación estratiforme (SCM-LT-NS). o  Líneas de turbonada con precipitación estratiforme trasera (SCM-LT-TS). o  Líneas de turbonada con precipitación estratiforme delantera (SCM-LT-LS). o  Líneas de turbonada con precipitación estratiforme paralela (SCM-LT-PS). o  Líneas de turbonada arqueadas (bow echo) (SCM-LT-BE). o  Líneas de turbonada mixtas con múltiples bow echo (SCM-LT-LEWP). o  Derechos  (SCM-LT-Der):  los  SCM  de  mayor  tamaño  o  de  vientos  intensos  y
  Sistemas en cluster no lineales (SCM-NL).   Complejos  convectivos  de  mesoescala  (SCM-CCM):  SCM  de  mayores  tamaños  o  de

LangExtract: Processing, current=718 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=527 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=620 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=691 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=489 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=584 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=401 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=841 chars, processed=0 chars:  [00:05]

------- chunk id 38
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 38: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Valencia/València, Cuenca Precipitaciones torrenciales muy persistentes. Tornados, granizo e inundaciones. A  partir  de  primera  hora  de  la  tarde,  se  forma  una  intensa  y  muy  extensa supercélula  que  permanece  estática  sobre  la  Ribera  Baixa  y  Horta  Sud, principalmente, batiendo varios récords nacionales de cantidad e intensidad de precipitación en  la estación  de Turís y  produciendo el  desastre posterior con 223 fallecidos y 3 desaparecidos aún (a fecha de finalización de este estudio). Cabe  reseñar  que  también  produjo  varios  tornados,  con  daños  materiales. Posteriormente  se  desorganiza  y  forma  una  LT  que  sigue  percutiendo  en zonas ya afectadas por los sistemas convectivos precedentes.
Situación de lluvias intensas en la Península y Baleares entre el 28 de octubre y 4 de noviembre de 2024

LangExtract: Processing, current=412 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=792 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=784 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=783 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=660 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=589 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=592 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=658 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=600 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=789 chars, processed=0 chars:  [00:05]

------- chunk id 48
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 48: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Durante  la  madrugada  del  día  28  una  línea  de  tormentas  (SCM-28-I)  fue  barriendo Mallorca de sureste a noreste, afectando inicialmente a la zona sur y posteriormente al este y noreste de la isla. Llovió en toda la isla, aunque las zonas más afectadas fueron el sur y el este. En Manacor, que fue el lugar con más precipitación recogida, la máxima intensidad se produjo sobre  las  3:00  horas.  Los  chubascos  presentaron  intensidad  entre  muy  fuerte  y  torrencial, observándose acumulados en una hora ente 50 y 70 mm.
Los  mayores  impactos  se  produjeron  en  el  municipio  de  Manacor,  especialmente  en  Porto Cristo, donde el torrente se desbordó y arrastró a numerosos coches. También hubo muchas carreteras cortadas y campos anegados en el sur y este de Mallorca.

LangExtract: Processing, current=305 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=681 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=784 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=309 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=606 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=626 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=656 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=368 chars, processed=0 chars:  [00:21]
LangExtract: Processing, current=620 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=604 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=622 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=680 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=500 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=696 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=722 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=741 chars, processed=0 chars:  [00:05]

------- chunk id 64
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 64: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Tabla 4.5. Precipitaciones más destacables durante el 29 de octubre de 2024 en estaciones de AEMET en la
provincia de Valencia. Acumulados en mm una, seis, doce y veinticuatro horas.
En  la  figura  4.5  se  muestra  el  mapa  de  acumulados  de  este día  sobre  el  cual  se  aprecian  los valores  extraordinarios  registrados,  con  una  amplia  área  superando  los  300  mm,  y  un  gran contraste entre estos acumulados y los que se registraron en la zona más cercana al litoral de Valencia.
Situación de lluvias intensas en la Península y Baleares entre el 28 de octubre y 4 de noviembre de 2024
Figura 4.5. Precipitación acumulada (mm) a lo largo del día 29 de octubre. Fuente: AEMET, SAIH-Júcar, IVIA, Sisritel, AVAMET e Inforatge.

LangExtract: Processing, current=674 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=462 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=509 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=726 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=713 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=480 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=800 chars, processed=0 chars:  [00:05]

------- chunk id 71
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 71: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: En  las  comarcas  de  Guadix  y  Baza  se  dieron  precipitaciones  muy  fuertes  durante  la madrugada  y  gran  parte  de  la  mañana.  El  río  Guadix  se  desbordó  en  algún  tramo,  con anegaciones de viviendas y locales y cortes en las carreteras. Destacan los valores de Dólar y Guadix con casi 150 y 100 mm en doce horas, respectivamente.
Por  otro  lado,  en  la  comarca  Valle  de  Almanzora,  las  precipitaciones  también  produjeron  el desbordamiento del río Almanzora. La estación de Purchena de la red MetClim y en Tíjola, de la red SiAR, registraron acumulados superiores a 110 mm en doce horas.
Tabla 4.6. Precipitaciones más destacables durante el 29 de octubre de 2024 en estaciones de AEMET en la
provincia de Granada. Acumulados en mm en una, seis, doce y veinticuatro horas.

LangExtract: Processing, current=300 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=721 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=512 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=725 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=687 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=722 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=784 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=678 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=722 chars, processed=0 chars:  [00:05]

------- chunk id 80
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 80: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Las precipitaciones recogidas durante el día superaron los 100 mm en una elipse con eje mayor que se extendía desde Caravaca de la Cruz (Murcia), hasta Molinicos (Albacete), en la de Sierra del Segura y Alcaraz, superándose los 200 mm al noroeste de Caravaca. En estaciones de AEMET, se  acumularon  hasta  152,6  mm  en  Caravaca,  y  149,6  mm  en  la  estación  del  Embalse  de  la Fuensanta (Albacete). En las estaciones de SUREMET se llegaron a acumular durante el día 29 cantidades del orden de los 250 mm en Sierra del Frontón y en Rincón de los Huertos, ambas en Moratalla (Murcia).
NOMBRE CARAVACA DE LA CRUZ EMBALSE DE LA FUENSANTA BENIZAR
Max Max Max 12h 6h 1h 27,6 122,6 75,4 46,2  103,2  131,0 48,0 33,0 28,4

LangExtract: Processing, current=731 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=675 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=592 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=660 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=508 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=713 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=298 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=771 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=703 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=87 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=782 chars, processed=0 chars:  [00:05]

------- chunk id 91
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 91: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Durante la madrugada y mañana del día 31 un sistema convectivo de mesoescala (SCM- 31-I)  afectó  a  la  mitad  norte  de  la  provincia  de  Castellón  que  provocaron  precipitaciones persistentes de intensidad muy fuerte, localmente torrencial. Afectó principalmente a una zona entre Torreblanca, Vilanova d’Alcolea, Sant Mateu, Catí y Fredes.  En doce horas se llegaron a acumular 100,8 mm en Torreblanca, 110,0 en Catí y 100,0 mm en Vall d’Alba, con acumulados de más 60 mm en una hora. Las primeras tormentas comenzaron a formarse a primera hora de la  madrugada  y,  alimentadas  por  un  flujo  de  viento  muy  húmedo  de  levante,  se  fueron generalizando y permanecieron estáticas en el norte de la provincia hasta mediodía, cuando se fueron trasladando hacia Tarragona.

LangExtract: Processing, current=405 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=781 chars, processed=0 chars:  [00:05]

------- chunk id 93
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 93: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: El día 29 por la noche se emitió aviso amarillo de precipitación de 20 mm en una hora en Litoral norte de Castellón para el 31. El día 30 por la mañana se extendió el aviso a Interior norte. Por la  tarde-noche  los  avisos  se  elevaron  a  naranja  de  40  mm  en  una  hora  en  estas  zonas,  y  se añadieron avisos naranjas de precipitación de 100 mm en doce horas. También se añadió aviso amarillo  de  precipitación  de  30 mm  en  una  hora  en  Litoral  sur. El día  31  a  las  7:23  horas  se elevaron a naranja de 40 mm en una hora y 100 mm en doce horas los avisos de Litoral sur. A las 9:16 horas se elevaron a rojo de 180 mm en doce horas los avisos de Interior norte y Litoral norte de Castellón desde esa hora y hasta el mediodía, continuando después como naranjas

LangExtract: Processing, current=427 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=709 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=390 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=406 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=562 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=763 chars, processed=0 chars:  [00:05]

------- chunk id 99
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 99: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Lo más destacado de las precipitaciones se produjo en las provincias de Cádiz y Huelva. En  San  Fernando  y  Vejer  de  la  Frontera  se  superaron  los  80  mm  en  veinticuatro  horas, produciéndose en estas zonas inundaciones por el desbordamiento del río Barbate.
En Isla Cristina (Huelva), entre las 16:00 y 17:00 horas se formó una tromba marina que levantó barcas del mar, y penetró en tierra ocasionando destrozos. Se trató de un fenómeno de escala local y poca duración que sólo afectó a una estrecha franja.
NOMBRE SAN FERNANDO VEJER DE LA FRONTERA CERRO ANDEVALO
Tabla 4.13. Precipitaciones más destacables durante el 31 de octubre de 2024 en estaciones de AEMET en las
provincias de Huelva y Cádiz. Acumulados en una, seis, doce y veinticuatro horas.

LangExtract: Processing, current=464 chars, processed=0 chars:  [00:19]
LangExtract: Processing, current=677 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=611 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=723 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=662 chars, processed=0 chars:  [00:05]

------- chunk id 104
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 104: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Situación de lluvias intensas en la Península y Baleares entre el 28 de octubre y 4 de noviembre de 2024
Provincia NOMBRE HUELVA CARTAYA, PEMARES HUELVA EL ARENOSILLO HUELVA, RONDA ESTE HUELVA VILLARRASA PLANTA DE RECICLAJ  HUELVA HUELVA EL CERRO DE ANDEVALO
Max 1h 70,0  117,2  137,6 71,6 50,4 18,7 64,8 49,0 31,0 50,0 39,2 16,2 37,0 33,0 14,0
Tabla 4.14. Precipitaciones más destacables durante el 1 de noviembre de 2024 en estaciones de AEMET en
la provincia de Huelva. Acumulados en mm en una, seis, doce y veinticuatro horas.
-A continuación, se presentan a modo de resumen los avisos emitidos para las principales zonas afectadas de la provincia de Huelva:

LangExtract: Processing, current=712 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=748 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=617 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=714 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=726 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=311 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=693 chars, processed=0 chars:  [00:05]

------- chunk id 111
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 111: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: El día 2 por la mañana se emitieron avisos amarillos de precipitación de 15 mm en una hora y de 60 mm en doce horas para la mañana del día 3 en Campo de Cartagena y Mazarrón. Por la noche se  elevaron  los  avisos  a  naranja  de  40  mm  en  una  hora y  amarillo  de  80  mm  en  doce  horas. Además, se emitió aviso naranja de precipitación de 40 mm en una hora y amarillo de 80 mm en doce horas en Valle del Guadalentín, Lorca y Águilas, para el mismo periodo. El día 3 a las 11:52 horas  se  elevaron  los  avisos  a  naranja  de  precipitación  de  50 mm  en  una  hora y  amarillo  de precipitación de 90 mm en doce horas en ambas zonas, cancelándose a las 16:53 horas todos los avisos.

LangExtract: Processing, current=320 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=643 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=688 chars, processed=0 chars:  [00:05]

------- chunk id 114
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 114: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: El día 2 por la mañana se emitieron avisos amarillos de  20 mm de precipitación en una hora previstos  para  todo  el  día  3  en  Litoral  sur  de  Valencia.  Por  la  noche  se  elevaron  los  avisos  a naranja  de  50  mm  de  precipitación  en  una  hora  y  se  emitió  aviso  naranja  de  150  mm  de precipitación en doce horas. El día 3 a las 8:25 horas se rebajaron los acumulados de los avisos de precipitación: en una hora a 40 mm y en doce horas a 100 mm. A las 15:50 horas se elevó el aviso a rojo de precipitación de 90 mm en una hora entre las 18:00 y las 22:00 horas.
Situación de lluvias intensas en la Península y Baleares entre el 28 de octubre y 4 de noviembre de 2024

LangExtract: Processing, current=485 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=686 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=602 chars, processed=0 chars:  [00:19]
LangExtract: Processing, current=528 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=646 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=741 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=608 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=709 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=602 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=765 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=675 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=322 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=749 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=572 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=844 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=725 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=491 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=802 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=526 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=399 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=666 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=316 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=652 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=584 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=450 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=549 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=389 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=471 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=763 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=798 chars, processed=0 chars:  [00:05]

------- chunk id 144
Error when applying LangExtract on document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned, text block 144: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Al  contrario  de  lo  descrito  en  los  párrafos  anteriores,  hay  una  mayor  confianza  en  las proyecciones  climáticas  relativas  a  la  intensidad  de  las  precipitaciones  que  pueden  llevar asociadas  (Pinheiro  y  otros.  2024).  Un  ejemplo  de  ello  puede  encontrarse  en  Ferreira  2021, donde  se  apunta  a  un  posible  aumento  futuro  durante  el  otoño,  de  hasta  un  88%  de  la precipitación  asociada  a  las  danas  en  el  noreste  de  España  y  de  un  61%  en  las  regiones adyacentes. Uno de los principales factores asociados a este incremento obedece a una ley física fundamental  que  relaciona  la  mayor  capacidad  que  tiene  una  atmósfera  más  cálida  para almacenar  un  mayor  contenido  de  humedad,  la  cual  le  otorga  una  mayor  potencialidad

LangExtract: Processing, current=656 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=233 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=761 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=94 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=735 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=700 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=731 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=509 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=698 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=208 chars, processed=0 chars:  [00:06]

 -------- Processing document [3]: Wildhagen 2013 - Hochwasser_ Wie die Flut Unternehmen lahmlegt_cleaned.md --------

LangExtract: Processing, current=749 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=595 chars, processed=0 chars:  [00:21]
LangExtract: Processing, current=621 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=672 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=596 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=669 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=572 chars, processed=0 chars:  [00:18]
LangExtract: Processing, current=701 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=680 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=646 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=575 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=738 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=225 chars, processed=0 chars:  [00:06]

 -------- Processing document [4]: European Investment Bank 2025 - Spain_ EIB lends €50 million to Iberdrola to rebuild and climate-proof flood-hit power infrastructure in Valencia_cleaned.md --------

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: b2920fb1-7280-4a49-a169-aabb2a0e95ec)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: b2920fb1-7280-4a49-a169-aabb2a0e95ec)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
LangExtract: Processing, current=811 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=688 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=798 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=558 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=489 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=237 chars, processed=0 chars:  [00:03]

 -------- Processing document [5]: The Maritime Executive 2024 - A Week After Devastating Floods, Spain’s Valencia Port is Restoring Service_cleaned.md --------

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 3b3db82e-1a24-473c-bda0-f3d48f661e61)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 3b3db82e-1a24-473c-bda0-f3d48f661e61)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
LangExtract: Processing, current=166 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=502 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,010 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,126 chars, processed=0 chars:  [00:38]
LangExtract: Processing, current=668 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=780 chars, processed=0 chars:  [00:20]
LangExtract: Processing, current=967 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=503 chars, processed=0 chars:  [00:04]

------- chunk id 7
Error when applying LangExtract on document The Maritime Executive 2024 - A Week After Devastating Floods, Spain’s Valencia Port is Restoring Service_cleaned, text block 7: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Could Northeast States Trade Pipeline Access for Offshore Wind Permits? ( northeast-states-trade-pipeline-access-for-offshore-wind-permits)
Port Wars in the Horn of Africa (
NOAA: Higher Temps and Less Ice in a Changing Arctic ( less-ice-in-a-changing-arctic)
Could Northeast States Trade Pipeline Access for Offshore Wind Permits? ( northeast-states-trade-pipeline-access-for-offshore-wind-permits)
The Maritime Executive's Most Popular Editorials of 2025 ( executive-s-most-popular-editorials-of-2025)

LangExtract: Processing, current=424 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=482 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=624 chars, processed=0 chars:  [00:03]

 -------- Processing document [6]: Ferlita 2023 - Incendi in Sicilia, ecco cosa accade_cleaned.md --------

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 2cd897bc-2791-469b-8567-38f58f27e398)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 2cd897bc-2791-469b-8567-38f58f27e398)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
LangExtract: Processing, current=691 chars, processed=0 chars:  [00:19]
LangExtract: Processing, current=605 chars, processed=0 chars:  [00:19]
LangExtract: Processing, current=625 chars, processed=0 chars:  [00:19]
LangExtract: Processing, current=750 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=675 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=687 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=730 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=681 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=277 chars, processed=0 chars:  [00:06]

 -------- Processing document [7]: Containerlift 2024 - Valencia Port Resumes Operations Following Devastating Flooding in Spain - Containerlift.co.uk - Transport_Lifting_Shipping_cleaned.md --------

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 0b804346-4efb-42fe-9413-9b6f3ddd630d)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 0b804346-4efb-42fe-9413-9b6f3ddd630d)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].
LangExtract: Processing, current=905 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,116 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=1,058 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=462 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=491 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=435 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=454 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=527 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=529 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=489 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=80 chars, processed=0 chars:  [00:03]

 -------- Processing document [8]: Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned.md --------

Token indices sequence length is longer than the specified maximum sequence length for this model (609 > 512). Running this sequence through the model will result in indexing errors
LangExtract: Processing, current=276 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=877 chars, processed=0 chars:  [00:05]

------- chunk id 1
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 1: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Susanna Mohr1,2, Uwe Ehret1,3, Michael Kunz1,2, Patrick Ludwig1,2, Alberto Caldas-Alvarez2, James E. Daniell1,4, Florian Ehmele2, Hendrik Feldmann2, Mário J. Franca3, Christian Gattke5, Marie Hundhausen2, Peter Knippertz2, Katharina Küpfer1,2, Bernhard Mühr1, Joaquim G. Pinto1,2, Julian Quinting2, Andreas M. Schäfer1,6, Marc Scheibel7, Frank Seidel3, and Christina Wisotzky1,8 1Center for Disaster Management and Risk Reduction Technology (CEDIM), Karlsruhe Institute of Technology (KIT), Karlsruhe, Germany 2Institute of Meteorology and Climate Research (IMK-TRO), Karlsruhe Institute of Technology (KIT), Karlsruhe, Germany 3Institute for Water and River Basin Management, Karlsruhe Institute of Technology (KIT), Karlsruhe, Germany 4Institute of Photogrammetry and Remote Sensing, Karlsruhe Institute of Technology (KIT), Karlsruhe, Germany 5Erftverband, Bergheim, Germany

LangExtract: Processing, current=343 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=1,187 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=973 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,149 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=217 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,010 chars, processed=0 chars:  [00:05]

------- chunk id 7
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 7: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The Center for Disaster Management and Risk Reduc- tion Technology (CEDIM,  last access: 13 November 2022), an interdisciplinary research center in the ﬁeld of disasters, risks, and security at Karl- sruhe Institute of Technology (KIT), Germany, has been conducting forensic disaster analyses (FDAs) in near-real- time since 2011 (e.g., Kunz et al., 2013; Merz et al., 2014; Piper et al., 2016; Wilhelm et al., 2021). The approach of forensically investigating disasters stems from the interdis- ciplinary research program integrated research on disaster risk (IRDR) and their program forensic investigation of dis- asters (FORIN; Burton, 2010). IRDR uses the forensic ap- proach to uncover the root causes of disasters through in- depth investigations and to build an understanding of how hazards do or do not become disasters. CEDIM aims for a timely analysis within a few hours to a few days after the event. CEDIM’s FDAs examine the dynamics and interrela- tions of disasters, identiﬁes major risk drivers,

LangExtract: Processing, current=648 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=880 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,277 chars, processed=0 chars:  [00:16]
LangExtract: Processing, current=886 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=561 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=817 chars, processed=0 chars:  [00:18]
LangExtract: Processing, current=352 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=757 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=683 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=825 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=474 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=991 chars, processed=0 chars:  [00:05]

------- chunk id 19
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 19: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: In addition, different gridded precipitation data sets pro- vided by DWD were used in this study for both the event analysis and the estimation of return periods, in- cluding daily HYRAS data (Hydrometeorologische Raster- datensätze; Rauthe et al., 2013) and hourly RADOLAN data (Radar-Online-Aneichung; Weigl and Winterrath, 2009; Winterrath et al., 2018). HYRAS is a gridded data set cov- ering Germany and its relevant river basins in neighboring countries at a 5 × 5 km2 grid resolution currently available for the period from 1951 to 2015 (update in preparation). It is based on several thousand climate stations interpolated to the regular grid considering elevation, exposition, and climatology. A sub-sample of HYRAS is the HYRAS-DE data, formerly known as REGNIE (Regionalisierte Nieder- schlagshöhen), covering only Germany but with a higher res- olution of 1 km2. HYRAS-DE is continuously updated on a daily basis and thus available for the July 2021 event. Caldas- Alvarez et al.

LangExtract: Processing, current=848 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=795 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=999 chars, processed=0 chars:  [00:05]

------- chunk id 22
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 22: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: All water level W and streamﬂow Q data from gauges used in this study were provided by the water administrations of Rhineland-Palatinate, the Erftverband, and the Wupperver- band. From the large number of gauge data made available to us, for brevity we selected a representative subset based on the objectives of (a) covering our region of main interest – from the river Wupper in the east to the river Amblève in the west, (b) covering a range of basin sizes – from 31.9 km2 at gauge Schönau (Erft) to 816 km2 at gauge Kordel (Kyll), and (c) covering the position along streams – wherever pos- sible we selected two gauges per river, one in the headwater and one close to its junction (see Fig. 1; river names in blue, gauge names in red, reservoir names in brown). Addition- ally, we selected gauges of special interest, such as gauge Schönau (Erft) for its proximity to retention basin Horch- heim (see Sect. 3.2), gauge Bliesheim (Erft) for its proximity to the pit at Blessem (urban district of

LangExtract: Processing, current=996 chars, processed=0 chars:  [00:06]

------- chunk id 23
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 23: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: the town Erftstadt; see Sect. 3.3), and gauge Altenahr (Ahr) for the morphological effects in the river Ahr (see Sect. 3.3) and its historical con- text (cf. Part 2).
Water level data are from direct observations; streamﬂow data were calculated by the water authorities from water level observations and gauge-speciﬁc water level–discharge relations (W –Q relations), including uncertainties of about 15 % to 20 %. A summary of the gauge data is given in Ta- ble 1 (see Sect. 3.2). In cases where water level data were either not available (mainly due to gauge destruction), wa- ter levels exceeded the existing W –Q relations, or W –Q re- lations becoming invalid because of morphological changes of the river bed, streamﬂow data were estimated by the wa- ter authorities. In particular, the streamﬂow time series at gauge Altenahr (Ahr) that was completely destroyed during the ﬂood was reconstructed based on ﬂoating debris lines at buildings, recordings of upstream gauges, and observed rain-

LangExtract: Processing, current=605 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=846 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=480 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=666 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,113 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=434 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=794 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=840 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,015 chars, processed=0 chars:  [00:05]

------- chunk id 32
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 32: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Adjusting statistical distribution functions to a data se- ries allows for estimating high return periods beyond the available time period. Furthermore, the comparatively strong noise or high random component of an empirical return pe- riod estimation (e.g., block maximum) is reduced to a certain degree (e.g., Bezak et al., 2014).
Using the loss models available in CEDIM (e.g., Daniell et al., 2011, 2018; Mühr et al., 2017) and empirical data from past ﬂood disasters (hazard information, infrastructural, and other damage), a ﬁrst rapid loss assessment was carried out as part of the FDA activity immediately after the ﬂood event (Schäfer et al., 2021). A central element for this assessment was a very large natural hazard database with over 60 000 en- tries (CATDAT; Daniell et al., 2011, 2016; EEA, 2022) built up by CEDIM in recent years.
The following characteristics and assumptions were made
a. Based on the inundation areas, 9694 buildings in RP and 9702 buildings in NRW were identiﬁed to be affected.

LangExtract: Processing, current=612 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,162 chars, processed=0 chars:  [00:18]
LangExtract: Processing, current=290 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,247 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=197 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,028 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,124 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=40 chars, processed=0 chars:  [00:02]
LangExtract: Processing, current=1,044 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=805 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=638 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=752 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=895 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=126 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=1,049 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=475 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,007 chars, processed=0 chars:  [00:05]

------- chunk id 49
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 49: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: In the following section, the predictability of the event is an- alyzed based on weather forecasts by DWD and ECMWF (see Sect. 2.1). The deterministic forecast runs of the DWD ICON-EU model show the potential for a widespread heavy precipitation event in the border region between western Germany, eastern France, Belgium, Luxembourg, and the Netherlands as early as 12 July 00:00 UTC (see Fig. S5). While the affected area and intensity varies over the next forecasts, the potential for an extraordinary event in this region remains. Speciﬁcally for the affected area (LReg), high 24 h precipitation totals (within the range of the ob- servations; see Sect. 3.1.1) were predicted more than 2 d (from 12 July 00:00 UTC) ahead of the event (blue dots in Fig. 4a). The DWD ICON-D2 forecasts also captured the magnitude of the event right from of their ﬁrst initializa- tion (13 July 06:00 UTC; red dots in Fig. 4a), as can also be seen in the spatial distribution of the precipitation forecasts by ICON-D2 and

LangExtract: Processing, current=333 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=993 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,197 chars, processed=0 chars:  [00:07]

------- chunk id 52
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 52: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: In this section, we discuss the hydrological aspects of the event, including antecedent conditions in the catchments, river water levels and streamﬂow, effects on reservoirs, and a comparison of observed peak values with statistical design ﬂoods. However, we did not estimate statistical return peri- ods of the July 2021 ﬂood for several reasons. The ﬁrst reason is that during the event, many gauging stations were partly or completely destroyed, and even if water level recordings existed, water level–discharge relations (W –Q relations) at many gauges were severely altered during the ﬂood due to dynamical river bed changes or backwater effects from ﬂoat- ing debris trapped upstream of bridges (see Sect. 3.3). Fur- thermore, the water levels observed during the ﬂood were of- ten all-time records exceeding existing W –Q relations. Re- constructing event discharge, the basis for a statistical treat- ment, is therefore a difﬁcult and still ongoing task, and the values reported below should be interpreted as the best avail- able to date but not as ﬁnal estimates. Nevertheless, and de- spite considerable uncertainties, often the sheer magnitude of the estimates underline the exceptional

LangExtract: Processing, current=725 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=897 chars, processed=0 chars:  [00:05]

------- chunk id 54
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 54: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Figure 4. (a) 24 h precipitation totals over LReg (14 July 06:00 UTC to 15 July 2021 06:00 UTC) as forecasted by ICON-EU, ICON-D2, and ICON-D2-EPS for different initialization times and observed precipitation total as reference based on RADOLAN: 55.4 mm (stippled black horizontal line). For the EPS, the boxes represent the median and 25 % or 75 % percentiles, the triangles the 10 % or 90 % percentiles and the whiskers the total ensemble range. (b) Extreme forecast index (EFI) for precipitation on 14 July 2021 based on the ECMWF-EPS for different initialization times. Horizontal lines at 0.5 and 0.8 denote the limits for classiﬁcation of an unusual (EFI between 0.5 and 0.8) and very unusual or extreme event (EFI greater 0.8).
region in the 3 weeks prior to the ﬂood leading to widespread high soil moisture. For Luxembourg, AGE (2021) also re- ported relatively wet antecedent conditions.

LangExtract: Processing, current=930 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=776 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=790 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=827 chars, processed=0 chars:  [00:20]
LangExtract: Processing, current=632 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,002 chars, processed=0 chars:  [00:05]

------- chunk id 60
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 60: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Like the rivers Ahr, Kyll, and Prüm, the river Erft originates in the Eifel, but it drains northward towards its conﬂuence with the Rhine near the city of Düsseldorf (see Fig. 1). In the Erft headwater region, 130 to 150 mm of rain fell on 14 July, with highest intensities occurring between 10:00 and 19:00 UTC. As a consequence, the water level at headwa- ter gauge Schönau (Fig. 6g), for example, started rising at 07:00 UTC, reaching its peak at 18:50 UTC in the evening, more than 5 times larger than the statistical H Q100 of the gauge. At gauge Bliesheim (Fig. 6h), 36 km downstream of Schönau, water levels started rising about 6 h later, but – due to the operation of the retention basins Eicherscheid and Horchheim located in-between – reached its peak only at 08:45 UTC on the following day. While the operation of the reservoirs delayed the peak somewhat, they were far too small to signiﬁcantly reduce the ﬂood peak: at Bliesheim, the maximum discharge exceeded the statistical H Q100 by a

LangExtract: Processing, current=1,009 chars, processed=0 chars:  [00:05]

------- chunk id 61
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 61: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: factor of more than 7 (Table 1), which is even higher than for Schönau. In fact, the magnitude of the ﬂood not only ren- dered ﬂood reduction by reservoir operation impossible, it even posed a great threat to many retention basins in the re- gion most affected. As a typical example, we brieﬂy sum- marize the course of events at retention basin Horchheim (see Fig. 1). It was built in the 1980s and is operated by the Erftverband for downstream ﬂood protection. The reser- voir volume and outlet gates are designed for protection from H Q100 = 58 m3 s−1, the design ﬂood for ensuring dam stability is H Q10 000 = 90 m3 s−1. In the night from 14 to 15 July, water entering the reservoir exceeded any recorded values. Between 02:00 and 05:00 UTC in the morning of 15 July, i.e., in only 3 h, total inﬂow exceeded twice the entire retention volume. The peak inﬂow was estimated as about 390 m3 s−1, which is about 4 times the H Q10 000. As a consequence, and despite all ﬂood gates opened, the dam overtopped at

LangExtract: Processing, current=615 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=979 chars, processed=0 chars:  [00:05]

------- chunk id 63
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 63: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Unlike the above discussed river basins, the Wupper river basin is located east of the Rhine (see Fig. 1). It is charac- terized by low mountain terrain and several reservoirs, most of them operated by the Wupperverband. The largest reser- voir is the Wupper-Talsperre. It has an upstream basin size of 212 km2 and an overall storage volume of 25.6 × 106 m3; additionally, 9.9 × 106 m3 are available for ﬂood retention. Gauge Hückeswagen (Table 1 and Fig. 6i) is just upstream of the reservoir, and gauge Opladen (Table 1 and Fig. 6j) is far downstream, close to the conﬂuence with the Rhine (see Fig. 1). Just like in the Eifel region west of the Rhine, the rainfall event in the Wupper basin on 14 July was char- acterized by high intensities, large sums, and large spa- tial extent (see Fig. 3a): in an area larger than 1000 km2, 120 to 150 mm of rainfall were recorded within 24 h on 14 July. Even compared to point statistics, these totals ex- ceed 200-year return intervals

LangExtract: Processing, current=1,031 chars, processed=0 chars:  [00:34]
LangExtract: Processing, current=629 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=847 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=428 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,097 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=403 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,038 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,066 chars, processed=0 chars:  [00:31]
LangExtract: Processing, current=954 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=968 chars, processed=0 chars:  [00:05]

------- chunk id 73
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 73: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Figure 7. (a) Flood marks in the municipality of Dernau (Ahrweiler district), including the ﬂoods of 1804, 1910, 2016, and 2021 (© Heinz Grates). (b) One of the collapsed bridges of the Ahr valley railroad (Ahrtalbahn) with trees eroded from the landscape (© Mar- tin Seifert) and (c) bank erosion and collapsed road bridge, both in the municipality of Altenahr (Altenburg; © Bettina Vier). Blue arrows show the river ﬂow direction.
transported as a continuous carpet at the surface of the ﬂow. The recruitment and transport of large debris are not con- sidered in the current practice of ﬂood hazard modeling, un- derestimating the real risk (see Sect. 4.2). We believe that the magnitude of the overland and river ﬂows reported pre- viously (see Sect. 3.2) corresponded to large periods when the ﬂow exceeding the threshold for recruitment of sediment and debris, and that when the peak discharge occurred the channel network was already clogged with solid material.

LangExtract: Processing, current=1,039 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=166 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,043 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=832 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=812 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=763 chars, processed=0 chars:  [00:22]
LangExtract: Processing, current=750 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=800 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=968 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=871 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=674 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=854 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=682 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=575 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,037 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=995 chars, processed=0 chars:  [00:05]

------- chunk id 89
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 89: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: 4.2 Rapid loss estimation and further loss statistics
Based on the rapid quantiﬁcation of the mapped inunda- tion areas (Sect. 4.1), a ﬁrst loss estimation was carried out immediately after the ﬂood (within 1 week; Schäfer et al., 2021) using the loss models (Sect. 4.2) available in CEDIM. The modeling was applied to the whole of Germany; dam- age proportion for Saxony and Bavaria, however, was only about 1 %. Damage was estimated to (a) damage to private assets (including household goods), EUR 4.4 to 13.0 billion; (b) damage to commercial, industrial, and other buildings,
EUR 1.8 to 3.9 billion; and (c) damage to infrastructure, EUR 4.7 to 12 billion (each based on capital stock portions). This results in total estimated damage of EUR 11 to 29 bil- lion (as of 21 July 2021). However, it must be taken into ac- count that the ﬂooded areas represent only a part of the total affected area, so that the extrapolation of the damaged area was associated with high uncertainty at the time.

LangExtract: Processing, current=1,114 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=670 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=797 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=989 chars, processed=0 chars:  [00:04]

------- chunk id 93
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 93: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: 2022; Szymczak et al., 2022), both of which are classiﬁed as critical infrastructures. Most of the disruptions regarding rail and road occurred directly after the event. In the Ahr valley alone, an estimated 103 bridges were damaged or completely destroyed (cf. BMI, 2022). On 15 July 2021, 4 % of the to- tal road trafﬁc reports issued by the police in RP and NRW (Sect. 2.5) were directly related to the ﬂood event. Given the large size of the two states and a generally high number of trafﬁc reports, and since this does not include indirect effects such as trafﬁc jams, this can be considered a high percent- age. In total, 39 road sections and 33 rail lines were affected. This decreased to 1.5 % on 23 July (15 rail lines, 15 road sec- tions), but changed little until 31 July (11 rail lines, 11 road sections). At the end of August 2021, 1 % of total trafﬁc re- ports issued in the two federal states was related to the ﬂood event. The number of disruptions in rail trafﬁc decreased

LangExtract: Processing, current=1,129 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=905 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=901 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=745 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=716 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,024 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=902 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,209 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=131 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=1,020 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=989 chars, processed=0 chars:  [00:04]

------- chunk id 104
Error when applying LangExtract on document Mohr 2022 - A multi-disciplinary analysis of the exceptional flood event of July 2021 in central Europe - Part 1 Event desciption and analysis_cleaned, text block 104: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: In the Ahr valley alone, more than 100 bridges were dam- aged or completely destroyed. On 15 July 2021, about 4 % of the total road trafﬁc reports issued by the police in RP and NRW were directly related to the ﬂood event. In NRW, around 600 km of railroad tracks were affected. In general, about twice as many districts suffered from by rail disrup- tions – with longer required reconstruction times compared to road disruptions. Based on the rapid quantiﬁcation of the mapped inundation areas, we carried out a ﬁrst loss esti- mation using CEDIM’s loss model 1 week after the onset of the ﬂood (Fig. 12). Damage to private assets was esti- mated between EUR 4.4 and 13.0 billion, damage to com- mercial, industrial, and other buildings between EUR 1.8 and 3.9 billion, and damage to infrastructure between EUR 4.7 and 12 billion, thus in total EUR 11 to 29 billion. Several months later, the German government applied to the Euro- pean Commission for a ﬁnancial contribution from the Eu-

LangExtract: Processing, current=500 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=735 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,180 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=724 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,116 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=506 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=925 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,005 chars, processed=0 chars:  [00:21]
LangExtract: Processing, current=851 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,050 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=991 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=639 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=634 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=289 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,090 chars, processed=0 chars:  [00:24]
LangExtract: Processing, current=609 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=1,144 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=494 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=678 chars, processed=0 chars:  [00:03]

 -------- Processing document [9]: Euronews 2024 - Spain floods_ Death toll rises to 205 as nation braces for more rain _cleaned.md --------

LangExtract: Processing, current=673 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=651 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,077 chars, processed=0 chars:  [00:19]
LangExtract: Processing, current=887 chars, processed=0 chars:  [00:05]

------- chunk id 3
Error when applying LangExtract on document Euronews 2024 - Spain floods_ Death toll rises to 205 as nation braces for more rain _cleaned, text block 3: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: (/2026/01/03/at-least- seven-explosions-and-low- 'captured' amid US flying-aircraft-heard-in- strikes on Venezuela venezuelan-capital- caracas) (/2026/01/03/us-strikes- venezuela-and-says- Venezuela until 'safe' maduro-captured) transition
1 Trump says Maduro was 2 Trump says US 'will run' 3 Ukraine orders 3,000
(/2026/01/02/ukraine- orders-evacuation-of- children and parents to 3000-children-and- evacuate two regions parents-from-two-regions- as-russian-forces-) (/green/2026/01/02/tiny- fiddler-crabs-are- hoovering up and hoovering-up-and- breaking down breaking-down- microplastics - study microplastics-study-finds) (/video/2026/01/03/videos- show-explosions-in- in Venezuela's capital venezuelas-capital-caracas) Caracas
Members of the Spanish Guardia Civil carry the body of a person who died during floods in Valencia- Alberto Saiz/Copyright 2024 The AP. All rights reserved.

LangExtract: Processing, current=1,220 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=993 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=894 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,320 chars, processed=0 chars:  [00:28]
LangExtract: Processing, current=1,126 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,086 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,239 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=892 chars, processed=0 chars:  [00:16]
LangExtract: Processing, current=77 chars, processed=0 chars:  [00:05]

 -------- Processing document [10]: ABC 2024 - Traffic jams and flight delays due to heavy rain and lightning storm in Malaga_cleaned.md --------

LangExtract: Processing, current=688 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=831 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=805 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=559 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=972 chars, processed=0 chars:  [00:18]
LangExtract: Processing, current=718 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=555 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=443 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=683 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=600 chars, processed=0 chars:  [00:03]

 -------- Processing document [11]: Rozendaal 2021 - Infrabel_ Flood damage to railway track worth tens of millions of euros _ SpoorPro - incomplete_cleaned.md --------

LangExtract: Processing, current=929 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=728 chars, processed=0 chars:  [00:06]
LangExtract: Processing [00:00]

 -------- Processing document [12]: Skoulding 2023 - Where are the fires in Italy today as temperatures rise to 47.6C on Sicily_ _ The Independent_cleaned.md --------

LangExtract: Processing, current=1,186 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=926 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=642 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=899 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=936 chars, processed=0 chars:  [00:06]
LangExtract: Processing [00:00]

 -------- Processing document [13]: PWC 2015 - Updated estimates on cost of Storm Desmond_cleaned.md --------

LangExtract: Processing, current=507 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,011 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,033 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=904 chars, processed=0 chars:  [00:01]
LangExtract: Processing [00:00]

 -------- Processing document [14]: The Vibes 2022 - Valencia Airport in Madrid briefly shut as lightning hits runway _ World _cleaned.md --------

LangExtract: Processing, current=1,250 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=966 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=273 chars, processed=0 chars:  [00:06]

 -------- Processing document [15]: Gilbody Dickerson 2024 - Spain floods_ At least 95 people killed including British man near Malaga _ World News _ Sky News_cleaned.md --------

LangExtract: Processing, current=449 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=702 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=774 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=756 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=400 chars, processed=0 chars:  [00:18]
LangExtract: Processing, current=698 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=656 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=620 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=594 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=708 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=416 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=610 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=839 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=169 chars, processed=0 chars:  [00:24]

 -------- Processing document [16]: Korzilius 2021 -  Nach der Flut  Rheinisches Ärzteblatt 10 -  p12–16_cleaned.md --------

Token indices sequence length is longer than the specified maximum sequence length for this model (513 > 512). Running this sequence through the model will result in indexing errors
LangExtract: Processing, current=455 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=606 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=534 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=425 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=582 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=707 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=471 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=752 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=296 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=729 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=733 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=303 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=593 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=567 chars, processed=0 chars:  [00:19]
LangExtract: Processing, current=430 chars, processed=0 chars:  [00:21]
LangExtract: Processing, current=671 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=448 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=598 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=637 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=616 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=685 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=330 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=732 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=154 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=614 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=506 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=755 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=576 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=418 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=550 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=272 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=554 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=748 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=84 chars, processed=0 chars:  [00:05]

 -------- Processing document [17]: Treanor 2015 - Storm Desmond damage across Cumbria estimated at £500m _ Storm Desmond _The Guardian_cleaned.md --------

LangExtract: Processing, current=775 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=793 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=853 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,233 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,040 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=288 chars, processed=0 chars:  [00:03]

 -------- Processing document [18]: Karakatsani 2023 - Greece economy briefing The economic impact of the recent devastating floods in Greece_cleaned.md --------

LangExtract: Processing, current=1,468 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=1,367 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,297 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,235 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=997 chars, processed=0 chars:  [00:05]

------- chunk id 4
Error when applying LangExtract on document Karakatsani 2023 - Greece economy briefing The economic impact of the recent devastating floods in Greece_cleaned, text block 4: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: estimations increased the cost to 2.5 bil euros. Nevertheless, the damage assessment has not yet
been completed, and thus the final cost of the damages is not yet known. It is worth noting that
some economists argue that the cost will increase up to 3-5 bil euros, by taking into account not
only the fiscal cost but the total impact to the economy (7).
According to a report published by Alpha Bank, in 2022 Thessaly contributed 5.2% of
the country’s GDP and produced 14,1% of the agricultural production. In addition, 6,4% of the
work force of the country lives in Thessaly, among which 20,1% work in the agricultural sector.
Some estimate that the cost of the flood damages will negatively affect not only the local and
regional-economic figures, such as production, incomes, employment etc but in addition the
financial figures of the Greek economy as a whole. Specifically, GDP growth will decrease by
0.2% in 2023, 0,35% in 2024, 0,3% in 2025 and 0.2% in 2026. Moreover, it is estimated that

LangExtract: Processing, current=1,131 chars, processed=0 chars:  [00:13]

------- chunk id 5
Error when applying LangExtract on document Karakatsani 2023 - Greece economy briefing The economic impact of the recent devastating floods in Greece_cleaned, text block 5: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: the effects on the imports will be larger, with imports increasing by 0.1% in 2023, 0.5% in 2024,
0,4%  in  2025  and  0,2%  in  2026.  A  smaller  impact  is  estimated  in  unemployment,  which  is
projected to increase by 0.3 percentage points in 2025 and thus reaching 10.3%. Overall, over
the period of four years, it is estimated that the GDP in Greece will show losses up to 38 bil
euros,  as  a  consequence  of  the  floods  in  Thessaly.  In  accordance  with  this  scenario,  it  is
expected  that  withing  the  next  four  years  and  taking  into  account  the  environment  of
international and European economic slowdown, as well as the strict fiscal rules in the EU, the
socio-economic problems of the Greek economy will worsen, together with the of widening
fiscal-economic imbalance and social inequalities in the country (8).
It is worth to be mentioned that despite all analysts agreeing that there will be a negative
impact in the economy, the extent of which is not yet known. Despite the latter arguments that
the impact to the economy will be quite significant, other reports mention a lesser extent of the

LangExtract: Processing, current=1,324 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=714 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=310 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=51 chars, processed=0 chars:  [00:24]
LangExtract: Processing, current=382 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=198 chars, processed=0 chars:  [00:03]

 -------- Processing document [19]: AFP 2022 - The_Vibes_Valencia Airport in Madrid briefly shut as lightning hits runway _ World _ The Vibes_cleaned.md --------

LangExtract: Processing, current=1,250 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=966 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=226 chars, processed=0 chars:  [00:05]

 -------- Processing document [20]: Kaur 2025 - Authorities suspect arson in 17 wildfires across Dalmatian coast, Croatia - The Watchers_cleaned.md --------

LangExtract: Processing, current=1,097 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,110 chars, processed=0 chars:  [00:33]
LangExtract: Processing, current=1,302 chars, processed=0 chars:  [00:10]

------- chunk id 2
Error when applying LangExtract on document Kaur 2025 - Authorities suspect arson in 17 wildfires across Dalmatian coast, Croatia - The Watchers_cleaned, text block 2: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Interior vessel and a civilian craft. These units evacuated 25 residents from
Marušići. Additionally, 94 individuals, mostly tourists, were evacuated as a
precaution and returned once the area was stabilized.
Police authorities, led by Deputy Chief Siniša Mihanović of the Split-Dalmatia
Police Department, stated that at least one fire in the Makarska area was the result
of arson. All 17 fires are being treated as deliberately set.
Increased patrols and surveillance are being conducted across the region,
As of June 23, the fire has been largely contained, though flare-ups continue to be
monitored by on-site teams. The fire will only be declared extinguished once all
personnel are withdrawn and smoldering is fully resolved.
I’m a science journalist and researcher at The Watchers,
contributing to the Epicenter edition, where I cover peer-
reviewed scientific research and emerging discoveries
across Earth and space sciences. With a background in
astronomy and a passion for environmental science, I’ve
worked in shark and coral conservation in Fiji, conducting
reef and shark-behavior research, contributing to mangrove
restoration, and earning PADI Open Water and Coral Reef
Certifications. I bring a blend of scientific rigor and
storytelling to illuminate the discoveries shaping our planet

LangExtract: Processing, current=870 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=919 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,079 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=386 chars, processed=0 chars:  [00:03]

 -------- Processing document [21]: Lloyd's List 2024 - Port of Valencia reopens after devastating floods_cleaned.md --------

LangExtract: Processing, current=1,215 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,009 chars, processed=0 chars:  [00:04]
LangExtract: Processing [00:00]

 -------- Processing document [22]: Keller 2014 - Mapping Natural Hazard Impacts on Road Infrastructure—The Extreme Precipitation in Baden-Württemberg_cleaned.md --------

LangExtract: Processing, current=320 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,238 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=206 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,036 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=966 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,230 chars, processed=0 chars:  [00:18]
LangExtract: Processing, current=1,181 chars, processed=0 chars:  [00:04]

------- chunk id 6
Error when applying LangExtract on document Keller 2014 - Mapping Natural Hazard Impacts on Road Infrastructure—The Extreme Precipitation in Baden-Württemberg_cleaned, text block 6: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: the authors present an explanatory approach. Based on an observational design, causal con- nections between the occurrence and spatiotemporal pat- terns of extreme events and infrastructure impacts should be explained. Using secondary data on actual events, this approach provides a different perspective and complements the experimental research conducted in other projects. The present hazard mapping case study combines trafﬁc infor- mation and data on the extreme precipitation that occurred in Germany in early June 2013.1 It focuses on the hazard effects in the state of Baden-Wu¨rttemberg, where more than 100 hazardous incidents occurred within a few days. The case study is based on a systemic framework for the assessment of infrastructure risks introduced by Atzl and Keller (2013). The framework differentiates between three systemic constituents: the critical infrastructure, its natural environment, and its social environment, all of which interact (Atzl and Keller 2013). To facilitate the analysis of causal connections across systems and sectors, existing concepts and deﬁnitions of natural processes, hazards, and disasters are applied to this systemic framework.

LangExtract: Processing, current=1,037 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=791 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,214 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=488 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=985 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=739 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=479 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,058 chars, processed=0 chars:  [00:30]
LangExtract: Processing, current=289 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=1,193 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=678 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=811 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=943 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=850 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,029 chars, processed=0 chars:  [00:33]
LangExtract: Processing, current=996 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,124 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,090 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=615 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,097 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=187 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,068 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=842 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,019 chars, processed=0 chars:  [00:05]

------- chunk id 30
Error when applying LangExtract on document Keller 2014 - Mapping Natural Hazard Impacts on Road Infrastructure—The Extreme Precipitation in Baden-Württemberg_cleaned, text block 30: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: In total, 92 incidents with road closures occurred during the study period accounting for around 80 % of all inci- dents (Table 3). While road closures on federal freeways were unidirectional or limited to single lanes, federal highways were completely closed in more than 20 cases, two-thirds of them for more than one day. Around 70 % of the road incidents were caused by ﬂooding or ﬂooding risk (Table 4). Due to higher speed limits, hydroplaning was
mainly a problem on freeways and some federal highways. In total, hydroplaning accounted for 6 % of all road inci- dents. Around one-fourth of all incidents were caused by landslides or landslide risks.
Figures 4 and 5 provide an overview of the spatiotemporal change of hazard patterns during the case study event. Both ﬁgures include ﬁve maps showing the daily precipitation rates for days 3–7. Days 1 and 2 are not included due to low precipitation rates and only one road incident. Figure 4
Keller and Atzl. Mapping Natural Hazard Impacts on Road Infrastructure

LangExtract: Processing, current=986 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,036 chars, processed=0 chars:  [00:19]
LangExtract: Processing, current=466 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=914 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,052 chars, processed=0 chars:  [00:31]

------- chunk id 35
Error when applying LangExtract on document Keller 2014 - Mapping Natural Hazard Impacts on Road Infrastructure—The Extreme Precipitation in Baden-Württemberg_cleaned, text block 35: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: On day 6 (center right maps in Figs. 4 and 5), precipi- tation stopped in most parts of Baden-Wu¨rttemberg, with low rainfall in the northeast. However, the number of road incidents still increased overnight. A new peak of 45 incidents was reached by 7 a.m. New disturbances and closures occurred on ﬂooded federal highways along the Neckar River south of Stuttgart and east of Mannheim. Federal freeway A8 between Karlsruhe and Stuttgart was partially closed due to ﬂooding and federal freeway A96 in southeast Baden-Wu¨rttemberg was partially closed for a few hours due to a landslide. The number of road incidents on the outskirts of the Swabian Alb and the northern edges of the Black Forest remained stable.
The last day of the case study period, day 7, was nearly free of precipitation in Baden-Wu¨rttemberg (lower left maps in Figs. 4 and 5). Most road incidents disappeared by
Table 4 Hazards causing road incidents in Baden-Wu¨rttemberg from 28 May to 3 June 2013 (n = 117)
Keller and Atzl. Mapping Natural Hazard Impacts on Road Infrastructure

LangExtract: Processing, current=974 chars, processed=0 chars:  [00:04]

------- chunk id 36
Error when applying LangExtract on document Keller 2014 - Mapping Natural Hazard Impacts on Road Infrastructure—The Extreme Precipitation in Baden-Württemberg_cleaned, text block 36: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: b Fig. 5 Precipitation and spatiotemporal appearance of different types of road incidents in Baden-Wu¨rttemberg, Germany, 30 May–3 June 2013. Source Maps by authors based on DWD REGNIE dataset 2013, IMBW dataset 2013, and Esri dataset 2005
noon with 13 left at 10 a.m. and 2 incidents left at 11 a.m. (Fig. 3). The last incidents included ﬂooded federal high- ways in the Neckar Valley east of Mannheim, minor roads around Karlsruhe, and roads on the northern border of the Swabian Alb. However, closures of roads leading up to the Swabian Alb lasted longer than the case study period.
4.3 Spatiotemporal Patterns and Hazard Characteristics
To clarify the spatiotemporal patterns on the basis of the above mapping, the hazards are characterized following the concepts developed by Egli (1996) and Bloetzer (1998), who deﬁne ﬁve natural hazard characteristics: limitation to speciﬁc locations; limitation to time; spontaneity; limita- tion to space; possibility to intervene.

LangExtract: Processing, current=1,151 chars, processed=0 chars:  [00:25]
LangExtract: Processing, current=625 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=1,098 chars, processed=0 chars:  [00:20]
LangExtract: Processing, current=622 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,147 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=707 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,193 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=1,156 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=1,065 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,266 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=343 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=956 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=914 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=978 chars, processed=0 chars:  [00:06]

 -------- Processing document [23]: The Guardian 2018 - Freezing weather costs UK economy £1bn a day _ UK weather_cleaned.md --------

LangExtract: Processing, current=1,230 chars, processed=0 chars:  [00:10]

------- chunk id 0
Error when applying LangExtract on document The Guardian 2018 - Freezing weather costs UK economy £1bn a day _ UK weather_cleaned, text block 0: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Financial impact of the ‘beast from the east’ and storm Emma worst since Christmas 2010
Gridlocked motorways, empty restaurants and idle diggers seen across Britain last week cost the economy at least £1bn a day and could halve GDP growth in the ﬁrst three months of the year.
Analysts said the impact of the “beast from the east” sweeping in from Siberia and the arrival of Storm Emma hitting the south coast was likely to be the most costly weather event since 2010, when freezing temperatures and snow brought the economy to a standstill a week before Christmas.
The extreme weather was likely to have the biggest impact on the construction industry, which experts said could lose up to £2bn over the three worst days, as sub-zero temperatures forced building workers to down tools.
Transport networks and retailers were also expected to count the cost of the freezing weather following multiple rail cancellations, a string of crashes on motorways and A roads, and warnings that workers should stay at home, keeping them away from the high street.
Economists said GDP growth, which indicates how much national income has expanded, could fall by up to 0.2% in the ﬁrst quarter of the year, halving the expected 0.4% growth rate.

LangExtract: Processing, current=1,003 chars, processed=0 chars:  [00:20]
LangExtract: Processing, current=1,083 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=1,134 chars, processed=0 chars:  [00:12]

------- chunk id 3
Error when applying LangExtract on document The Guardian 2018 - Freezing weather costs UK economy £1bn a day _ UK weather_cleaned, text block 3: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: A spokesman for the Rail Delivery Group, the train operators’ lobby group, said: “Invariably, the bad weather this week will have had an impact on ticket sales but the main focus of every rail worker has been to keep lines open and people moving. We’d encourage our customers to continue checking before they travel and to claim any compensation they might be due for delayed or cancelled journeys.”
Cancellations due to weather may see Network Rail footing the bill in “schedule 8 payments”, compensating train operators for infrastructure issues – although operators whose trains have broken down may ﬁnd themselves presented with bills in reverse.
But refunds to passengers will be only part of the costs, with many people choosing not to travel during a week of disruption and weather warnings.
A spokesman for Glasgow airport said last week’s snowfall was double the previous record of 18cm in 1996.
He did not put a ﬁgure on the cost of cancellations, but said that the revenues of the last two days were simply lost, and the airport did not expect that to be made up by its 25,000 passengers each day travelling at a later date.

LangExtract: Processing, current=883 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,131 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=998 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=244 chars, processed=0 chars:  [00:06]

 -------- Processing document [24]: Brown 2010 - Economy feels chill as UK grinds to a halt _ The Independent_cleaned.md --------

LangExtract: Processing, current=723 chars, processed=0 chars:  [00:05]

------- chunk id 0
Error when applying LangExtract on document Brown 2010 - Economy feels chill as UK grinds to a halt _ The Independent_cleaned, text block 0: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Cost of travel and retail chaos running at &#163;1bn a day / Government under pressure over lack of preparation
Get the free Morning Headlines email for news from our reporters across the world
I would like to be emailed about oﬀers, events and updates from The Independent. Read our Privacy notice
The economic impact of the freezing winter will deepen this week as Britain prepares for more travel gridlock, and millions of workers, travellers and shoppers were expected to stay at home in the run-up to Christmas rather than brave the icy conditions.
Heavy snow and sub-zero temperatures cost the aviation and retail industries many millions of pounds in lost revenue during one of the most crucial weekends of the year.

LangExtract: Processing, current=867 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=942 chars, processed=0 chars:  [00:05]

------- chunk id 2
Error when applying LangExtract on document Brown 2010 - Economy feels chill as UK grinds to a halt _ The Independent_cleaned, text block 2: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Howard Archer, the chief economist at IHS Global Insight, said many ﬁrms could now consider working between Christmas and the New Year to make up for lost business. But retailers, who had been hoping for a bonanza festive season as consumers sought to beat the January VAT rise, fear that many shoppers might now simply not bother.
"It now looks highly probable that some people may end up buying fewer Christmas presents and these sales are not subsequently made up," said Mr Archer. "If the bad weather persists most or all of the coming week, these problems will be magniﬁed."
Even John Lewis, which has been leading the revival in the UK's high street's fortunes, saw sales slump by 10 per cent on Saturday, enduring nearly £5m in lost revenue when two of its 32 stores were closed by the weather on what should have been the biggest trading day of the year. Brent Cross shopping centre in north-west London was forced to close its doors.

LangExtract: Processing, current=1,038 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=924 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=813 chars, processed=0 chars:  [00:06]
LangExtract: Processing [00:00]

 -------- Processing document [25]: Artemis 2015 - PERILS finalises Storm Desmond UK flood loss estimate at £604m_cleaned.md --------

LangExtract: Processing, current=1,197 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=974 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=908 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=999 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=157 chars, processed=0 chars:  [00:05]

 -------- Processing document [26]: Wilson 2024 - Flash floods in Spain sweep away cars, disrupt trains and leave several missing _ AP News_cleaned.md --------

LangExtract: Processing [00:00]
LangExtract: Processing, current=1,096 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=437 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=742 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=413 chars, processed=0 chars:  [00:03]

 -------- Processing document [27]: EFE 2024 - The DANA storm, live_ The death toll rises to 158_cleaned.md --------

LangExtract: Processing, current=939 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=790 chars, processed=0 chars:  [00:20]
LangExtract: Processing, current=1,079 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=934 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=894 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,290 chars, processed=0 chars:  [00:33]
LangExtract: Processing, current=1,105 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=900 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,125 chars, processed=0 chars:  [00:26]
LangExtract: Processing, current=901 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=814 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=930 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=886 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=929 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=747 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=857 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=798 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=608 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=938 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=866 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=649 chars, processed=0 chars:  [00:06]

 -------- Processing document [28]: Plag 2014 - Foreword extreme geohazards—a growing threat for a globally interconnected civilization_cleaned.md --------

LangExtract: Processing, current=281 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=912 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,278 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,107 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,158 chars, processed=0 chars:  [00:25]
LangExtract: Processing, current=656 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,023 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=900 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,328 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=885 chars, processed=0 chars:  [00:06]

 -------- Processing document [29]: Korzilius 2021 Nach der Flut_cleaned.md --------

Token indices sequence length is longer than the specified maximum sequence length for this model (513 > 512). Running this sequence through the model will result in indexing errors
LangExtract: Processing, current=455 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=606 chars, processed=0 chars:  [00:21]
LangExtract: Processing, current=534 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=425 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=582 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=707 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=471 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=752 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=296 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=729 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=733 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=303 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=593 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=567 chars, processed=0 chars:  [00:19]
LangExtract: Processing, current=430 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=671 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=448 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=598 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=637 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=616 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=685 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=330 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=732 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=154 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=614 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=506 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=755 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=576 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=418 chars, processed=0 chars:  [00:18]
LangExtract: Processing, current=550 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=272 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=554 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=748 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=84 chars, processed=0 chars:  [00:05]

 -------- Processing document [30]: UNEP 2013 - Impacts of summer 2003_cleaned.md --------

LangExtract: Processing, current=720 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,060 chars, processed=0 chars:  [00:10]

------- chunk id 1
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 1: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: More than 25 000 fires were recorded in Portugal, Spain, Italy,  France,  Austria,  Finland,  Denmark  and  Ireland.  The estimation  of  forest  areas  destroyed  reached  647  069 hectares. Portugal was the worst hit with 390 146 ha burned, destroying  around  5.6  %  of  its  forest  area.  Spain  came second with 127 525 ha burned. The agricultural area burned reached  44 123  ha  plus  8,973  ha  of  unoccupied  land,  and 1 700  ha  of  inhabited  areas. This  was  by  far  the  worst  forest fire  season  that  Portugal  had  faced  in  the  last  23  years.  In October  2003,  the  financial  impact  estimated  by  Portugal exceeded 1 billion euros.
COPA COGECA 2003: Assessment of the impact of the heat wave and drought of the summer 2003 on agriculture and forestry. EU-JRC 2003: The European Forest Fires Information System (EFFIS) results on the 2003 fire season in Portugal to the 20th of August.
G R I D E u r o p e A. De Bono, G. Giuliani, S. Kluser, P. Peduzzi March 2004
European  heat  wave  and  global  warming:  extremes increasing

LangExtract: Processing, current=1,361 chars, processed=0 chars:  [00:11]

------- chunk id 2
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 2: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The  record  high  temperatures  in  the  summer  of  2003,  and repetitive  temperature  records,  raise  the  problem  of  global warming impacts on human activities and ecosystems.
Global warming is a fact proven by the scientific community. According  to  the  last  IPCC1  assessment  report,  the  global average  surface  temperature  has  increased  over  the  20th century by about 0.6 °C. This value is about 0.15°C higher than that  estimated  by  the  previous  reports.  Data  for  the  Northern Hemisphere indicate that the increase in temperature in the 20th century  is  likely  to  have  been  the  largest  and  fastest  in  any century during the past 1000 years.
New  record  extreme  events  occur  every  year  somewhere on  the  globe,  but  in  recent  years  the  number  of  such  extremes has  been  increasing  (WHO  Press  release).  We  cannot  directly attribute  this  one  event  to  climate  change,  but  this  type  of occurrence  is  expected  to  happen  more  frequently.  The  heat wave that hit Europe in the summer of 2003 can be seen as one more warning of impacts from a warmer climate on populations and ecosystem. ♦
IPCC: Intergovernmental Panel on Climate Change; "Third Assessment Report"
"As the global temperatures continue to warm due to climate change, the number and intensity of extreme events might increase"

LangExtract: Processing, current=1,135 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,173 chars, processed=0 chars:  [00:11]

------- chunk id 4
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 4: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Extreme  maximum  temperatures  of  35  to  40°C  were repeatedly recorded in July and to a larger extent in August in most of the southern, and central countries from Germany to Turkey. This extreme wheather was caused by an anti-cyclone firmly anchored over the western European land mass holding back  the  rain-bearing  depressions  that  usually  enter  the continent  from  the  Atlantic  ocean. This  situation  was  excep- tional  in  the  extended  length  of  time  (over  20  days)  during which it conveyed very hot dry air up from south of the Medi- terranean.
The all-time maximum temperature recorded in the United Kingdom  was  broken  on  10  August,  with  38.1°C;    tempera- tures in France soared to 40 °C and remained unusually high
for  two  weeks.  In  Switzerland,  June  was  the  hottest  month ever  recorded  in  250  years  of  archives  and  a  temperature record  of  41.5  °C  was  reached  on  August  11. With  tempera- tures  exceeding  the  average  by  +5.4°C  in  Geneva,  the prevailing conditions corresponded to a usual summer in Rio de Janeiro! July was characterised by dry conditions centred on France, Spain, Germany and Italy.

LangExtract: Processing, current=928 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=901 chars, processed=0 chars:  [00:05]

------- chunk id 6
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 6: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: France  reported  14  802  casualties  using  a  method from  the  National  Institute  of  Health  and  Medical Research (INSERM, France). This figure was reached by counting  the  number  of  deaths  over  and  above  what would  normally  be  expected  for  the  month  of  August. Italy  followed  the  same  formula  and  counted  more  than 4'000  elderly  casualites  during  the  month  of  August  in Italy's 21 largest cities.
Country France Germany Spain Italy UK Netherlands Portugal Belgium
Casualties 14 082 7 000 4 200 4 000 2 045 1 400 1 300 150
INSERM: "Surmortalité liée à la canicule de l'été 2003", AP September 25, 2003
This  year's  extreme  weather  conditions  decreased  the quantity  and  quality  of  the  harvests,  particularly  in Central  and  Southern  European  agricultural  areas; threatening  a  large  proportion  of  harvests,  and  increas- ing production costs.

LangExtract: Processing, current=963 chars, processed=0 chars:  [00:05]

------- chunk id 7
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 7: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The winter crops already suffered from the effects of a harsh winter and late spring frost. The heat wave that began in early June accelerated crop development by 10 to  20  days,  thus  advancing  ripening  and  maturity. Winter-spring  cereals  formed  grain  with  insufficient  soil moisture. The very high air temperature and solar radia- tion, especially from the second part of July to the begin- ning  of  August,  resulted  in  a  notable  increase  in  the crops'  water  consumption.  This,  together  with  the summer  dry  spell,  resulted  in  an  acute  depletion  of  soil water  and  lowered  crop  yields.  Even  in  Switzerland,  the "water tower" of Europe, river withdrawals for agricultural use  were  banned  in  some  cantons  from  July  to  mid October,  thus  affecting  producers  of  potatoes  and tobacco.  According  to  the  Union  of  Swiss  Farmers,  the agricultural  deficit  reached  more  than  300  millions  CHF (~US$ 230).

LangExtract: Processing, current=1,259 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=1,362 chars, processed=0 chars:  [00:12]

------- chunk id 9
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 9: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: COPA  COGECA  2003:  Assessment  of  the  impact  of  the  heat  wave  and  drought  of  the summer 2003 on agriculture and forestry.
"Mass of Alpine glaciers decreased by up to 10% in 2003"
According to Professor Wilfried Haeberli, director of the World Glacier Monitoring Service (WGMS) at the Geography Department, University of  Zurich,  first  results  from  field  measurements  indicate  that  the extreme warm and dry weather conditions in summer 2003 caused an average loss in thickness of glaciers in the European Alps of about 3 meters water equivalent (see graph on the right), nearly twice as much as  during  the  previous  record  year  of  1998  (1.6  m),  and  roughly  five times more than the average loss of 0.65 m per year recorded during the exceptionally warm period 1980 - 2000.
The World Glacier Monitoring Service follows the evolution of annual glacier  mass  balance  (thickness  change)  through  the  monitoring  of more than 60 reference glaciers worldwide and 14 glaciers in the Alps. In 2003 alone, the total glacier volume loss in the Alps corresponds to
Drought  affects  the  state  of  vegetation  by  lowering  photosynthetic activity  leading  to  a  reduction  in  productivity,  in  particular  for  crops and fodder. It also affects forests, weakening trees and making them more vulnerable to diseases and insect attacks.

LangExtract: Processing, current=1,366 chars, processed=0 chars:  [00:11]

------- chunk id 10
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 10: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Another  consequence  of  the  heat  wave  was  to  force  the  early harvest  of  crops  that  became  mature  much  earlier  than  usual.  In addition,  some  types  of  vegetation  were  killed  by  the  extreme
conditions  of  drought  and  temperatures  bordering  on  40°C. Water  stress  also  encourages  forest  fires,  which  were particularly intense with the exceptional climatic conditions of the summer of 2003.
The effects of the drought on vegetation are clearly visible. The images represent the variation of the vegeta- tion index in the summer of 2003 compared to the summer of 2002. The blue zones on the map represent a vegetation condition in 2003 similar to that in 2002. Spain appears in blue as 2003 was as dry as 2002. The green,  yellow  red,  areas  were  drier  than  in  2002.  Above  all  drought  affected  the  South  Western  part  of France, the Central Massive and the Northern part of Italy. This caused the yellowing or early fall of leaves, early harvesting, forest fires.
The heat wave spelled trouble for France's nuclear reactors, many of which  are  cooled  by  river  water. The  plants  return  cooling  water  to the rivers, but only after it has cooled down to reduce the impact on the environment. In some regions, river water levels dropped so low that  cooling  process  became  impossible  and  plants  had  to  shut

LangExtract: Processing, current=950 chars, processed=0 chars:  [00:05]

------- chunk id 11
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 11: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Mass balance based on 10 alpine glaciers: St. Sorlin, Sarennes, Silvretta, Gries,Sonnblickkees, Vernagtferner, Kesselwandferner, Hintereis-ferner, Caresèr.
Courtesy: Regula Frauenfelder (World Glacier Monitoring Service, Zürich)
5-10%  (probably  closer  to  10%)  of  the  remaining  ice  volume.  Alpine glaciers  had  already  lost  more  than  25%  of  their  volume  in  the  25 years  before  2003,  and  roughly  two-thirds  of  their  original  volume since  1850  (see  figure  to  left).  At  such  rates,  less  than  50%  of  the glacier volume still present in 1970/80 would remain in 2025 and only about 5% in 2100."
Left:  This  3D  view  of  the  Aletsch  region  with  a  satellite  image  from  1997, depicts  glacier  extent  of  1850  (in  red),  1973  (in  blue).  The  Aletsch  glacier  is now formally a part of the UNESCO World Heritage Programme.
Sources: Geography Department, University of Zurich, DEM25 (C) 2003 swisstopo.

LangExtract: Processing, current=998 chars, processed=0 chars:  [00:05]

------- chunk id 12
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 12: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: down,  while  elsewhere  the  water  temperatures  after  the cooling  process  exceeded  environmental  safety  levels.  An exceptional  exemption  from  the  legal  requirements  was granted to six nuclear reactors and a number of conventional power  stations:  The  nuclear  power  plants  of  Saint-Alban (Isère),  Golfech (Ardèche), Nogent-sur-Seine  (Aube),  Tricastin  (Drôme)  et  Bugey  (Ain) continued  functioning,  although  the  upper  legal  limits  were exceeded.
Moreover, demand for electricity soared as the population turned  up  air  conditioning  and  refrigerators,  but  nuclear power  stations,  which  generate  around  75%  of  France's electricity,  operated at a much reduced capacity. In order to conserve  energy  for  the  nation,  France  (Europe's  main electricity exporter) cut its power exports by more than half.
"The Guardian" August 13, 2003, "Le Monde" August 13, 2003 EDF Note d'information August 29, 2003
Permafrost changes affect long-term rock stability

LangExtract: Processing, current=1,226 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=901 chars, processed=0 chars:  [00:05]

------- chunk id 14
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 14: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: France  reported  14  802  casualties  using  a  method from  the  National  Institute  of  Health  and  Medical Research (INSERM, France). This figure was reached by counting  the  number  of  deaths  over  and  above  what would  normally  be  expected  for  the  month  of  August. Italy  followed  the  same  formula  and  counted  more  than 4'000  elderly  casualites  during  the  month  of  August  in Italy's 21 largest cities.
Country France Germany Spain Italy UK Netherlands Portugal Belgium
Casualties 14 082 7 000 4 200 4 000 2 045 1 400 1 300 150
INSERM: "Surmortalité liée à la canicule de l'été 2003", AP September 25, 2003
This  year's  extreme  weather  conditions  decreased  the quantity  and  quality  of  the  harvests,  particularly  in Central  and  Southern  European  agricultural  areas; threatening  a  large  proportion  of  harvests,  and  increas- ing production costs.

LangExtract: Processing, current=963 chars, processed=0 chars:  [00:05]

------- chunk id 15
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 15: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The winter crops already suffered from the effects of a harsh winter and late spring frost. The heat wave that began in early June accelerated crop development by 10 to  20  days,  thus  advancing  ripening  and  maturity. Winter-spring  cereals  formed  grain  with  insufficient  soil moisture. The very high air temperature and solar radia- tion, especially from the second part of July to the begin- ning  of  August,  resulted  in  a  notable  increase  in  the crops'  water  consumption.  This,  together  with  the summer  dry  spell,  resulted  in  an  acute  depletion  of  soil water  and  lowered  crop  yields.  Even  in  Switzerland,  the "water tower" of Europe, river withdrawals for agricultural use  were  banned  in  some  cantons  from  July  to  mid October,  thus  affecting  producers  of  potatoes  and tobacco.  According  to  the  Union  of  Swiss  Farmers,  the agricultural  deficit  reached  more  than  300  millions  CHF (~US$ 230).

LangExtract: Processing, current=1,259 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,362 chars, processed=0 chars:  [00:14]

------- chunk id 17
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 17: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: COPA  COGECA  2003:  Assessment  of  the  impact  of  the  heat  wave  and  drought  of  the summer 2003 on agriculture and forestry.
"Mass of Alpine glaciers decreased by up to 10% in 2003"
According to Professor Wilfried Haeberli, director of the World Glacier Monitoring Service (WGMS) at the Geography Department, University of  Zurich,  first  results  from  field  measurements  indicate  that  the extreme warm and dry weather conditions in summer 2003 caused an average loss in thickness of glaciers in the European Alps of about 3 meters water equivalent (see graph on the right), nearly twice as much as  during  the  previous  record  year  of  1998  (1.6  m),  and  roughly  five times more than the average loss of 0.65 m per year recorded during the exceptionally warm period 1980 - 2000.
The World Glacier Monitoring Service follows the evolution of annual glacier  mass  balance  (thickness  change)  through  the  monitoring  of more than 60 reference glaciers worldwide and 14 glaciers in the Alps. In 2003 alone, the total glacier volume loss in the Alps corresponds to
Drought  affects  the  state  of  vegetation  by  lowering  photosynthetic activity  leading  to  a  reduction  in  productivity,  in  particular  for  crops and fodder. It also affects forests, weakening trees and making them more vulnerable to diseases and insect attacks.

LangExtract: Processing, current=1,366 chars, processed=0 chars:  [00:11]

------- chunk id 18
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 18: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Another  consequence  of  the  heat  wave  was  to  force  the  early harvest  of  crops  that  became  mature  much  earlier  than  usual.  In addition,  some  types  of  vegetation  were  killed  by  the  extreme
conditions  of  drought  and  temperatures  bordering  on  40°C. Water  stress  also  encourages  forest  fires,  which  were particularly intense with the exceptional climatic conditions of the summer of 2003.
The effects of the drought on vegetation are clearly visible. The images represent the variation of the vegeta- tion index in the summer of 2003 compared to the summer of 2002. The blue zones on the map represent a vegetation condition in 2003 similar to that in 2002. Spain appears in blue as 2003 was as dry as 2002. The green,  yellow  red,  areas  were  drier  than  in  2002.  Above  all  drought  affected  the  South  Western  part  of France, the Central Massive and the Northern part of Italy. This caused the yellowing or early fall of leaves, early harvesting, forest fires.
The heat wave spelled trouble for France's nuclear reactors, many of which  are  cooled  by  river  water. The  plants  return  cooling  water  to the rivers, but only after it has cooled down to reduce the impact on the environment. In some regions, river water levels dropped so low that  cooling  process  became  impossible  and  plants  had  to  shut

LangExtract: Processing, current=950 chars, processed=0 chars:  [00:05]

------- chunk id 19
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 19: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Mass balance based on 10 alpine glaciers: St. Sorlin, Sarennes, Silvretta, Gries,Sonnblickkees, Vernagtferner, Kesselwandferner, Hintereis-ferner, Caresèr.
Courtesy: Regula Frauenfelder (World Glacier Monitoring Service, Zürich)
5-10%  (probably  closer  to  10%)  of  the  remaining  ice  volume.  Alpine glaciers  had  already  lost  more  than  25%  of  their  volume  in  the  25 years  before  2003,  and  roughly  two-thirds  of  their  original  volume since  1850  (see  figure  to  left).  At  such  rates,  less  than  50%  of  the glacier volume still present in 1970/80 would remain in 2025 and only about 5% in 2100."
Left:  This  3D  view  of  the  Aletsch  region  with  a  satellite  image  from  1997, depicts  glacier  extent  of  1850  (in  red),  1973  (in  blue).  The  Aletsch  glacier  is now formally a part of the UNESCO World Heritage Programme.
Sources: Geography Department, University of Zurich, DEM25 (C) 2003 swisstopo.

LangExtract: Processing, current=998 chars, processed=0 chars:  [00:05]

------- chunk id 20
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 20: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: down,  while  elsewhere  the  water  temperatures  after  the cooling  process  exceeded  environmental  safety  levels.  An exceptional  exemption  from  the  legal  requirements  was granted to six nuclear reactors and a number of conventional power  stations:  The  nuclear  power  plants  of  Saint-Alban (Isère),  Golfech (Ardèche), Nogent-sur-Seine  (Aube),  Tricastin  (Drôme)  et  Bugey  (Ain) continued  functioning,  although  the  upper  legal  limits  were exceeded.
Moreover, demand for electricity soared as the population turned  up  air  conditioning  and  refrigerators,  but  nuclear power  stations,  which  generate  around  75%  of  France's electricity,  operated at a much reduced capacity. In order to conserve  energy  for  the  nation,  France  (Europe's  main electricity exporter) cut its power exports by more than half.
"The Guardian" August 13, 2003, "Le Monde" August 13, 2003 EDF Note d'information August 29, 2003
Permafrost changes affect long-term rock stability

LangExtract: Processing, current=1,086 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,244 chars, processed=0 chars:  [00:18]
LangExtract: Processing, current=1,076 chars, processed=0 chars:  [00:20]
LangExtract: Processing, current=996 chars, processed=0 chars:  [00:04]

------- chunk id 24
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 24: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: New  record  extreme  events  occur  every  year  somewhere on  the  globe,  but  in  recent  years  the  number  of  such  extremes has  been  increasing  (WHO  Press  release).  We  cannot  directly attribute  this  one  event  to  climate  change,  but  this  type  of occurrence  is  expected  to  happen  more  frequently.  The  heat wave that hit Europe in the summer of 2003 can be seen as one more warning of impacts from a warmer climate on populations and ecosystem. ♦
IPCC: Intergovernmental Panel on Climate Change; "Third Assessment Report"
"As the global temperatures continue to warm due to climate change, the number and intensity of extreme events might increase"
United Nations Environment Programme DEWA / GRID-Europe Tel: (4122) 917 82 94 Fax: (4122) 917 80 29 E-mail: earlywarning@grid.unep.ch Web:
The boundaries and names shown and the designations used on maps and graphics do not imply official endorsement or acceptance by the United Nations. Printed on recycled paper.

LangExtract: Processing, current=1,393 chars, processed=0 chars:  [00:14]

------- chunk id 25
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 25: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The extreme drought and heat wave that hit Europe in the summer of 2003 had enormous adverse  social,  economic  and  environmental  effects,  such  as  the  death  of  thousands  of vulnerable  elderly  people,  the  destruction  of  large  areas  of  forests  by  fire,  and  effects  on water  ecosystems  and  glaciers.  It  caused  power  cuts  and  transport  restrictions  and  a decreased agricultural production. The losses are estimated to exceed 13 billion euros.
The  severe  heat  wave  began  in  Europe  in  June  2003  and continued  through  July  until  mid-August,  raising  summer temperatures 20 to 30% higher than the seasonal average in Celsius degrees over a large portion of the continent, extend- ing  from  northern  Spain  to  the  Czech  Republic  and  from Germany to Italy (see map below).
Extreme  maximum  temperatures  of  35  to  40°C  were repeatedly recorded in July and to a larger extent in August in most of the southern, and central countries from Germany to Turkey. This extreme wheather was caused by an anti-cyclone firmly anchored over the western European land mass holding back  the  rain-bearing  depressions  that  usually  enter  the continent  from  the  Atlantic  ocean. This  situation  was  excep- tional  in  the  extended  length  of  time  (over  20  days)  during which it conveyed very hot dry air up from south of the Medi- terranean.

LangExtract: Processing, current=1,247 chars, processed=0 chars:  [00:14]

------- chunk id 26
Error when applying LangExtract on document UNEP 2013 - Impacts of summer 2003_cleaned, text block 26: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The all-time maximum temperature recorded in the United Kingdom  was  broken  on  10  August,  with  38.1°C;    tempera- tures in France soared to 40 °C and remained unusually high
for  two  weeks.  In  Switzerland,  June  was  the  hottest  month ever  recorded  in  250  years  of  archives  and  a  temperature record  of  41.5  °C  was  reached  on  August  11. With  tempera- tures  exceeding  the  average  by  +5.4°C  in  Geneva,  the prevailing conditions corresponded to a usual summer in Rio de Janeiro! July was characterised by dry conditions centred on France, Spain, Germany and Italy.
This  hot  and  dry  spell  extended  to  Central  Europe  in August.  The  low  precipitation  during  this  period  failed  to compensate for the accumulated evapotranspiration of almost 400 mm in the Mediterranean area, creating an accumulative water balance deficit of up to 380 mm in South Europe and of 200  mm  over  most  of  France,  Germany,  western  Czech Republic, Hungary and southern Romania.
This map, produced from both in situ and satellite information (NDC/NOAA), shows the extreme deviation from the average as recorded from June to August 2003. In some areas the difference exceeds 4°C. Climatological base period is 1988-2003.


 -------- Processing document [31]: Diakakis 2020 - A systematic assessment of the effects of extreme flash floods on transportation infrastructure and circulation: The example of the 2017 Mandra flood_cleaned.md --------

LangExtract: Processing, current=694 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,387 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,113 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=1,079 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=926 chars, processed=0 chars:  [00:05]

------- chunk id 4
Error when applying LangExtract on document Diakakis 2020 - A systematic assessment of the effects of extreme flash floods on transportation infrastructure and circulation: The example of the 2017 Mandra flood_cleaned, text block 4: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: InternationalJournalofDisasterRiskReduction47(2020)101542Availableonline26February20202212-4209/©2020ElsevierLtd.Allrightsreserved.M. Diakakis et al.
Fig. 1. Mandra map illustrating the catchments of the two main torrents (Soures and Agia Aikaterini) flowing towards the western part of Thriasion plain and the road network. The dashed red line shows the wider study area.
Fig. 2. Inundation boundary delineation based on UAV-captured imagery (a, b), along with total flood extent of November 15, 2017, across the study area [46].
InternationalJournalofDisasterRiskReduction47(2020)1015422M. Diakakis et al.
Fig.  3. Types  of  effects  of  flash  flooding  on  different  categories  of  transportation  infrastructure  with  respect  to  structural  or  non-structural  impacts  and discharge capacity.
Fig. 4. GPS locations of the truck fleet with respect to Zones (red for Zone 1, black for Zone 2 and green for Zone 3).

LangExtract: Processing, current=704 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,137 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,280 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,286 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,063 chars, processed=0 chars:  [00:29]

------- chunk id 9
Error when applying LangExtract on document Diakakis 2020 - A systematic assessment of the effects of extreme flash floods on transportation infrastructure and circulation: The example of the 2017 Mandra flood_cleaned, text block 9: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Fig.  6. Types  of  impacts  on  road  infrastructure  including  (a,b)  submersion  under  floodwaters,  (c)  inundation  of  interchanges,  (d)  scoured  asphalt  surface  and damaged installations, (e) scouring of road foundations, (f) scouring and collapse of sidewalk foundation and (g, h) collapse of road embankment.
a) quantifying  and  classifying  direct  effects  on  transportation  infra- structure, including the road network, bridges, ford crossings and the various installations associated with them
b)  quantifying key effects on network links and vehicle circulation in
In  this  section,  we  provide  details  about  the  study  area,  its  trans- portation  infrastructure,  along  with  a  description  of  the  extreme weather event.
InternationalJournalofDisasterRiskReduction47(2020)1015425M. Diakakis et al.
Fig. 7. Types of effects on bridges (a, b), ford crossings (c, d) and culverts (e, f) in terms of structural integrity (left column) and drainage capacity (right column). s/ d: Structural Damages, d/o/i: damages on installations.

LangExtract: Processing, current=1,066 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,159 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=862 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,056 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=1,046 chars, processed=0 chars:  [00:28]

------- chunk id 14
Error when applying LangExtract on document Diakakis 2020 - A systematic assessment of the effects of extreme flash floods on transportation infrastructure and circulation: The example of the 2017 Mandra flood_cleaned, text block 14: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: This section includes a description of the data sources and method- ology  that  were  utilized  for  this  study.  Due  to  this  event’s  profound impact on multiple sectors, heterogeneous data sets were collected and analysed in an attempt to accurately depict the sequence of impacts in various assets, ranging from the infrastructure and landscape to traffic congestion and delays. As the temporal duration of the extreme weather event  was  short,  the  collected  data  spanned  over  a  period  up  to  two
InternationalJournalofDisasterRiskReduction47(2020)1015427M. Diakakis et al.
Fig.  9. Types  of  impact  on  infrastructure  including  (a)  utilities,  (b)  non-functioning  traffic  lights,  (c,  d)  damaged  guardrails,  (e,  f)  collapsed  road  signs,  (g,  h) collapsed power poles and (h) damaged sidewalk surface.
weeks before and after its occurrence, to avoid seasonal biases in the analysis, given that the area is a commercial and tourism hub.
3.1. Data relating to transportation infrastructure and vehicle circulation

LangExtract: Processing, current=1,108 chars, processed=0 chars:  [00:11]

------- chunk id 15
Error when applying LangExtract on document Diakakis 2020 - A systematic assessment of the effects of extreme flash floods on transportation infrastructure and circulation: The example of the 2017 Mandra flood_cleaned, text block 15: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: (1)  Firstly, data on the impacts of the 2017 Mandra flash flood on transportation infrastructure were gathered through ground and aerial observations in the course of field surveys during and after the  flood.  Visual  material,  including  photos  and  videos,  was
InternationalJournalofDisasterRiskReduction47(2020)1015428M. Diakakis et al.
captured  from  the  ground  as  well  as  from  a  UAV  (Unmanned Aerial Vehicle). The UAV used in this study was a DJI Phantom 4 Pro, a quadcopter, shooting 4 K video at 60 frames per minute and 20megapixel photos. Twelve flights were realized between the 15th November 2017, and 20th February 2018.
All elements of transportation infrastructure (i.e. roads, bridges, ford crossings, culverts and underground passages) within the basin and the flooded area were mapped in a GIS environment. A handheld GPS device was  used  to  identify  their  exact  locations,  which  were  photographed after  the  flood  to  document  its  impacts.  Roads  were  represented  by polylines, whereas all other types of transportation infrastructure were represented by points.

LangExtract: Processing, current=1,210 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,276 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=985 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,103 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=376 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,223 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=568 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,124 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=905 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=952 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,255 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,147 chars, processed=0 chars:  [00:25]
LangExtract: Processing, current=1,038 chars, processed=0 chars:  [00:30]
LangExtract: Processing, current=1,235 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=750 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=699 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=690 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=820 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=650 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=810 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=971 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,229 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,236 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=1,365 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,231 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=1,117 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,301 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=470 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=676 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=645 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=605 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=583 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=576 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=521 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=610 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=509 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=681 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=638 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=489 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=614 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=429 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=632 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=732 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=672 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=485 chars, processed=0 chars:  [00:08]

 -------- Processing document [32]: Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned.md --------

Token indices sequence length is longer than the specified maximum sequence length for this model (4698 > 512). Running this sequence through the model will result in indexing errors
LangExtract: Processing, current=242 chars, processed=0 chars:  [00:26]
LangExtract: Processing, current=668 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=979 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=185 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=840 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=708 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=1,401 chars, processed=0 chars:  [00:11]

------- chunk id 6
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 6: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: In  this  report  EURELECTRIC  examines  four  different  events:  freezing  rain  covering everything up to 90 mm thickness in Canada in January 1998, a windstorm up to 220 km/h in France  in  December  1999,  a  heavy  snowstorm  in  Poland  in  November  2004,  and  the  storm Gudrun  with  150 km/h  wind  in  Sweden,  Latvia  et  al  in  January  2005.  While  the  regulatory and political reactions to these events differ from case to case, certain common patterns can be  recognised,  perhaps  the  most  conspicuous  one  being  the  demand  for  burying  more distribution  networks  underground.  Another  consequence  is  the  emergence  of  different functional  demands  for  distribution  networks  accompanied  by  compensation  schemes  for customers in some countries.
EURELECTRIC  has  analysed  the  political  and/or  regulatory  consequences  of  the  above events and formulated recommendations on them, partly for distribution companies and partly for decision-makers. The most important conclusion is that there is no uniform solution valid all over Europe. The structure of the grid, the national regulatory framework, the geographical and  geomorphological  situation  along  with  local  weather  conditions  influence  the  optimal solution  to  such  an  extent  that  it  is  doubtful  whether  it  makes  sense  to  look  for  a  single European answer to these issues.

LangExtract: Processing, current=1,269 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=709 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=298 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=275 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=273 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=271 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=290 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=274 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=283 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=145 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=148 chars, processed=0 chars:  [00:24]
LangExtract: Processing, current=263 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=286 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=143 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=146 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=293 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=275 chars, processed=0 chars:  [00:02]
LangExtract: Processing, current=273 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=273 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=290 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=274 chars, processed=0 chars:  [00:21]
LangExtract: Processing, current=253 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=153 chars, processed=0 chars:  [00:24]
LangExtract: Processing, current=288 chars, processed=0 chars:  [00:26]
LangExtract: Processing, current=288 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=353 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=281 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=378 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=145 chars, processed=0 chars:  [00:21]
LangExtract: Processing, current=157 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=280 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=378 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=282 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=252 chars, processed=0 chars:  [00:02]
LangExtract: Processing, current=145 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=226 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=271 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=279 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=278 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=287 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=355 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=250 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=266 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=280 chars, processed=0 chars:  [00:01]

------- chunk id 50
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 50: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Mutual assistance ......................................................................................................................49 3.7.2  Own emergency measures .........................................................................................................49 3.8

LangExtract: Processing, current=368 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=263 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=932 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,413 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,263 chars, processed=0 chars:  [00:14]

------- chunk id 55
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 55: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The reasons for power outages were almost solely the tremendous weight of ice; 70, 80 and in some  cases  90  mm  of  ice  on  lines  (3  tonnes  of  weight  on  every  100  metres  of  cable  – equivalent to two minivans). Ontario Hydro design for ice was 25 mm for 230 kV and 115 kV lines;  50  mm  for  500 kV  and  main  trunk  230 kV  –  equivalent  of  a  50-year  event  (the Canadian Standards Association called for resistance to 12.5 mm of ice).
In  the  area  of  Ontario  Hydro  the  following  damage  occurred:  130  transmission  pylons destroyed; 2·100 transformers destroyed or damaged; 10·750 pylons pulled down.
By  January  8,  more  than  30%  of  the  distribution  lines  had  been  destroyed,  together  with  a significant  portion  of  transmission  lines  and  thousands  of  trees.  Some  lines  were  lost  again after having been restored the previous day.
By Friday (January 9), electricity distribution had suffered the worst ever damage in Ontario Hydro’s history, with thousands of poles snapping; many lines and facilities, repaired the day before,  collapsing  again;  and  new  damage  occurring  at  thousands  of  locations.  34%  of distribution stations were without power; 31% of distribution lines were downed or damaged.

LangExtract: Processing, current=1,208 chars, processed=0 chars:  [00:11]

------- chunk id 56
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 56: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: A  specific  environmental  damage  was  caused  by  791  transformer  oil  spills  (due  to  pole- mounted transformers crashing to the ground).
In the Hydro-Québec area, 600 transmission towers collapsed; 300 to 400 more towers were damaged; 4·000 transformers were left inoperable; over 3·000 km high voltage transmission lines were affected; over 16·000 wooden transmission poles were destroyed or damaged; over 2·000 additional supporting structures were impacted; and more than 128 transmission lines were affected.
1.1.3  Impacts on customers and civil infrastructure
Of Ontario Hydro’s customers, well over 600·000 people were left without supply for varying lengths of time.
On  January  6,  about  30·000  residences  and  businesses  (~95·000  people)  experienced  power outages;  most  were  restored  within  24  hours.  The  following  day  50·000  residences  and businesses lost power. On January 9, supply to 149·062 customers (homes, farms, businesses,
etc.) got interrupted, leaving about 600·000 people (half the population) out of electricity in sub-zero conditions.
In the area of Hydro-Québec, 1.4 million customers (~3 million people) were left in the dark, many for close to a month.

LangExtract: Processing, current=1,134 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,112 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,447 chars, processed=0 chars:  [00:21]
LangExtract: Processing, current=1,137 chars, processed=0 chars:  [00:11]

------- chunk id 60
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 60: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: speeds  of  170 km/h  (47 m/s)  were  recorded  in  Brest.  The  storm  gained  speed  and  power  as soon  as  it  crossed  France.  At  Orly  airport,  173 km/h  (48 m/s)  was  recorded;  216 km/h (60 m/s)  on  the  top  of  the  Eiffel  Tower,  150 km/h  (42 m/s)  in  Paris  streets  and  180 km/h (50 m/s)  in  Vosges  Mountains.  There  are  no  data  in  Meteo  France  archives  of  such  fierce weather ever being recorded.
The second storm over the southern part A  second  storm  hit  the  southern  part  of  France  on  December  27  around  5  pm.  There,  wind speeds of 150 km/h (42 m/s) were recorded.
During  the  first  storm,  30  people  were  killed.  Damage  was  substantial:  several  houses  and other  buildings  were  partially  or  totally  destroyed.  Many  roads,  motorways,  railways  were blocked.  The  electrical  grid  also  suffered  severe  damages:  flooded  substations,  broken  or tangled wires, flattened poles, twisted pylons and so forth.
The  interconnection  grid  was  also  badly  affected:  lines  to  Germany  were  temporary  out  of order. 5·500 MV and LV poles needed to be replaced.

LangExtract: Processing, current=1,163 chars, processed=0 chars:  [00:11]

------- chunk id 61
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 61: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The  storm  also  caused  huge  damage  to  forests.  Some  of  them  were  completely  ruined. Thousands  of  trees  fell  on  MV  and  phone  overhead  lines.  Air  and  railways  traffic  was severely  disturbed.  But  most  damage  occurred  on  the  Electricité  de  France  (EdF)  grid.  For long,  EdF  had  been  prepared  for  white  frost  or  sticking  snow  on  lines,  but  such  a  severe situation  was  completely  unanticipated  by  the  company.  Nearly  3.4  million  household customers were left without electricity.
35 EHV lines (¼ of the total number) tripped. 180 HV lines were brought to the ground; more than  100  HV/MV  substations  were  out  of  order.  Innumerable  lengths  of  MV  and  LV  lines collapsed under falling trees.
1.2.3  Impact on customers and civil infrastructure
In  the  morning  of  December  27,  1·400·000  household  customers  were  without  electricity, mainly in the East, the North and in Paris suburbs. In these regions, the EdF grid was severely damaged: 120 EHV pylons and 67 HV lines.
After the second storm, the situation became worse.
Number of household customers without electricity on December 28:

LangExtract: Processing, current=1,289 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=689 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=1,339 chars, processed=0 chars:  [00:11]

------- chunk id 64
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 64: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Foreign companies sent 300 portable power generators across a broad power scale from some kW  to  1.25 MW,  which  EdF  bought  or  rented.  For  example,  25  units  of  850 MVA  were loaded in a plane from Zagreb in Croatia to Bordeaux. German company Ets Wilson sent 22 units  transported  by  German  civil  security.  London  Electricity  sent  5  powerful  units  to Périgueux  and  Limoges.  In  fact,  EdF  used  all  the  available  portable  power  generators  in Europe  and  beyond:  some  of  them  came  from  Canada.  Altogether,  1·600  units  were connected.
Operational equipment was also sent to France, e.g. Hungary provided two off-road cars and two lifting trucks (12 m and 20 m).
After  days  of  work,  recovery  teams  concentrated  on  regions  with  significant  access difficulties, such as forests, mountains or flooded zones.
Just  before  the  weekend  of  January  8/9,  97%  of  the  affected  household  customers  had recovered electricity. The last customer was reconnected on January 14.
Number of households without electricity (in thousands)
The following estimation of direct costs was made immediately after the storm:
- an  exceptional  so-called  “Millennium  Compensation”  (voluntary  by  EdF),  in  form  of  total  rebate  of  fixed
charges for 2000 for customers without supply on December 31

LangExtract: Processing, current=1,015 chars, processed=0 chars:  [00:04]

------- chunk id 65
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 65: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: On November 19, 3 of the 17 administrative regions in Poland, a part of Silesian and parts of the Malopolskie and Świętokrzyskie voivodships were affected by the snowstorm with heavy snowfall  and  extremely  strong  wind  blows.  The  weather  conditions  caused  some  serious disturbances in the operation of the national electricity system, both in the transmission grid (400  and  220 kV)  and  in  the  100 kV  sub-transmission  grid,  bringing  about  many  serious damages  both  to  national  and  international  transmission  lines.  As  a  result  of  these disturbances, the dispatching services of the TSO and DSOs had to conduct a series of actions in a very short time in order to minimise the danger, to eliminate the disturbances and also to restore  the  dispatch  of  electricity  to  customers.  It  can  be  roughly  estimated  that  the  storm caused  serious  problems  with  the  dispatch,  with  the  disconnection  of  some  1·000 MW electricity demand in the area covered by Katowice DSO.

LangExtract: Processing, current=1,011 chars, processed=0 chars:  [00:05]

------- chunk id 66
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 66: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: As  the  result  of  the  storm,  400 kV  and  220 kV cross-border  interconnectors with the Czech Republic  tripped.  In  Poland,  three  400 kV  lines,  six  220 kV  lines  and  one  autotransformer 400/220 kV 330 MVA also tripped, as well as four autotransformers 220/110 kV 160 MVA.
The  disconnection  of  the  400 kV  line  between  Dobrzyn  and  Albrechtice  (permanent  since November  16  due  to  line  damage  at  Albrechtice  station)  had  a  significant  influence  on  the sequence and evolution of this disturbance.
The  worst  hit  region  was  in  southern  Poland,  where  the  operation  of  110 kV  line  is coordinated by Katowice DSO. The main characteristics of the disturbances were:
(cid:137)  simultaneous  intensive  development  in  the  transmission  grid  at  400 kV,  220 kV  and
(cid:137)  simultaneous  intensive  development  in  the  grids  of  some  distribution  companies  at
(cid:137)  with widespread serious damage to equipment, disabling the restoration of electricity

LangExtract: Processing, current=1,289 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=987 chars, processed=0 chars:  [00:05]

------- chunk id 68
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 68: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: restoring supply to final customers disconnected for security reasons;
and to determine the date of their readiness to switch back on.
1.3.3  Damage caused. Impact on customers and civil infrastructure
Świętokszyskie voivodship Some  51  distribution  lines  and  434  transformer  stations  were  destroyed.  Around  13·000 customers suffered interruption of electricity supplies. The failures were repaired within two days.
Silesion voivodship 6·135 failures were recorded. As a consequence, 310·000 household and industrial customers, such  as  steel  mills,  water  conditioning  stations,  coal  mines  and  cooling  plants,  lost  supply. The  loss  of  supply  to  the  Water  Production  Plant  Goczałkowice  and  Zawada  for  24  hours caused  shortages  in  fresh  water  supply  to  the  Silesian  agglomeration.  Disturbances  in  the functioning of public transport also occurred. The traction grid of railway traffic was affected and 25 tramway traction lines were damaged.

LangExtract: Processing, current=1,379 chars, processed=0 chars:  [00:25]
LangExtract: Processing, current=1,434 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=1,002 chars, processed=0 chars:  [00:05]

------- chunk id 71
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 71: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The  location  of  disconnected  and  severely  damaged  lines  in  the  110 kV  grid  made  it necessary  to  make  a  temporary  set  of  distribution  line  arrangements  in  the  following  hours and  even  days.  At  that  time,  some  parts  of  the  grid  were  ‘emergency  supplied’,  with  lower reliability, which created a real risk of repeated disconnection of customers.
A  great  problem  was  the  relatively  large  number  of  stations  without  permanent  operation personnel and a lack of remote connector-control in many places.
The storm named Gudrun, which hit southern Sweden on January 8, had devastating effects. The entire infrastructure was hit. Roads and railways in large parts of southern Sweden were obstructed by large number of trees, e.g. there were no trains between Stockholm and Malmö for  12  days.  Electricity  outages  were  extensive  and  a  large  part  of  both  the  stationary  and mobile telephone traffic in the affected area were hit for a long period.

LangExtract: Processing, current=1,014 chars, processed=0 chars:  [00:05]

------- chunk id 72
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 72: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The storm gathered northwest of Ireland and followed a path usual for intense low-pressures passing over Sweden. It was not exceptional from a meteorological point of view, although it hit  a  larger  area  than  usual.  During  the  storm,  there  were  hurricane  winds  (more  than 117.7 km/h  or  32.7 m/s)  over  large  areas  and  the  most  powerful  gusts  were  151 km/h (42 m/s). That had happened several times before during the last 100 years, but had never led to such damage. 70 million cubic meter wood (150 million trees) was cut, corresponding to almost  one  normal  year  of  woodcutting  for  the  whole  of  Sweden  (the  second  most  severe storm in 1969 cut 25 million m3 of wood).
The  severe  consequences  can  be  explained  by  a  number  of  contributing  circumstances. Among other things, there was no ground frost at the time and the planted spruce trees may not be biotopically suitable for the area. It was primarily in spruce woods that electric lines were cut, causing outages.

LangExtract: Processing, current=1,308 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=1,012 chars, processed=0 chars:  [00:05]

------- chunk id 74
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 74: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Length of distribution networks in the affected area and percentage of cables, insulated and uninsulated overhead lines for the distribution network companies (from the investigation by Statens Energimyndighet)
1.4.3  Impacts on customers and civil infrastructure
Immediately  after  the  storm,  there  were  663·000  network  customers  without  electricity supply.  Of  these,  295·000  belonged  to  Sydkraft’s  network.  There  were  some  other  network companies  with  many  affected  customers:  Vattenfall  with  260·000  customers  facing  power outages, and Fortum with 50·000. In relative terms, the local distribution company KREAB Öst was hit the hardest, with 100% of its 7·200 customers without electricity supply, mainly due to problems at sub-transmission levels (Sydkraft’s 50kV line feeding KREAB was out of service). As mentioned in the previous chapter, Sydkraft’s customers had to wait the longest time  before  the  electricity  supply  was  resumed,  due  to  extensive  damage  to  the

LangExtract: Processing, current=1,122 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=1,190 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=527 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=835 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,221 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=1,321 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=834 chars, processed=0 chars:  [00:05]

------- chunk id 81
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 81: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The overall cost to the network operators was calculated at about 2·350 MSEK (€257 M). Of this  sum,  about  ⅔  (1·540  MSEK  or  €168  M)  was  spent  on  clearance,  reparation  and  re- building the network. Compensation to customers, paid voluntarily based on the companies’ own rules, amounted to 616 MSEK (€67 M) or a quarter.
Cost  per  customer,  worked  out  on  average  at  3·560  SEK/customer  (€280/customer).  The various  companies  reported  costs  ranging  from  about  300  SEK/customer  (€33/customer)  to 11·900 SEK/customer (€1·300/customer).
The storm, which hit western, southern and northern Latvia on January 8 and 9, was the most severe storm in Latvia during the last 35-year period. The previous similar storm was in 1969. The average wind was 33-35 m/s (118-126 km/h) with wind gusts of 40 m/s (144 km/h).

LangExtract: Processing, current=1,314 chars, processed=0 chars:  [00:11]

------- chunk id 82
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 82: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The entire infrastructure was hit. Roads and railways in large parts of Latvia were obstructed by large numbers of trees. In the inland, as winds of only 20-25 m/s (72-90 km/h) may be able to bring down trees, the damage in the woods was extensive in western, southern and northern Latvia.  In  many  cases,  trees  fell  on  wires  and  poles  of  the  distribution  and  transmission network, broke poles and disrupted wires.
Around 2·000 km of network lines were damaged in the transmission network and 54·000 km (64%)  in  the  distribution  network.  Approximately  400·000  electricity  customers  were  left without  electricity  in  the  immediate  aftermath  of  the  storm  –  some  40%  of  all  Latvian customers.  The  distribution  network  was  badly  affected,  which  contributed  to  the  large number of customers involved. However, the biggest cities – Riga, Liepaja, Daugavpils had only  small  problems  with  electricity,  because  the  distribution  network  consists  of underground cables.
Damage to the transmission system caused a 90-hour long emergency situation. Around 1·200 trees  fell  on  transmission  lines;  3  transmission  line  towers  were  destroyed,  and  34 transmission  line  towers  damaged;  conductors  were  damaged  at  60  locations  in  the transmission network.

LangExtract: Processing, current=1,254 chars, processed=0 chars:  [00:11]

------- chunk id 83
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 83: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Damage to the distribution system caused a 23-day long emergency situation. Around 53·000 trees  fell  on  distribution  lines.  There  were  11·000  broken  poles  and  38·500  instances  of damaged conductors; 2·000 kg of wire (about 15 km) was stolen.
1.5.3  Impacts on customers and civil infrastructure
Immediately  after  the  storm,  on  January  9,  372·000  Latvenergo  network  customers  were without  electricity  supply,  and  a  further  20·000  customers  of  other  companies.  224·000 customers had their electricity supply restored within 24 hours; 96·400 customers had to wait between  one  and  three  days.  22·000  customers  got  their  electricity  back  within  4  to  7  days after the storm. And finally, more than 1·000 customers got their electricity back only 10 to 26 days after the storm.
The  damage  was  so  extensive  that,  despite  the  tremendous  efforts  made  by  the  electricity companies, many customers had to live without electricity for several weeks. The last house with permanent residents had their electricity restored on February 1. After that, only 17 small summer  cottages,  without  people  living  in  them  in  wintertime,  remained  disconnected,  and they were also reconnected during February.

LangExtract: Processing, current=1,089 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,131 chars, processed=0 chars:  [00:17]

------- chunk id 85
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 85: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: (cid:137)  2·847 replaced 20 kV line poles; (cid:137)  damaged wires in 11·292 places of 20 kV lines; (cid:137)  8·207 replaced low voltage line poles; (cid:137)  damaged wires in 27·124 places of low voltage lines; (cid:137)  around 1·000 km had to be completely rebuilt; (cid:137) (cid:137)  broken trees cleared from overhead network protective zones – 10·345 km.
At state level, action of units in crisis situation is regulated by:
(cid:137)  energy law; (cid:137) (cid:137)  different pieces of secondary legislation.
A  local  crisis  control  centre  is  run  by  the  Ministry  of  Economics.  A  crisis  control  centre operates  within  Latvenergo,  and  there  were  no  problems  with  coordination  of  information. There  was  generally  good  cooperation  with  State  Fire  and  Rescue  Service,  National  army, local municipalities, and energy contractors.
First, Latvenergo focused on restoring supply to priority customers (hospitals, schools, etc.), which slowed down the restoration of energy supply to other customers. Involvement of non- Latvenergo personnel in the restoration helped improve the situation.

LangExtract: Processing, current=1,264 chars, processed=0 chars:  [00:11]

------- chunk id 86
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 86: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Network  operators  do  not  have  agreements  with  external  contractors  in  case  of  emergency. During the storm, network operators reported that it had been a great problem the first day.
In  Latvia,  cooperation  between  network  operators  is  carried  out  under  the  aegis  of Latvenergo.  According  to  the  involved  companies,  it  worked  very  well  during  the  storm according.
Cooperation with municipalities and county administrative boards seems to have worked well in  most  cases.  State  Fire  and  Rescue  Service,  National  army  and  local  forestry  helped  with forest  clearance  work.  Other  local  organisations  and  private  persons  assisted  in  locating faults.
Workforce contribution by different organisations:
1.5.6  Estimated costs (repair, compensation, investment)
The overall cost to the network operators was calculated at about 3.3 MLs (€4.7 M). Of this sum,  3.2  MLs  (€4.6  M)  or  ~97%  was  spent  on  clearance,  repair  and  re-building  the distribution network. The rest was paid to mobile generators not owned by Latvenergo.
No  compensation  was  paid  to  customers,  as  corresponding  Latvian  law  reads,  “very  severe weather events can be a reason for not giving any compensation to the customer”.

LangExtract: Processing, current=1,617 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,466 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,481 chars, processed=0 chars:  [00:23]
LangExtract: Processing, current=1,384 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,216 chars, processed=0 chars:  [00:11]

------- chunk id 91
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 91: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The  Commission  suggested  that  the  government  set  objectives  in  order  to  strengthen electricity-supply  security.  Hydro-Québec  was  urged  to  use  risk  analysis  techniques  as standard practices.
2.1.4  Demands and incentives for investments to enhance security of supply
The  Commission  emphasised  that  the  only  solution  was  to  find  a  compromise  between  the level of electricity supply security sought by citizens and the price they were willing to pay for it.
2.1.5  Political tolerance of long and/or widespread outages
The Commission suggested adapting rather than redefining energy policy, and emphasised:
(cid:137)  service  quality  and  supply  security  are  one  and  the  same  thing,  and  part  of  a
comprehensive vision ranging from producer to consumer; the  society  must  keep  up  with  energy  efficiency  efforts  thus  creating  an  “energy surplus”;
(cid:137)  with  ongoing  liberalisation,  the  critical  nature  of  energy  services  must  be  carefully
Certain issues were left unclear, e.g. the government required Hydro-Québec to supply mobile generators to farmers, although this task was not among the company’s responsibilities. Yet, the task was completed.

LangExtract: Processing, current=971 chars, processed=0 chars:  [00:05]

------- chunk id 92
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 92: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: At the end of December, 1999 France was hit successively by 2 huge storms, which crossed the northern, then the southern part of the country. 3·445·000 household customers were left without electricity, some of them until January 14.
2.2.1  New requirements on design, need for undergrounding
EdF has voluntarily decided to improve grid sturdiness according to a 4-step programme:
a.  restoring electricity supply as soon as possible b.  securing the grid
Until  May  2000,  EdF  teams  secured  all  temporary  installations  from  public  access.  2·200 operators worked and the corresponding cost was 46 M€ (in 2005 euro).
From March 2000 to December 2001, the work was carried out at a total of 82·000 building sites  over  the  country,  9·100 km  of  new  lines  (5·280 km  for  MV  grid,  undergrounding  of 4·130 km; and 3·820 km in LV grid, undergrounding of 370 km). 1·350 operators worked on the project with a the corresponding cost of €494 M (at 2005 value).

LangExtract: Processing, current=961 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=1,172 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,136 chars, processed=0 chars:  [00:10]

------- chunk id 95
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 95: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Since  the  events  in  1999,  the  French  legislation  has  been  changed  and  now  prescribes obligations for TSOs and DSOs to provide compensation in case of outages lasting more than 6  hours.  The  current  grid  access  contracts  already  include  such  responsibility  conditions. Customers are compensated to the extent of:
(cid:137)  2% of the annual fixed part of the tariff for a duration of more than 6 hours and less
(cid:137)  4% of the annual fixed part of the tariff for a duration of more than 12 hours and less
Compensation  is  nevertheless  limited  to  the  annual  fixed  part  of  the  tariff  and  is  paid irrespective  of  the  origin  of  the  outage  (even  under  force  majeure  conditions).  This compensation cannot be deducted from possible compensation for actual damages.
2.2.4  Demands and incentives for investments to enhance security of supply
In  France,  a  regulation  (Arrêté  Technique)  defines  the  technical  conditions  that  electricity distribution  must  meet.  The  latest  version  dates  from  2001  and  takes  into  account  the technical conclusions drawn from the 1999 storms.

LangExtract: Processing, current=1,234 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,290 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,213 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=877 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=625 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,346 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,355 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,231 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,379 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,019 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=626 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,050 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,239 chars, processed=0 chars:  [00:24]
LangExtract: Processing, current=1,400 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,526 chars, processed=0 chars:  [00:09]

------- chunk id 110
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 110: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The  table  below  summarises  the  main  regulatory  consequences  along  with  voluntary measures taken by the industry itself.
Note that only those measures are indicated that were introduced after the storms described in this  report;  e.g.  voluntary  compensation  mechanisms  that  were  in  place  in  Sweden  already before the Gudrun storm are not included in the table.
The  last  category  in  the  table  (“allowances”)  contains  measures  that  have  not  placed obligations  on  distribution  companies,  but  for  example  facilitated  a  simpler  authorisation procedure for undergrounding lines.
This  chapter  gives  some  examples  of  the  kind  of  conclusions  that  can  be  drawn  from  the above  events.  The  list  of  conclusions  is  not exhaustive, partly because EURELECTRIC did not have the intention of conducting a detailed, in-depth investigation of the events, and partly because distribution is a local issue. Huge differences in national weather conditions, in the national  regulation,  the  operating  environment  for  distribution  companies  make  it  not  only inappropriate  to  formulate  uniform  recommendations,  but  even  impossible  to  draw  uniform conclusions.
EURELECTRIC believes that the key conclusion is that a proper and fair investigation must be  performed  at  technical  level  by  experts  after  power  outages.  Conclusions  drawn  and requirements  re-formulated  must  be  based  on  these  expert  reports,  in  order  to  avoid  any premature reactions.

LangExtract: Processing, current=1,478 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,164 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=909 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=690 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,268 chars, processed=0 chars:  [00:11]

------- chunk id 115
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 115: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: When  planning  for  investments  in  the  network,  a  life  cycle  cost  approach  can  be  used  to assess  the  most  cost  efficient  solution.  The  investment  cost  of  various  techniques  differs substantially, but so also do operation and maintenance costs. Taking all cash flows within the investment the  most  cost-effective  solutions. Unavoidably, there are many uncertainties due to long investment cycles (25 to 40 years). A crucial  uncertainty  is  the  stability  of  the  regulatory  framework,  which  is  vital  to  create  a climate  attractive  to  investments.  When  assessing  whether  maintenance  is  the  most  cost- effective for the line, renovation of the (parts of the) line may prove to be a better solution.
For  the  new  solutions,  equipment  should  require  a  minimum  of  maintenance  so  as  to  meet both  the  customers’  demands  for  high  availability  (i.e.  no  interruptions)  and  society’s demands  for  efficiency  in  the  distribution  business  (i.e.  low  tariffs).  In  rural  areas,  it  is  not possible  to  build  a  distribution  system  with  100%  redundancy,  so  the  maintenance  of
equipment should be done in a simple and quick manner or with live line techniques so as to minimise interruptions.

LangExtract: Processing, current=1,506 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,291 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,131 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=415 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=966 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,282 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,416 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=804 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,525 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=1,325 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,021 chars, processed=0 chars:  [00:00]ERROR:absl:Extraction text must be a string, integer, or float. Found: <class 'NoneType'>
LangExtract: Processing, current=1,021 chars, processed=0 chars:  [00:03]

------- chunk id 126
Error when applying LangExtract on document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned, text block 126: Extraction text must be a string, integer, or float.
Probably one of the few-shot examples does not match.

LangExtract: Processing, current=1,472 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,570 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=1,338 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,030 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,304 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,497 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,353 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,455 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,102 chars, processed=0 chars:  [00:09]

 -------- Processing document [33]: Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned.md --------

Token indices sequence length is longer than the specified maximum sequence length for this model (552 > 512). Running this sequence through the model will result in indexing errors
LangExtract: Processing, current=797 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,419 chars, processed=0 chars:  [00:27]
LangExtract: Processing, current=619 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=828 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=984 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,163 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=771 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,326 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=943 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,205 chars, processed=0 chars:  [00:26]
LangExtract: Processing, current=325 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,422 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,502 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=394 chars, processed=0 chars:  [00:20]
LangExtract: Processing, current=1,359 chars, processed=0 chars:  [00:18]
LangExtract: Processing, current=1,104 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=269 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,145 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=1,241 chars, processed=0 chars:  [00:25]
LangExtract: Processing, current=1,274 chars, processed=0 chars:  [00:36]
LangExtract: Processing, current=1,326 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=1,078 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,092 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=989 chars, processed=0 chars:  [00:04]

------- chunk id 23
Error when applying LangExtract on document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned, text block 23: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Many  people  perished  in  cars,  many  cars  (> 120,000)  were  damaged,  also  creating waste disposal problems [50, 51]. There are many underground car parks, typical of con- structing  residential  areas  in  Spain,  which  were  flooded.  The  damaged  cars  were  then piled up in the collection centres and checked by volunteers and the Emergency Military Unit (UME is the acronym in Spanish), which was responsible, alongside a civil defence unit, to ensure that no bodies were left in the cars. Damaged cars are a visible sign of flood destruction due to their deformation and muddy hulls (Fig. 4).
The main problem is that the insurance company requires detailed documentation of the car damage. Some had parked their cars on the street during the flood, but after the
Fig. 4  Car wrecks with signs for being searched for dead bodies (R = Reviewed, X + 2, checked two times) (photos: Fekete, 8 Jan. 2025)
Fekete et al. Discover Sustainability           (2025) 6:586 Page 9 of 31

LangExtract: Processing, current=1,098 chars, processed=0 chars:  [02:00]

------- chunk id 24
Error when applying LangExtract on document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned, text block 24: Ollama API error: Ollama Model timed out (timeout=120, num_threads=None)
Probably Timeout threshold for calling Ollama API needs to be increased

LangExtract: Processing, current=1,067 chars, processed=0 chars:  [00:11]

------- chunk id 25
Error when applying LangExtract on document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned, text block 25: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: The  recovery  plan  of  the  provincial  government  of  Valencia  lists  estimated  bud- gets needed for the rehabilitation of infrastructure and living conditions [53]. Tourism is  an  essential  economic  factor  in  the  region,  and  the  Valencia  Region  Tourist  Board announced  two  months  after  the  flooding  and  before  Christmas  that  tourists  are  wel- come  and  normality  has  returned  to  the  region  [54].  This  fact  certainly  applies  to  the unaffected  areas  and  the  entire  city  centre  of  Valencia.  Hotels,  restaurants,  and  other
Fekete et al. Discover Sustainability           (2025) 6:586
services  are  still  being  operated.  Many  people  in  the  region  report  that  the  floods affected  colleagues  or  relatives.  Between  10–20%  of  the  affected  companies  were  sus- pected to need to close after the damage [55], and a similar number of people from the business  community  were  said  to  be  affected.  On-site  conversations  with  the  people revealed that the floods affected up to 40% of their staff.

LangExtract: Processing, current=328 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,023 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=397 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,293 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=389 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,232 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=930 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=441 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=972 chars, processed=0 chars:  [00:04]

------- chunk id 34
Error when applying LangExtract on document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned, text block 34: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Special  mention  merits  the  Albufera  Natural  Park,  an  ecosystem  protected  by  the European  Union  with  an  area  of  approximately  211  Km2,  of  which  some  150  Km2  are dedicated to rice cultivation, which is crucial for the region’s biodiversity and has been seriously  affected  by  the  floods.  The  arrival  DW  in  the  northern  zone  was  estimated at  85.000  m3,  of  which  1,500  m3  from  irrigation  ditches  had  already  been  removed  in December,  together  with  some  2.5  tons  of  plastics.  In  December,  PreZero  began  the removal of hazardous waste, removing an accumulated 18 m3. Another critical issue is that after floods, the volume of sediment at the bottom of the lake is estimated at 700,000 tons, which means about 46,000 truckloads of debris. Floods caused in one day the usual 30-year volume of sedimentation, which raises the debate as to whether it is necessary to drain the lake bottom, which has been increased by 6

LangExtract: Processing, current=718 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,277 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,309 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=560 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=903 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=426 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=1,085 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=143 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=1,332 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,082 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,418 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=1,029 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,172 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,024 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=732 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=1,112 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=855 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,352 chars, processed=0 chars:  [00:16]
LangExtract: Processing, current=1,033 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,136 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=862 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,131 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,169 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=922 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,298 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=277 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,403 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,066 chars, processed=0 chars:  [00:04]

------- chunk id 62
Error when applying LangExtract on document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned, text block 62: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Germany.  These  are  employed  by local authorities to promote the introduction of climate change adaptation techniques in the community and work together with various departments in the city, as well as with companies and people in the communities. However, training such individual multipli- ers is not enough, as we know from the German study [85]. Such multipliers are ‘lone wolves’ who often lack support for their newly created department and positions from the more established and recognised departments. It is therefore vital not only to intro- duce their positions but also to create an environment and ecosystem of support within
Fekete et al. Discover Sustainability           (2025) 6:586 Page 20 of 31
the municipality and a connection with the local waste management companies, such as disaster and emergency management, as in the project case in Germany.
To  create  a  plan  for  multi-stakeholder,  multi-level,  and  multi-sector  cooperation,  it is first important to develop schemes that help to understand the interrelationships in governance.

LangExtract: Processing, current=489 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,094 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=694 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=912 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=861 chars, processed=0 chars:  [00:20]
LangExtract: Processing, current=814 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,377 chars, processed=0 chars:  [00:11]

------- chunk id 69
Error when applying LangExtract on document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned, text block 69: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: problem.  People  are  unaware  of  the  potential  risk  of  flooding,  and  in  many  countries, these  riverbeds  are  even  used  for  daily  transport.  An  additional  problem  is  that  it  is  a low-lying  area,  and  people  in  such  wadis  or  irrigation  canals  are  unaware  of  flooding because it often does not even rain in their area when the flood comes. The flood waters come  from  nearby  or  distant  mountainous  regions  at  high  speed  without  any  natural warning  signs.  For  Valencia,  this  could  mean  that  urban  planning  needs  to  extend  a protection system, such as the Turia river channel, and create a costly measure for the southern  and  other  growing  areas.  It  is  crucial  to  consider  the  areas  not  affected  last time, as they may be more surprised next time. The "next valley problem" is similar to the "not in my backyard" problem [92] and applies to many areas around the world that have been affected before.
On the other hand, other urban planning measures, such as permits for underground car  parks,  must  also  be  considered  overall.  The  positive  examples  of  supermarkets  or furniture shops that sell their goods on mezzanine floors and have ground-level parking spaces could be an option. However, this must be accompanied by a good and reliable warning system so people do not get stuck in their cars.

LangExtract: Processing, current=1,317 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,336 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,281 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=398 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=972 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,360 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=1,157 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=1,227 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=607 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,189 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,068 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,187 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=769 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,134 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,318 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=676 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=944 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,074 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=589 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,454 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=375 chars, processed=0 chars:  [00:01]

------- chunk id 90
Error when applying LangExtract on document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned, text block 90: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: science can help to distribute such lessons learned internationally, and also find links between sectors  and  actors  that  often  do  not  have  an  opportunity  or  occasion.  Authorities  and companies usually must talk to other persons or institutions outside the usual commu- nication chains. Impact chains are, therefore, also highly connected to communication chains.

LangExtract: Processing, current=1,401 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=358 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=893 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=1,154 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=347 chars, processed=0 chars:  [00:03]

 -------- Processing document [34]: Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts_cleaned.md --------

Token indices sequence length is longer than the specified maximum sequence length for this model (8194 > 512). Running this sequence through the model will result in indexing errors
LangExtract: Processing, current=985 chars, processed=0 chars:  [00:05]

------- chunk id 0
Error when applying LangExtract on document Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts_cleaned, text block 0: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Weather – August 2004, Vol. 59, No. 8209Andreas H. FinkTim BrücherAndreas KrügerGregor C. LeckebuschJoaquim G. PintoUwe UlbrichInstitute of Geophysics and Meteorology,University of Cologne, GermanyEurope was affected by a series of strong,persistent heatwaves during the summer of2003. The largest positive anomalies inmonthly mean temperatures were observedin June and August in a region stretchingfrom south-west Germany acrossSwitzerland to the eastern and southernparts of France (Figs. 1(a) and (e)). In easternFrance, the northern parts of Switzerlandand the German Alpine foreland, theJune–August 2003 period was more than5degC warmer than the 1961–90 average,making 2003 the warmest summer in theabove-mentioned area since at least 1864(Schär et al.2004; Bader and Zbinden 2003),but more likely since instrumental recordsbegan in the mid-to-late eighteenth century(Fricke 2003; Schönwiese et al.2004). As aresult, the impacts and the media interestwere extraordinary. The World

LangExtract: Processing, current=984 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,114 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=920 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,004 chars, processed=0 chars:  [00:05]

------- chunk id 4
Error when applying LangExtract on document Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts_cleaned, text block 4: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: June, when thewarm anomalies lasted throughout theentire month, August was characterised byan extreme heatwave from 1 to 13 Augustduring which many all-time temperaturerecords tumbled in much of Europe. Forexample, the old Swiss temperature recordof 39.0°C observed on 2 July 1952 in Baselwas greatly exceeded by the 41.5°C readingin Grono (Mesolcina valley in the CantonGrisons, south Alps) on 11 August 2003(Bader and Zgraggen 2003). In Germany,daily maximum temperatures exceeding40°C were recorded three times: on 9August 40.2°C was measured at Karlsruheand on the 13th again at Freiburg andKarlsruhe, exactly equalling the previousrecord observed on 27 July 1983 atGärmersdorf (Bavaria). In central and easternFrance, the daily maximum temperaturessoared above 40°C at individual synopticweather stations every day between 5 and13 August, culminating in 41.1°C at Auxerre(Burgundy) on 6 August and 40.9°C atColmar (Alsace, in the upper Rhine valley) on13 August. In addition, the night-time mini-mum

LangExtract: Processing, current=1,019 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=939 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=985 chars, processed=0 chars:  [00:05]

------- chunk id 7
Error when applying LangExtract on document Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts_cleaned, text block 7: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: respect to the meanaccumulation in the period 1879–2002 forHohenpeissenberg. In the Bavarian AlpineWeather – August 2004, Vol. 59, No. 8210European heatwave – impactsFig. 2(a) Mean June–August temperature (curve, 1755–2003) and total sunshine duration (bars,1886–2003) at the Swiss station Basel-Binnigen (altitude 316m). (b) Annual development of accumulateddaily precipitation anomalies (reference period: 1879–2002) of the six (seven) wettest (driest) years atHohenpeissenberg (altitude 986 m) during the period 1879–2003 (i.e.the reference period plus the anom-alous year of 2003). The station is located on a low mountain top in the Bavarian foreland of the Alps. ((b) iscourtesy of Wolfgang Fricke, German Weather Service, Meteorological Observatory Hohenpeissenberg.)temperature (°C)Weather – August 2004, Vol. 59, No. 8211foreland, the drier than normal conditionsdeveloped in late March, and by mid-Junethe largest precipitation deficit on recordwas observed for this time of

LangExtract: Processing, current=1,009 chars, processed=0 chars:  [00:06]

------- chunk id 8
Error when applying LangExtract on document Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts_cleaned, text block 8: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: year. Aftersome rainfall in the second half of July, theaccumulated precipitation deficit againdropped to record low values in late August.Note that due to an anomalously wetOctober, 2003 only ended as the third drieston record. Figure 3 conveys an idea aboutthe impact of the dryness on the river flowof a major central European river, the Rhine.It shows the minimum (1930–2002) dailydischarge at Cologne, together with the cor-responding hydrographs for 2003 and twoother exceptionally dry years, 1947 and1976 (cf. Fig. 2 (b)). The latter two years alsobelong to the six driest on record atHohenpeissenberg (Fig. 2(b)). In the Rhinecatchment the period with below averageaccumulated areal rainfall had commencedalready in February (Belz et al. 2004). Thesame authors note that February, March,and August were the driest months inGermany’s river catchments in 2003. InAugust, the lowest discharges at Colognesince 1930 were observed. However, theminimum September 2003 value of640m3s–1was considerably higher

LangExtract: Processing, current=990 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=944 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=939 chars, processed=0 chars:  [00:05]

------- chunk id 11
Error when applying LangExtract on document Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts_cleaned, text block 11: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: 9.3% (compared to the summerhalf-year average of 1.7%), 20.2% (7.2%),and 10.9% (4.2%), respectively. GWL5 pre-vailed in the first half of June 2003. To givethe reader an idea of the associated surfaceand mid-tropospheric conditions, the500mbar geopotential height and surfacepressure distributions, computed fromaveraging the National Centers for En-vironmental Prediction four-times-daily re-analysis (Kalnay et al.1996) between 5 and11 June, are shown in Fig. 4(a).Corresponding to the definition of GWL5,central Europe was dominated by an anti-cyclonic south-westerly flow regime withweak surface pressure gradients and a mid-level ridge aloft. Daily 5-day backwardtrajectories starting at 850mbar over south-western Germany (not shown) indicate thatthis flow pattern was often associated withwarm air advection from the westernMediterranean ahead of the trough north-west of the British Isles (Fig. 4 (a)). Between22 July and 4 August,

LangExtract: Processing, current=972 chars, processed=0 chars:  [00:05]

------- chunk id 12
Error when applying LangExtract on document Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts_cleaned, text block 12: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: i.e.just before and atthe beginning of the major heatwave, GWL10 has been diagnosed over central Europe(Fig. 4 (b)). It was replaced by GWL14, lastingfrom 5 until 13 August (Fig. 4 (c)).Comparison of Figs. 4(b) and (c) clearlyreveals that geopotential heights rose overcentral Europe during the latter period, andthat the build-up of a surface high pressurezone stretching from the Azores to theNorwegian Sea completely inhibited theintrusion of low-level cooler air from theAtlantic and North Sea into central Europe.The peak of the summer heat occurred atthe end of the above-noted period duringwhich GWL14 prevailed.The question arises as to what extent thepredominance of the anticyclonic GWLs 5,10, and 14 can account for the 2003 summerheat. Figure 5 shows the 1890–2002 fre-quency distribution of mean daily tempera-tures at Karlsruhe (Germany) observedduring days assigned to these GWLs for June,July and August. The colour-coded verticallines in Fig. 5 denote the

LangExtract: Processing, current=1,024 chars, processed=0 chars:  [00:05]

------- chunk id 13
Error when applying LangExtract on document Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts_cleaned, text block 13: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: correspondingvalues observed during 2003. Whilst in Juneand July the 2003 mean daily temperaturesare more or less within the hithertoobserved range (Figs. 5(a) and (b)), theAugust 2003 result is striking; almost alldaily mean temperatures occurring duringGWL14 (5–13 August) exceeded the maxi-mum value observed since 1890 (Fig. 5(c)).Moreover, analyses of the Karlsruhe temper-ature data (not shown) revealed that there isno general build-up of heat during a succes-sion of days with the same anticyclonicweather type. Thus, other factors that will bediscussed in some more detail in theconcluding section must have played thedecisive role for the extreme heat in August.One reason discussed below, the desicca-tion of soils, is related to the dryness of thepreceding spring season and the summeritself. Figure 6 illustrates the mean (1946–2002) and actual daily accumulated precipi-tation at Karlsruhe from January toDecember 2003. A simplified GWLstatisticfor 2003 that distinguishes betweencyclonic weather types (blue),

LangExtract: Processing, current=1,003 chars, processed=0 chars:  [00:05]

------- chunk id 14
Error when applying LangExtract on document Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts_cleaned, text block 14: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: GWLs 5, 10,and 14 and all other anticyclonic weathertypes (light and dark orange) is also given inFig. 6 by the colouring between the 2003European heatwave – impactsFig. 3Annual distribution of minimum daily discharge of the River Rhine at the water-level gauge at Colognein a mean year (averaging period 1930–2002) and in the three extremely dry years of 1947, 1976, and 2003accumulated precipitation curve and theabscissa. The prevalence of anticyclonicweather types in 2003, especially in the firstthree quarters of the year is obvious. Alsoevident is the frequent occurrence of GWLs5, 10, and 14 between June and September.The light and dark orange curves in thelower part of Fig. 6 show the developmentof the anomalous occurrence of GWLs 5, 10,and 14 and all other anticyclonic weathertypes in the course of 2003, respectively. Theformer anomaly rose to about 150% inAugust and September with respect to the1946–2002 mean, i.e.days with GWLs 5, 10,and 14 have been observed by this time ofthe year

LangExtract: Processing, current=1,044 chars, processed=0 chars:  [00:34]
LangExtract: Processing, current=878 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=949 chars, processed=0 chars:  [00:05]

------- chunk id 17
Error when applying LangExtract on document Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts_cleaned, text block 17: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: (b)GWL10, 22 July–4 August, and (c) GWL14, 5–13 August 2003Fig. 5Frequency of occurrence per 1 degC interval of daily mean June (a), July (b), andAugust (c) temperatures at the German station Karlsruhe (altitude 145 m) between 1890and 2002. Only data from days which were assigned to anticyclonic GWLs 5, 10, and 14(see text), respectively, are used. The vertical lines are drawn at the decimal values of themean daily temperatures in 2003 for days that were assigned to GWL5 (blue), 10 (red),and 14 (green) in 2003.Weather – August 2004, Vol. 59, No. 8213Impacts The drought and heatwaves in summer2003 affected not only central Europe, butalso the west central Mediterranean area (cf.Fig. 1). In this context, Grazzini and Viterbo(2003) note record-breaking high sea sur-face temperatures in this area peakingabove 30°C. While small-scale forest fireswere observed all over central Europe andthe western Mediterranean, the forest andbush fires on

LangExtract: Processing, current=1,146 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=1,054 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,050 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=916 chars, processed=0 chars:  [00:05]

------- chunk id 21
Error when applying LangExtract on document Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts_cleaned, text block 21: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: GWLs, except anticyclonic GWLs 5,10, and 14 (light orange). Lower curves: anomalous frequencies of occurrence of anticyclonic GWLs 5, 10, and14 (light orange) and all other anticyclonic GWLs (dark orange) accumulated since 1 January 2003.Fig. 7 (a) Annual accumulated glacier tongue variations for the Alpine glaciers Grosser Aletsch (Bernese Alps, since 1881), Morteratsch (Bernina, since 1881), Trient(Mont Blanc, since 1880), and des Bossons (Mont Blanc, since 1871) until 2003. (b) Annual accumulated net specific mass balance of Vernagtferner (Ötztaler Alps) andGriesgletscher (Lepontine Alps), starting in the glaciological years 1964/65 and 1961/62, respectively, and ending in 2002/03.*Snow that has survived at least one summermelting season and has become more compactthan freshly fallen snow.Alps since 1961/62. The mass losses of 2.13and 2.63m w.e., respectively, in 2002/03stand out in the time-series.

LangExtract: Processing, current=953 chars, processed=0 chars:  [00:05]

------- chunk id 22
Error when applying LangExtract on document Fink 2004 - The 2003 European summer heatwaves and drought - synoptic diagnosis and impacts_cleaned, text block 22: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Grazzini et al.(2003) state that the volume of Alpine gla-ciers reduced by about 5–10% in 2003 alone.The extreme glacier melt in the Alps pre-vented the river flows of the Danube andRhine from attaining even lower values.The mass balance of the Vernagtfernerand the Griesgletscher was near balanceuntil early 1985. Since then, the mass bal-ances were mostly negative with theextreme years being 2002/03, 1997/98 and1990/91. Since the beginning of measure-ments the Vernagtferner and the Griesfernerlost 11 and 19.5m w.e., respectively.Assuming a density of glacier ice of910kgm–3, this corresponds to a thinning ofthe glaciers of about 12 and 21.4m respec-tively. Another notable feature is the factthat 2002/03 is the first glaciological yearsince the beginning of measurements in1880/81 in which no advancing or station-ary glacier tongue was measured inSwitzerland, i.e.all observed glaciers wereon retreat during the year considered. Thebehaviour of

LangExtract: Processing, current=1,081 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=930 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=712 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,035 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,066 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,116 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,027 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,117 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,027 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=347 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=414 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=523 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=145 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=593 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=657 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=446 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=428 chars, processed=0 chars:  [00:03]

 -------- Processing document [35]: IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned.md --------

Token indices sequence length is longer than the specified maximum sequence length for this model (534 > 512). Running this sequence through the model will result in indexing errors
LangExtract: Processing, current=881 chars, processed=0 chars:  [00:01]

------- chunk id 0
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 0: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: From the report accepted by Working Group II of the Intergovernmental Panel on Climate Change but not approved in detail
Cross-chapter case study citation: These cross-chapter case studies collect together material from the chapters of the underlying report. A roadmap showing the location of
this material is provided in the Introduction to the report. When referencing partial material from within a specific case study, please cite
the chapter in which it originally appears. When referencing a whole case study, please cite as:
Parry, M.L., O.F. Canziani, J.P. Palutikof, P.J. van der Linden and C.E. Hanson, Eds., 2007: Cross-chapter case study. In: Climate Change 2007: Impacts, Adaptation and Vulnerability. Contribution of Working Group II to the Fourth Assessment Report of the Intergovernmental Panel on Climate Change, Cambridge University Press, Cambridge, UK, 843-868.

LangExtract: Processing, current=255 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=307 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=260 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=417 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=342 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=384 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=400 chars, processed=0 chars:  [00:01]

------- chunk id 7
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 7: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: ....................................................864
C2.2.2 Impacts on coral reefs .....................................852
C4.1 Overview ................................................................864
C2.2.3 Climate change and the Great Barrier Reef.....853
C2.2.4 Impact of coral mortality on reef fisheries .......854
C2.3 Multiple stresses on coral reefs ...............................854

LangExtract: Processing, current=348 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=148 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=613 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=737 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=864 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=533 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=784 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=668 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,106 chars, processed=0 chars:  [00:24]
LangExtract: Processing, current=930 chars, processed=0 chars:  [00:05]

------- chunk id 17
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 17: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: and Dobbertin, 2004; Jolly et al., 2005; Fuhrer et al., 2006).
High temperatures and greater dry spell durations increase vegetation flammability (e.g., Burgan et al., 1997), and during the 2003 heatwave a record-breaking incidence of spatially extensive wildfires was observed in European countries (Barbosa et al., 2003), with roughly 650,000 ha of forest burned across the continent (De Bono et al., 2004). Fire extent (area burned), although not fire incidence, was exceptional in Europe in 2003, as found for the extraordinary 2000 fire season in the USA (Brown and Hall, 2001), and noted as an increasing trend in the USA since the 1980s (Westerling et al., 2006). In Portugal, area burned was more than twice the previous extreme (1998) and four times the 1980-2004 average (Trigo et al., 2005, 2006). Over 5% of the total forest area of Portugal burned, with an economic impact exceeding €1 billion (De Bono et al., 2004).

LangExtract: Processing, current=941 chars, processed=0 chars:  [00:22]
LangExtract: Processing, current=985 chars, processed=0 chars:  [00:20]
LangExtract: Processing, current=884 chars, processed=0 chars:  [00:19]
LangExtract: Processing, current=1,158 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=453 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=888 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=873 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=740 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=702 chars, processed=0 chars:  [00:05]

------- chunk id 26
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 26: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Brown, T.J. and B.L. Hall, 2001: Climate analysis of the 2000 fire season. CE-FA Report 01-02, Program for Climate Ecosystem and Fire Applications, Desert Research Institute, Division of Atmospheric Sciences, Reno, Nevada, 40 pp. Burgan, R.E., P.L. Andrews, L.S. Bradshaw, C.H. Chase, R.A. Hartford and D.J. Latham, 1997: WFAS: wildland fire assessment system. Fire Management Notes, 57, 14-17. Ciais, Ph., M. Reichstein, N. Viovy, A. Granier, J. Ogée, V. Allard, M. Aubinet, N. Buchmann, C. Bernhofer, A. Carrara, F. Chevallier, N. de Noblet, A.D. Friend, P. Friedlingstein, T. Grünwald, B. Heinesch, P. Keronen, A. Knohl, G. Krinner, D. Loustau, G. Manca, G. Matteucci, F. Miglietta, J.M. Our- cival,

LangExtract: Processing, current=717 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=899 chars, processed=0 chars:  [00:05]

------- chunk id 28
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 28: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: COPA COGECA, 2003b: Committee of Agricultural Organisations in the Euro- pean Union General Committee for Agricultural Cooperation in the European Union, CDP 03 61 1, Press release, Brussels.
Cox, P.M., R.A. Betts, C.D. Jones, S.A. Spall and I.J. Totterdell, 2000: Accelera- tion of global warming due to carbon-cycle feedbacks in a coupled climate model. Nature, 408, 184-187.
De Bono, A., P. Peduzzi, G. Giuliani and S. Kluser, 2004: Impacts of Summer 2003 Heat Wave in Europe. Early Warning on Emerging Environmental Threats 2, UNEP: United Nations Environment Programme, Nairobi, 4 pp.
EEA, 2003: Air pollution by ozone in Europe in summer 2003: overview of ex- ceedances of EC ozone threshold values during the summer season April–Au- gust 2003 and comparisons with previous years. Topic Report No 3/2003, European Economic Association, Copenhagen, 33 pp.  ropa.eu/topic
_
report
_
2003
_
3/en.

LangExtract: Processing, current=752 chars, processed=0 chars:  [00:05]

------- chunk id 29
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 29: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Fink, A.H., T. Brücher, A. Krüger, G.C. Leckebusch, J.G. Pinto and U. Ulbrich, 2004: The 2003 European summer heatwaves and drought: synoptic diagno- sis and impact. Weather, 59, 209-216.
Fischer, R., Ed., 2005: The condition of forests in Europe: 2005 executive report. United Nations Economic Commission for Europe (UN-ECE), Geneva, 36 pp. Fuhrer, J., M. Beniston, A. Fischlin, C. Frei, S. Goyette, K. Jasper and C. Pfis- ter, 2006: Climate risks and their impact on agriculture and forests in Switzer- land. Climatic Change, 79, 79-102.
Gobron, N., B. Pinty, F. Melin, M. Taberner, M.M. Verstraete, A. Belward, T. Lavergne and J.L. Widlowski, 2005: The state of vegetation in Europe fol- lowing the 2003 drought. Int. J. Remote Sens., 26, 2013-2020.

LangExtract: Processing, current=735 chars, processed=0 chars:  [00:05]

------- chunk id 30
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 30: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Grize, L., A. Huss, O. Thommen, C. Schindler and C. Braun-Fahrländer, 2005: Heat wave 2003 and mortality in Switzerland. Swiss Med. Wkly., 135, 200-205. Hemon, D. and E. Jougla, 2004: La canicule du mois d’aout 2003 en France [The heatwave in France in August 2003]. Rev. Epidemiol. Santé, 52, 3-5. Hegerl, G.C., F.W. Zwiers, P. Braconnot, N.P. Gillett, Y. Luo, J.A. Marengo Orsini, N. Nicholls, J.E. Penner and P.A. Stott, 2007: Understanding and at- tributing climate change. Climate Change 2007: The Physical Science Basis. Contribution of Working Group I to the Fourth Assessment Report of the In- tergovernmental Panel on Climate Change, S. Solomon, D. Qin, M. Manning, Z. Chen, M. Marquis, K.B. Averyt, M. Tignor and H.L. Miller,

LangExtract: Processing, current=753 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=715 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=777 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=854 chars, processed=0 chars:  [00:05]

------- chunk id 34
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 34: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Luterbacher, J., D. Dietrich, E. Xoplaki, M. Grosjean and H. Wanner, 2004: Eu- ropean seasonal and annual temperature variability, trends, and extremes since 1500. Science, 303, 1499-1503.
Martinez-Navarro, F., F. Simon-Soria and G. Lopez-Abente, 2004: Valoracion del impacto de la ola de calor del verano de 2003 sobre la mortalidad [Evaluation of the impact of the heatwave in the summer of 2003 on mortality]. Gac. Sanit., 18, 250-258.
Meehl, G.A. and C. Tebaldi, 2004: More intense, more frequent, and longer last-
ing heatwaves in the 21st century. Science, 305, 994-997.
Michelon, T., P. Magne and F. Simon-Delavelle, 2005: Lessons from the 2003 heat wave in France and action taken to limit the effects of future heat wave. Extreme Weather Events and Public Health Responses, W. Kirch, B. Menne and R. Bertolllini, Eds., Springer, Berlin, 131-140.

LangExtract: Processing, current=645 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=633 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=643 chars, processed=0 chars:  [00:25]
LangExtract: Processing, current=659 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=675 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=350 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=699 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=725 chars, processed=0 chars:  [00:05]

------- chunk id 42
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 42: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Trigo, R.M., J.M.C. Pereira, M.G. Pereira, B. Mota, T.J. Calado, C.C. Dacamara and F.E. Santo, 2006: Atmospheric conditions associated with the exceptional fire season of 2003 in Portugal. Int. J. Climatol., 26, 1741-1757.
Vandentorren, S. and P. Empereur-Bissonnet, 2005: Health impact of the 2003 heat-wave in France. Extreme Weather Events and Public Health Responses, W. Kirch, B. Menne and R. Bertollini, Eds., Springer, Heidelberg, 81-88.
Vandentorren, S., F. Suzan, S. Medina, M. Pascal, A. Maulpoix, J.-C. Cohen and
M. Ledrans, 2004: Mortality in 13 French cities during the August 2003 heat- wave. Am. J. Public Health, 94, 1518-1520.
Vazquez, A. and J.M. Moreno, 2001: Spatial distribution of forest fires in Sierra

LangExtract: Processing, current=918 chars, processed=0 chars:  [00:05]

------- chunk id 43
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 43: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: de Gredos (Central Spain). Forest Ecol. Manag., 147, 55-65.
Westerling, A.L., H.G. Hidalgo, D.R. Cayan and T.W. Swetnam, 2006: Warming and earlier spring increase western US forest wildfire activity. Science, 313, 940- 943.
WHO, 2003: The Health Impacts of 2003 Summer Heat-Waves. Briefing Note for the Delegations of the fifty-third session of the WHO Regional Committee for Europe. World Health Organization, Geneva, 12 pp.
WHO Regional Office for Europe, 2006: 1st meeting of the project ‘Improving Public Health Responses to Extreme Weather/Heat-waves’. EuroHEAT Report on a WHO Meeting in Rome, Italy, 20–22 June 2005. WHO Regional Office for Europe, Copenhagen, 52 pp.
Zebisch, M., T. Grothmann, D. Schröter, C. Hasse, U. Fritsch and W. Cramer, 2005: Climate Change in Germany: Vulnerability and Adaptation of Climate- Sensitive Sectors. Umweltbundesamt Climate Change 10/05 (UFOPLAN 201 41 253), Dessau, 205 pp.

LangExtract: Processing, current=752 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=695 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,026 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=953 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=802 chars, processed=0 chars:  [00:20]
LangExtract: Processing, current=1,021 chars, processed=0 chars:  [00:06]

------- chunk id 49
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 49: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Major bleaching events were observed in 1982-1983, 1987- 1988 and 1994-1995 (Hoegh-Guldberg, 1999). Particularly severe bleaching occurred in 1998 (Figure C2.1), associated with pronounced El Niño events in one of the hottest years on record (Lough, 2000; Bruno et al., 2001). Since 1998 there have been several extensive bleaching events. For example, in 2002 bleaching occurred on much of the Great Barrier Reef (Berkelmans et al., 2004; see C2.2.3) and elsewhere. Reefs in the eastern Caribbean experienced a massive bleaching event in late 2005, another of the hottest years on record. On many Caribbean reefs, bleaching exceeded that of 1998 in both extent and mortality (Figure C2.1), and reefs are in decline as a result of the synergistic effects of multiple stresses (Gardner et al., 2005; McWilliams et al., 2005; see C2.3.1). There is considerable variability in coral susceptibility and recovery to elevated SST in both time and space, and in the incidence of mortality (Webster et al., 1999; Wilkinson, 2002;

LangExtract: Processing, current=616 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=1,045 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=845 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=527 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=505 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=477 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=981 chars, processed=0 chars:  [00:06]

------- chunk id 56
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 56: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Coral reefs will also be affected by rising atmospheric CO2 concentrations (Orr et al., 2005; Raven et al., 2005; Denman et al., 2007, Box 7.3) resulting in declining calcification. Experiments at expected aragonite concentrations demonstrated a reduction in coral calcification (Marubini et al., 2001; Langdon et al., 2003; Hallock, 2005), coral skeleton weakening (Marubini et al., 2003) and strong temperature dependence (Reynaud et al., 2003). Oceanic pH projections decrease at a greater rate and to a lower level than experienced over the past 20 million years (Caldeira and Wickett, 2003; Raven et al., 2005; Turley et al., 2006). Doubling CO2 will reduce calcification in aragonitic corals by 20%-60% (Kleypas et al., 1999; Kleypas and Langdon, 2002; Reynaud et al., 2003; Raven et al., 2005). By 2070 many reefs could reach critical aragonite saturation states (Feely et al., 2004; Orr et al., 2005), resulting in reduced coral cover and greater erosion of reef frameworks

LangExtract: Processing, current=826 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=913 chars, processed=0 chars:  [00:05]

------- chunk id 58
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 58: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: higher latitudes with more optimal SST is unlikely, due both to latitudinally decreasing aragonite concentrations and projected atmospheric CO2 increases (Kleypas et al., 2001; Guinotte et al., 2003; Orr et al., 2005; Raven et al., 2005). Coral migration is also limited by lack of available substrate (see C2.2.2). Elevated SST and decreasing aragonite have a complex synergy (Harvell et al., 2002; Reynaud et al., 2003; McNeil et al., 2004; Kleypas et al., 2005) but could produce major coral reef changes (Guinotte et al., 2003; Hoegh-Guldberg, 2005). Corals could become rare on tropical and sub-tropical reefs by 2050 due to the combined effects of increasing CO2 and increasing frequency of bleaching events (at 2-3 × CO2) (Kleypas and Langdon, 2002; Hoegh-Guldberg, 2005; Raven et al., 2005). Other climate change factors (such as sea-level rise, storm impact and aerosols) and non-climate factors (such as

LangExtract: Processing, current=447 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=826 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,119 chars, processed=0 chars:  [00:24]
LangExtract: Processing, current=22 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,078 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,081 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=356 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=786 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=887 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=988 chars, processed=0 chars:  [00:06]

------- chunk id 68
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 68: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Sea temperatures on the GBR have warmed by about 0.4°C over the past century (Lough, 2000). Temperatures currently typical of the northern tip of the GBR are very likely to extend to its southern end by 2040 to 2050 (SRES scenarios A1, A2) and 2070 to 2090 (SRES scenarios B1, B2) (Done et al., 2003). Temperatures only 1°C above the long-term summer maxima already cause mass coral bleaching (loss of symbiotic algae). Corals may recover but will die under high or prolonged temperatures (2 to 3°C above long-term maxima for at least 4 weeks). The GBR has experienced eight mass bleaching events since 1979 (1980, 1982, 1987, 1992, 1994, 1998, 2002 and 2006); there are no records of events prior to 1979 (Hoegh- Guldberg, 1999). The most widespread and intense events occurred in the summers of 1998 and 2002, with about 42% and 54% of reefs affected, respectively (Done et al., 2003; Berkelmans et al., 2004). Mortality was distributed patchily, with the greatest effects on near-shore

LangExtract: Processing, current=190 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,001 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=1,049 chars, processed=0 chars:  [00:11]

------- chunk id 71
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 71: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Even under a moderate warming scenario (A1T, 2°C by 2100), corals on the GBR are very likely to be exposed to regular summer temperatures that exceed the thermal thresholds observed over the past 20 years (Done et al., 2003). Annual bleaching is projected under the A1FI scenario by 2030, and under A1T by 2050 (Done et al., 2003; Wooldridge et al., 2005). Given that the recovery time from a severe bleaching-induced mortality event is at least 10 years (and may exceed 50 years for full recovery), these models suggest that reefs are likely to be dominated by non-coral organisms such as macroalgae by 2050 (Hoegh-Guldberg, 1999; Done et al., 2003). Substantial impacts on biodiversity, fishing and tourism are likely. Maintenance of hard coral cover on the GBR will require corals to increase their upper thermal tolerance limits at the same pace as the change in sea temperatures driven by climate change, i.e., about 0.1- 0.5°C/decade (Donner et al., 2005). There is currently little evidence that corals have the capacity for such rapid genetic

LangExtract: Processing, current=1,223 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=482 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,134 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,099 chars, processed=0 chars:  [00:45]
LangExtract: Processing, current=1,018 chars, processed=0 chars:  [00:06]

------- chunk id 76
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 76: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: • subsistence exploitation of reef fish in Fiji (Dulvy et al.,
• giant clam harvesting on reefs, Milne Bay, Papua New
• non-indigenous species invasion of coral habitats in Guam
There is another category of ‘stress’ that may inadvertently result in damage to coral reefs – the human component of poor governance (Goldberg and Wilkinson, 2004). This can accompany political instability; one example being problems with contemporary coastal management in the Solomon Islands (Lane, 2006).
Abdullah, A., Z. Yasin, W. Ismail, B. Shutes and M. Fitzsimons, 2002: The effect of early coastal development on the fringing coral reefs of Langkawi: a study in small-scale changes. Malaysian Journal of Remote Sensing and GIS, 3, 1-10. Access Economics, 2005: Measuring the Economic and Financial Value of the Great Barrier Reef Marine Park. Report by Access Economics for Great Barrier Reef Marine Park Authority, June 2005, 61 pp.  com.au/publicationsreports/showreport.php?id=10&searchfor=Eco- nomic%20Consulting&searchby=area.

LangExtract: Processing, current=736 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=757 chars, processed=0 chars:  [00:05]

------- chunk id 78
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 78: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Berkelmans, R., G. De’ath, S. Kininmonth and W.J. Skirving, 2004: A compari- son of the 1998 and 2002 coral bleaching events of the Great Barrier Reef: spa- tial correlation, patterns and predictions. Coral Reefs, 23, 74-83.
Bindoff, N., J. Willebrand, V. Artale, A. Cazenave, J. Gregory, S. Gulev, K. Hanawa, C. Le Quéré, S. Levitus, Y. Nojiri, C.K. Shum, L. Talley and A. Unnikrishnan, 2007: Observations: oceanic climate change and sea level. Climate Change 2007: The Physical Science Basis. Contribution of Working Group I to the Fourth As- sessment Report of the Intergovernmental Panel on Climate Change, S. Solomon, D. Qin, M. Manning, Z. Chen, M. Marquis, K.B. Averyt, M. Tignor and H.L. Miller, Eds., Cambridge University Press, Cambridge, 385-432.

LangExtract: Processing, current=887 chars, processed=0 chars:  [00:05]

------- chunk id 79
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 79: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Bruno, J.F., C.E. Siddon, J.D. Witman, P.L. Colin and M.A. Toscano, 2001: El Niño related coral bleaching in Palau, Western Caroline Islands. Coral Reefs, 20, 127-136.
Bryant, D., L. Burke, J. McManus and M. Spalding, 1998: Reefs at Risk: A Map- Based Indicator of Threats to the World’s Coral Reefs. World Resources Institute, Washington, DC, 56 pp.
Buddemeier, R.W., J.A. Kleypas and B. Aronson, 2004: Coral Reefs and Global Climate Change: Potential Contributions of Climate Change to Stresses on Coral Reef Ecosystems. Report prepared for the Pew Centre on Global Climate Change, Arlington, Virginia, 56 pp.
Burke, L. and J. Maidens, 2004: Reefs at Risk in the Caribbean. World Resources
Institute, Washington, District of Columbia, 81 pp.
Burke, L., E. Selig and M. Spalding, 2002: Reefs at Risk in Southeast Asia. World
Resources Institute, Washington, District of Columbia, 72 pp.

LangExtract: Processing, current=646 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=757 chars, processed=0 chars:  [00:05]

------- chunk id 81
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 81: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Denman, K.L., G. Brasseur, A. Chidthaisong, P. Ciais, P. Cox, R.E. Dickinson, D. Hauglustaine, C. Heinze, E. Holland, D. Jacob, U. Lohmann, S. Ramachandran, P.L. da Silva Dias, S.C. Wofsy and X. Zhang, 2007: Couplings between changes in the climate system and biogeochemistry. Climate Change 2007: The Physi- cal Science Basis. Contribution of Working Group I to the Fourth Assessment Re- port of the Intergovernmental Panel on Climate Change, S. Solomon, D. Qin, M. Manning, Z. Chen, M. Marquis, K.B. Averyt, M. Tignor and H.L. Miller, Eds., Cambridge University Press, Cambridge, 499-587.
Dickinson, W.R., 2004: Impacts of eustasy and hydro-isostasy on the evolution and landforms of Pacific atolls. Palaeogeogr. Palaeoclimatol. Palaeoecol., 213, 251-269.

LangExtract: Processing, current=716 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=575 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=673 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=564 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=616 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=708 chars, processed=0 chars:  [00:16]
LangExtract: Processing, current=439 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=319 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=732 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=819 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=790 chars, processed=0 chars:  [00:05]

------- chunk id 92
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 92: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: LeClerq, N., J.-P. Gattuso and J. Jaubert, 2002: Primary production, respiration, and calcification of a coral reef mesocosm under increased CO2 pressure. Lim- nol. Oceanogr., 47, 558-564.
Lesser, M.P., 2004: Experimental biology of coral reef ecosystems. J. Exp. Mar.
Little, A.F., M.J.H. van Oppen and B.L. Willis, 2004: Flexibility in algal en-
dosymbioses shapes growth in reef corals. Science, 304, 1492-1494.
Hoegh-Guldberg, O., 1999: Climate change, coral bleaching and the future of the
Lough, J.M., 2000: 1997-98: unprecedented thermal stress to coral reefs? Geo-
world’s coral reefs. Mar. Freshwater Res., 50, 839-866.
Hoegh-Guldberg, O., 2004: Coral reefs in a century of rapid environmental change.
Lough, J.M. and D.J. Barnes, 2000: Environmental controls on growth of the mas-

LangExtract: Processing, current=481 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=575 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=643 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=565 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=672 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=759 chars, processed=0 chars:  [00:06]

------- chunk id 98
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 98: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Mestas-Nunez, A.M. and A.J. Miller, 2006: Interdecadal variability and climate change in the eastern tropical Pacific: a review. Prog. Oceanogr., 69, 267-284. Nott, J. and M. Hayne, 2001: High frequency of ‘super-cyclones’ along the Great
Barrier Reef over the past 5,000 years. Nature, 413, 508-512.
Nyström, M., C. Folke and F. Moberg, 2000: Coral reef disturbance and resilience
in a human-dominated environment. Trends Ecol. Evol., 15, 413-417.
Obura, D.O., 2005: Resilience and climate change: lessons from coral reefs and bleaching in the western Indian Ocean. Estuar. Coast. Shelf Sci., 63, 353-372. Ohde, S. and M.M.M. Hossain, 2004: Effect of CaCO3 (aragonite) saturation state
of seawater on calcification of Porites coral. Geochem. J., 38, 613-621.

LangExtract: Processing, current=476 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=563 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=779 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=678 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=548 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=812 chars, processed=0 chars:  [00:05]

------- chunk id 104
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 104: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Turley, C., J. Blackford, S. Widdicombe, D. Lowe and P. Nightingale, 2006: Re- viewing the impact of increased atmospheric CO2 on oceanic pH and the marine ecosystem. Avoiding Dangerous Climate Change, H.J. Schellnhuber, W. Cramer, N. Nakićenović, T.M.L. Wigley and G. Yohe, Eds., Cambridge University Press, Cambridge, 65-70.
Villanueva, R., H. Yap and N. Montaño, 2006: Intensive fish farming in the Philip- pines is detrimental to the reef-building coral Pocillopora damicornis. Mar. Ecol.–Prog. Ser., 316, 165-174.
Vunisea, A., 2003: Coral harvesting and its impact on local fisheries in Fiji. SPC
Women in Fisheries Information Bulletin, 12, 17-20.
Webster, P.J., A.M. Moore, J.P. Loschnigg and R.R. Leben, 1999: Coupled ocean– temperature dynamics in the Indian Ocean during 1997-98. Nature, 401, 356- 360.

LangExtract: Processing, current=819 chars, processed=0 chars:  [00:05]

------- chunk id 105
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 105: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Whittingham, E., J. Campbell and P. Townsley, 2003: Poverty and Reefs. DFID-
Precht, W.F. and R.B. Aronson, 2004: Climate flickers and range shifts of coral
Wilkinson, C.R., 2002: Status of Coral Reefs of the World. Australian Institute of
Ramessur, R., 2002: Anthropogenic-driven changes with focus on the coastal zone of Mauritius, south-western Indian Ocean. Reg. Environ. Change, 3, 99-106. Raven, J., K. Caldeira, H. Elderfield, O. Hoegh-Guldberg, P. Liss, U. Riebesell, J. Shepherd, C. Turley and A. Watson, 2005: Ocean acidification due to increasing atmospheric carbon dioxide. Policy Document 12/05, The Royal Society, The Clyvedon Press Ltd, Cardiff, 68 pp.
Riegl, B., 2003: Climate change and coral reefs: different effects in two high-lat-
itude areas (Arabian Gulf, South Africa). Coral Reefs, 22, 433-446.

LangExtract: Processing, current=616 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=693 chars, processed=0 chars:  [00:16]
LangExtract: Processing, current=262 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=871 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=563 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,174 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=775 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,095 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,066 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,077 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=928 chars, processed=0 chars:  [00:05]

------- chunk id 116
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 116: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Zhang, 2000; Inam et al., 2003; Li et al., 2004b; Thanh et al., 2004; Saito, 2005; Woodroffe et al., 2006; Wolanski, 2007).
C3.2.2 Climate change and the fisheries of the lower
Mekong: an example of multiple stresses on a megadelta fisheries system due to human activity (Chapter 5, Box 5.3)
Fisheries are central to the lives of the people, particularly the rural poor, who live in the lower Mekong countries. Two- thirds of the basin’s 60 million people are in some way active in fisheries, which represent about 10% of the GDP of Cambodia and Lao People’s Democratic Republic (PDR). There are approximately 1,000 species of fish commonly found in the river, with many more marine vagrants, making it one of the most prolific and diverse faunas in the world (MRC, 2003). Recent estimates of the annual catch from capture fisheries alone exceed 2.5 Mtonnes (Hortle and Bush, 2003), with the delta contributing over 30% of this.

LangExtract: Processing, current=534 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,232 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=911 chars, processed=0 chars:  [00:17]
LangExtract: Processing, current=1,163 chars, processed=0 chars:  [00:14]
LangExtract: Processing, current=1,192 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=54 chars, processed=0 chars:  [00:24]
LangExtract: Processing, current=1,260 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,040 chars, processed=0 chars:  [00:24]
LangExtract: Processing, current=688 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=774 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=984 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=706 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,039 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=621 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=508 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=446 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=838 chars, processed=0 chars:  [00:19]
LangExtract: Processing, current=711 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=762 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=733 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=786 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=737 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=684 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=735 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=710 chars, processed=0 chars:  [00:05]

------- chunk id 141
Error when applying LangExtract on document IPCC 2018 - Working Group 2 Cross-chapter case studies_cleaned, text block 141: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Thanh, T.D., Y. Saito, D.V. Huy, V.L. Nguyen, T.K.O. Ta and M. Tateish, 2004: Regimes of human and climate impacts on coastal changes in Vietnam. Reg. En- viron. Change, 4, 49-62.
Walsh, J.E., O. Anisimov, J.O.M. Hagen, T. Jakobsson, J. Oerlemans, T.D. Prowse, V. Romanovsky, N. Savelieva, M. Serreze, I. Shiklomanov and S. Solomon, 2005: Cryosphere and hydrology. Arctic Climate Impacts Assessment, ACIA, C. Symon, L. Arris and B. Heal, Eds., Cambridge University Press, Cambridge, 183-242. Wassmann, R., N.X. Hein, C.T. Hoanh and T.P. Tuong, 2004: Sea level rise affect- ing the Vietnamese Mekong Delta: water elevation in the flood season and im- plications for rice production. Climatic Change, 66, 89-107.

LangExtract: Processing, current=993 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,169 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,340 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,165 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,086 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=630 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=747 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,260 chars, processed=0 chars:  [00:08]
LangExtract: Processing, current=52 chars, processed=0 chars:  [00:02]
LangExtract: Processing, current=1,278 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=728 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,090 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,229 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=318 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,129 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,301 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=1,384 chars, processed=0 chars:  [00:06]

 -------- Processing document [36]: Kadir 2014 - The Impact of Natural Disasters on Critical Infrastructures - A Domino Effect-based Study_cleaned.md --------

LangExtract: Processing, current=198 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=1,407 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=646 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,138 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=831 chars, processed=0 chars:  [00:05]
LangExtract: Processing, current=1,161 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,165 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,281 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=824 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,059 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=1,287 chars, processed=0 chars:  [00:25]
LangExtract: Processing, current=1,066 chars, processed=0 chars:  [00:13]

------- chunk id 11
Error when applying LangExtract on document Kadir 2014 - The Impact of Natural Disasters on Critical Infrastructures - A Domino Effect-based Study_cleaned, text block 11: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: In the case of the disastrous chain of events in Tōhoku, the trigger was an earthquake  followed  by  a  tsunami.  Figure  2,  which  represents  the  sequence  of accidents  caused  by  the  earthquake,  gives  a  more  detailed  picture  of  some  of
The Impact of Natural Disasters on Critical Infrastructures      221
Figure 1 The Main Critical Infrastructures Damaged by the Effects of the Earthquake.
Figure 2 The Accident Sequences Generated by the Earthquake.
the interrelated events that occurred during the disaster and the significance of the interdependencies of the CI. For example, let us consider the chain of events leading to a weakening of the power supply. The earthquake (as the initiator) trig- gers  a  tsunami,  which,  in  turn,  affects  the  nuclear  plants  that  produce  energy. As a result, the authorities are forced to reduce the overall output produced and
supplied to the network. This further weakens the rest of the power plants, which are unable to deliver power to the victims.
3   Critical Infrastructure, Sources of Danger, and

LangExtract: Processing, current=1,234 chars, processed=0 chars:  [00:23]
LangExtract: Processing, current=800 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=900 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,279 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,220 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,137 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,345 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,337 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=648 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=910 chars, processed=0 chars:  [00:05]

------- chunk id 21
Error when applying LangExtract on document Kadir 2014 - The Impact of Natural Disasters on Critical Infrastructures - A Domino Effect-based Study_cleaned, text block 21: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: To  identify  sources  of  danger,  the  Method  Organized  for  a  Systematic  Analysis of  Risks,  or  MOSAR  (Perrin  et  al.  2012),  can  be  used.  MOSAR  facilitates  a  risk analysis by breaking down the infrastructure into subsystems and systematically identifying the level to which each subsystem can be a source of danger. To link the sources of danger (source systems) to targets (target systems), the Model of Analysis of Dysfunctional Systems (MADS) (Thivel et al. 2008; Perrin et al. 2012) is highly suited. This method is based on the principle of determining the propaga- tion of the “low of danger” in a “danger field” (see Figure 5).
Figure 5 Step 2: Identification of Sources of Danger.
The  aim  of  this  step  is  to  identify  all  links  (interdependencies)  between  infra- structures. The four main interdependencies are as follows (Rinaldi et al. 2001; Robert and Morabito 2008): –

LangExtract: Processing, current=1,223 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,199 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,146 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=1,228 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,166 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=993 chars, processed=0 chars:  [00:05]

------- chunk id 27
Error when applying LangExtract on document Kadir 2014 - The Impact of Natural Disasters on Critical Infrastructures - A Domino Effect-based Study_cleaned, text block 27: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: (cid:31) (cid:31) (cid:31) (cid:31) y N x d t , ), (
In  the  case  of  domino  effect  analysis,  the  failure  of  a  subsystem  depends  on the  dynamic  characteristics  of  the  escalation  (input)  vectors,  threshold  values, and the aforementioned influencing factors. Therefore, a domino system can be described by the following vector function )T –
, (cid:31) x is a real vector (input vector) with p dimension in a space of physical state at time t. xi may be divided into two types of parameters: random physical effects and influencing factors (intervention system and human factor). (cid:31) d is a real vector (input vector) with g dimension; dj repre- sents the deterministic input parameters of the system (physical characteris- tics of system-like thresholds). (cid:31) )T y variable depending on input parameters (Kadri et al. 2011b, 2013).
is the vector of system output with k dimensions; yi is a random
The Impact of Natural Disasters on Critical Infrastructures      233

LangExtract: Processing, current=962 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,113 chars, processed=0 chars:  [00:15]
LangExtract: Processing, current=1,007 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,136 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=974 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=965 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=974 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=964 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,072 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=855 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,169 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=1,325 chars, processed=0 chars:  [00:14]

------- chunk id 39
Error when applying LangExtract on document Kadir 2014 - The Impact of Natural Disasters on Critical Infrastructures - A Domino Effect-based Study_cleaned, text block 39: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: Three zones can then be defined: the irreversible effects zone, the beginning-of- lethality effects zone, and high lethality zone.
This  paper  presents  a  methodology  for  CI  risk  assessment  in  the  framework  of CEA.  This  method  allows  the  identification  of  all  sources  of  danger  involving CI,  the  primary  events  that  may  cause  CI  failure,  and  the  accident  sequences generated  following  that  failure  (destruction),  taking  into  account  human  and organizational  factors  and  the  interdependencies  among  CI  and/or  CI  systems (components).
This  work  deals  with  cascade  effects  caused  by  natural  events  and  shows the importance of taking natural risks into account when studying CI, especially in terms of a potential chain of accidents. It then illustrates the suitability of the proposed  methodology  in  assessing  the  consequences  of  cascade  effects,  and discusses  the  usefulness  of  such  a  methodology  in  establishing  risk  reduction strategies.
Finally, an analysis confirms that the study of natural events in the frame- work  of  CEA  is  necessary  given  their  catastrophic  consequences.  Hence,  much research remains to be done to improve the safety of CI, and much more impor- tance must be placed on the study of natural events and disasters.


 -------- Processing document [37]: Kettle 2020 - Storm Xaver over Europe in December 2013 Overview of energy impacts and North Sea events_cleaned.md --------

LangExtract: Processing, current=461 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,215 chars, processed=0 chars:  [00:11]
LangExtract: Processing, current=856 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=739 chars, processed=0 chars:  [00:19]
LangExtract: Processing, current=1,017 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=979 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=1,165 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=1,060 chars, processed=0 chars:  [00:32]

------- chunk id 7
Error when applying LangExtract on document Kettle 2020 - Storm Xaver over Europe in December 2013 Overview of energy impacts and North Sea events_cleaned, text block 7: Content must contain an 'extractions' key.
Probably content does not contain an 'extractions' key.
Respective chunk text: (Chen and Xu, 2016). Turbine tower collapse oc- curred in most of these cases during conditions of high wind speeds (stronger than a category 1 hurricane) and large changes in wind direction. Offshore wind farms have been in operating in the North Sea since 2000 (Buchana and Mc- Sharry, 2019), but there have been no reports of extensive wind turbine collapse in this area comparable with the worst coastal cases from east and south Asia. Mostly this is be- cause the largest historical wind speeds in the region seldom exceed the threshold at which the wind turbine tower has been threatened (Buchana and McSharry, 2019). On the other hand, there have been media reports of unusual isolated acci- dents at certain offshore sites. At the Danish offshore Samsø wind farm in the Kattegat, a nacelle fell off the top of a wind turbine tower into the sea on 3 December 2015 (4Coffshore, 2015). At the Alpha Ventus wind farm in the German Bight, the nacelle cover fell off one of the turbines in April 2018 (Wind Action, 2018). The brief media reports of the events

LangExtract: Processing, current=241 chars, processed=0 chars:  [00:06]
LangExtract: Processing, current=1,208 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=1,246 chars, processed=0 chars:  [00:26]
LangExtract: Processing, current=1,038 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=946 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,128 chars, processed=0 chars:  [00:13]
LangExtract: Processing, current=574 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,183 chars, processed=0 chars:  [00:27]
LangExtract: Processing, current=317 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,180 chars, processed=0 chars:  [00:12]
LangExtract: Processing, current=714 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,107 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=912 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=649 chars, processed=0 chars:  [00:07]
LangExtract: Processing, current=573 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,037 chars, processed=0 chars:  [00:09]
LangExtract: Processing, current=557 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=717 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=946 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=1,293 chars, processed=0 chars:  [00:10]
LangExtract: Processing, current=683 chars, processed=0 chars:  [00:04]
LangExtract: Processing, current=616 chars, processed=0 chars:  [00:03]
LangExtract: Processing, current=1,150 chars, processed=0 chars:  [00:00]

KeyboardInterrupt:

In [23]:
responses_all_docs_unnested = list(chain(*responses_all_docs))



# create dataframe of LX response
df_respones = pd.DataFrame(
    columns=[
        "infrastructure_type",
        "damage",
        "geolocation",
        "citation_id",
        "attributes",
        "name",
        "char_span",
        "token_span",
    ]
)
for i in range(len(responses_all_docs_unnested)):
    for j in responses_all_docs_unnested[i].extractions:
        try:
            ci_impact_dict = {
                "infrastructure_type": (
                    j.extraction_text
                    if j.extraction_class == "infrastructure_type"
                    else None
                ),
                "damage": j.attributes.get("damage", None),
                "geolocation": j.attributes.get("geolocation", None),
                #    "name": j.attributes.get("name", None),
                "attributes": j.attributes,
                "citation_id": responses_citations[i],
                "char_span": j.char_interval if hasattr(j, "char_interval") else None,
                "token_span": (
                    j.token_interval if hasattr(j, "token_interval") else None
                ),
            }
        except Exception as e:
            print(
                f"Error processing extraction {j} in document {responses_citations[i]}: {e}"
            )
            continue  # with next extraction

        df_respones = pd.concat(
            [df_respones, pd.DataFrame([ci_impact_dict])], ignore_index=True
        )

df_respones

# if os.path.exists(LX_OUTPUTS_DF_FILEPATH):
#     print(
#         f"File {LX_OUTPUTS_DF_FILEPATH.name} already exists. Renaming file to {LX_OUTPUTS_DF_FILEPATH.stem}_{current_timestamp}.csv."
#     )
#     LX_OUTPUTS_DF_FILEPATH = (
#         LX_OUTPUTS_DF_FILEPATH.parent
#         / f"{LX_OUTPUTS_DF_FILEPATH.stem}_{current_timestamp}.csv"
#     )
#     df_respones.to_csv(LX_OUTPUTS_DF_FILEPATH, index=False)

# else:
#     print(f"Saving LangExtract DF output to {LX_OUTPUTS_DF_FILEPATH}")
#     df_respones.to_csv(LX_OUTPUTS_DF_FILEPATH, index=False)

# print("\n\n -------- Finished LangExtract processing -------- \n")

Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed, severely damaged', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed, severely damaged', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed, severely damaged', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=4, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=5, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=6, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=7, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=5, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=6, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=7, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='power infrastructure', char_interval=None, alignment_status=None, extraction_index=8, group_index=2, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='affected', char_interval=None, alignment_status=None, extraction_index=9, group_index=2, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=10, group_index=2, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'

,infrastructure_type,damage,geolocation,citation_id,attributes,name,char_span,token_span
0,roads,blocked,Greece,Stamataki 2023 - Greece’s record rainfall and ...,"{'damage': 'blocked', 'geolocation': 'Greece'}",NaN,None,None
1,roads,blocked,Zagora,Stamataki 2023 - Greece’s record rainfall and ...,"{'damage': 'blocked', 'geolocation': 'Zagora'}",NaN,None,None
2,roads,blocked,Milan (city),Stamataki 2023 - Greece’s record rainfall and ...,"{'damage': 'blocked', 'geolocation': 'Milan (c...",NaN,None,None
3,highway,affected,Partinico area,Stamataki 2023 - Greece’s record rainfall and ...,"{'damage': 'affected', 'geolocation': 'Partini...",NaN,None,None
4,ports,temporarily closed,Valencia and Sagunto ports,Stamataki 2023 - Greece’s record rainfall and ...,"{'damage': 'temporarily closed', 'geolocation'...",NaN,None,None
...,...,...,...,...,...,...,...,...
2083,motorways,closure,NAN,Kadir 2014 - The Impact of Natural Disasters o...,"{'damage': 'closure', 'geolocation': 'NAN'}",NaN,None,None
2084,NAN,NAN,NAN,Kadir 2014 - The Impact of Natural Disasters o...,"{'damage': 'NAN', 'geolocation': 'NAN'}",NaN,None,None
2085,NAN,NAN,NAN,Kadir 2014 - The Impact of Natural Disasters o...,"{'damage': 'NAN', 'geolocation': 'NAN'}",NaN,None,None
2086,motorways,closure,NAN,Kadir 2014 - The Impact of Natural Disasters o...,"{'damage': 'closure', 'geolocation': 'NAN'}",NaN,None,None
2087,62 bridges,destroyed,Ahr valley,Kadir 2014 - The Impact of Natural Disasters o...,"{'damage': 'destroyed', 'geolocation': 'Ahr va...",NaN,None,None

## Saving

In [24]:
print("\n\n -------- Saving LangExtract output as jsonl and csv -------- \n")

responses_all_docs_unnested = list(chain(*responses_all_docs))


current_timestamp = datetime.today().strftime("%Y-%m-%d")


# check if file exists already
if os.path.exists(LX_OUTPUTS_FILEPATH):
    print(
        f"File {LX_OUTPUTS_FILEPATH.name} already exists. Renaming file to {LX_OUTPUTS_FILEPATH.stem}_{current_timestamp}.jsonl."
    )
    lx_response_filename_timestamped = (
        f"{LX_OUTPUTS_FILEPATH.stem}_{current_timestamp}.jsonl"
    )
    lx.io.save_annotated_documents(
        responses_all_docs_unnested,
        output_name=lx_response_filename_timestamped,
        output_dir=LX_OUTPUTS_FILEPATH.parent,
    )
else:
    print(f"Saving LangExtract output to {LX_OUTPUTS_FILEPATH}")
    lx.io.save_annotated_documents(
        responses_all_docs_unnested,
        output_name=lx_response_filename,
        output_dir=LX_OUTPUTS_FILEPATH.parent,
    )

# create dataframe of LX response
df_respones = pd.DataFrame(
    columns=[
        "infrastructure_type",
        "damage",
        "geolocation",
        "citation_id",
        "attributes",
        "name",
        "char_span",
        "token_span",
    ]
)
for i in range(len(responses_all_docs_unnested)):
    for j in responses_all_docs_unnested[i].extractions:
        try:
            ci_impact_dict = {
                "infrastructure_type": (
                    j.extraction_text
                    if j.extraction_class == "infrastructure_type"
                    else None
                ),
                "damage": j.attributes.get("damage", None),
                "geolocation": j.attributes.get("geolocation", None),
                #    "name": j.attributes.get("name", None),
                "attributes": j.attributes,
                "citation_id": responses_citations[i],
                "char_span": j.char_interval if hasattr(j, "char_interval") else None,
                "token_span": (
                    j.token_interval if hasattr(j, "token_interval") else None
                ),
            }
        except Exception as e:
            print(
                f"Error processing extraction {j} in document {responses_citations[i]}: {e}"
            )
            continue  # with next extraction

        df_respones = pd.concat(
            [df_respones, pd.DataFrame([ci_impact_dict])], ignore_index=True
        )


if os.path.exists(LX_OUTPUTS_DF_FILEPATH):
    print(
        f"File {LX_OUTPUTS_DF_FILEPATH.name} already exists. Renaming file to {LX_OUTPUTS_DF_FILEPATH.stem}_{current_timestamp}.csv."
    )
    LX_OUTPUTS_DF_FILEPATH = (
        LX_OUTPUTS_DF_FILEPATH.parent
        / f"{LX_OUTPUTS_DF_FILEPATH.stem}_{current_timestamp}.csv"
    )
    df_respones.to_csv(LX_OUTPUTS_DF_FILEPATH, index=False)

else:
    print(f"Saving LangExtract DF output to {LX_OUTPUTS_DF_FILEPATH}")
    df_respones.to_csv(LX_OUTPUTS_DF_FILEPATH, index=False)

print("\n\n -------- Finished LangExtract processing -------- \n")

 -------- Saving LangExtract output as jsonl and csv --------

Saving LangExtract output to ../data/langextract_output/llama3_mix_cigeo_2026-02-03.jsonl

LangExtract: Saving to llama3_mix_cigeo_2026-02-03.jsonl: 1025 docs [00:00, 6638.84 docs/s]

✓ Saved 1025 documents to llama3_mix_cigeo_2026-02-03.jsonl
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed, severely damaged', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed, severely damaged', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed, severely damaged', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=4, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=5, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=6, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=7, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=5, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=6, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=7, group_index=1, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='power infrastructure', char_interval=None, alignment_status=None, extraction_index=8, group_index=2, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='affected', char_interval=None, alignment_status=None, extraction_index=9, group_index=2, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=10, group_index=2, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document AEMET 2024 - ESTUDIO SOBRE LA SITUACIÓN DE LLUVIAS INTENSAS_cleaned: 'NoneType' object has no attribute 'get'

Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='Deichbruch', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='dam failure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Stendal (Landkreis)', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='water supply', char_interval=None, alignment_status=None, extraction_index=4, group_index=1, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='polluted', char_interval=None, alignment_status=None, extraction_index=5, group_index=1, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Belgium', char_interval=None, alignment_status=None, extraction_index=6, group_index=1, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='power infrastructure', char_interval=None, alignment_status=None, extraction_index=7, group_index=2, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='affected', char_interval=CharInterval(start_pos=694, end_pos=702), alignment_status=<AlignmentStatus.MATCH_FUZZY: 'match_fuzzy'>, extraction_index=8, group_index=2, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=9, group_index=2, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=10, group_index=3, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=11, group_index=3, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=12, group_index=3, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=13, group_index=4, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=14, group_index=4, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=15, group_index=4, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=16, group_index=4, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=3, group_index=1, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=4, group_index=1, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=5, group_index=1, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=6, group_index=1, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='network lines', char_interval=CharInterval(start_pos=29, end_pos=42), alignment_status=<AlignmentStatus.MATCH_EXACT: 'match_exact'>, extraction_index=1, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='damaged', char_interval=CharInterval(start_pos=48, end_pos=55), alignment_status=<AlignmentStatus.MATCH_EXACT: 'match_exact'>, extraction_index=2, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Sydkraft', char_interval=CharInterval(start_pos=59, end_pos=67), alignment_status=<AlignmentStatus.MATCH_EXACT: 'match_exact'>, extraction_index=3, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='electrical network', char_interval=CharInterval(start_pos=65, end_pos=84), alignment_status=<AlignmentStatus.MATCH_FUZZY: 'match_fuzzy'>, extraction_index=1, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='severe damages', char_interval=CharInterval(start_pos=39, end_pos=54), alignment_status=<AlignmentStatus.MATCH_EXACT: 'match_exact'>, extraction_index=2, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Sweden', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='electrical grid', char_interval=CharInterval(start_pos=182, end_pos=199), alignment_status=<AlignmentStatus.MATCH_FUZZY: 'match_fuzzy'>, extraction_index=1, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='significant damage', char_interval=CharInterval(start_pos=157, end_pos=176), alignment_status=<AlignmentStatus.MATCH_EXACT: 'match_exact'>, extraction_index=2, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='not specified', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document Eurelectric 2006 - Impacts of Severe Storms on Electric Grids_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='motorways', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='closure', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='geolocation', extraction_text='Ahr valley', char_interval=None, alignment_status=None, extraction_index=3, group_index=0, description=None, attributes=None) in document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='region', extraction_text='Rhineland-Palatinate', char_interval=None, alignment_status=None, extraction_index=4, group_index=0, description=None, attributes=None) in document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='infrastructure_type', extraction_text='62 bridges', char_interval=None, alignment_status=None, extraction_index=1, group_index=0, description=None, attributes=None) in document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned: 'NoneType' object has no attribute 'get'
Error processing extraction Extraction(extraction_class='damage', extraction_text='destroyed', char_interval=None, alignment_status=None, extraction_index=2, group_index=0, description=None, attributes=None) in document Fekete 2025 - Cascading impact chains and recovery challenges of the 2024 Valencia catastrophic floods_cleaned: 'NoneType' object has no attribute 'get'

In [25]:
df_respones

,infrastructure_type,damage,geolocation,citation_id,attributes,name,char_span,token_span
0,roads,blocked,Greece,Stamataki 2023 - Greece’s record rainfall and ...,"{'damage': 'blocked', 'geolocation': 'Greece'}",NaN,None,None
1,roads,blocked,Zagora,Stamataki 2023 - Greece’s record rainfall and ...,"{'damage': 'blocked', 'geolocation': 'Zagora'}",NaN,None,None
2,roads,blocked,Milan (city),Stamataki 2023 - Greece’s record rainfall and ...,"{'damage': 'blocked', 'geolocation': 'Milan (c...",NaN,None,None
3,highway,affected,Partinico area,Stamataki 2023 - Greece’s record rainfall and ...,"{'damage': 'affected', 'geolocation': 'Partini...",NaN,None,None
4,ports,temporarily closed,Valencia and Sagunto ports,Stamataki 2023 - Greece’s record rainfall and ...,"{'damage': 'temporarily closed', 'geolocation'...",NaN,None,None
...,...,...,...,...,...,...,...,...
2083,motorways,closure,NAN,Kadir 2014 - The Impact of Natural Disasters o...,"{'damage': 'closure', 'geolocation': 'NAN'}",NaN,None,None
2084,NAN,NAN,NAN,Kadir 2014 - The Impact of Natural Disasters o...,"{'damage': 'NAN', 'geolocation': 'NAN'}",NaN,None,None
2085,NAN,NAN,NAN,Kadir 2014 - The Impact of Natural Disasters o...,"{'damage': 'NAN', 'geolocation': 'NAN'}",NaN,None,None
2086,motorways,closure,NAN,Kadir 2014 - The Impact of Natural Disasters o...,"{'damage': 'closure', 'geolocation': 'NAN'}",NaN,None,None
2087,62 bridges,destroyed,Ahr valley,Kadir 2014 - The Impact of Natural Disasters o...,"{'damage': 'destroyed', 'geolocation': 'Ahr va...",NaN,None,None