# AIM:
create evaluation workflow. Taking the manually extracted Ci impacts (validation set) and compare it with the CI impacts (llm_geolocations.ipynb) extrracted by the first LLM 1. 
As a first step the evaluation should be done only for the direct CI impacts - CI type, damage and geolocation

Issue:
* What is needed an approach that recognizes when an direct impact case is not detected by the model
Idea: 
* Split the original texts passed to the model on the exact chunks as again
* Then chunkwise check if the CI impacts from the validation set correspond in number and their textual similarity to the CI impacts infered by the LLM 1 and Entity Linking

## Semantic Textual Similarity (STS)

Calculating the STS for both model configurations (chain of prompts, orchestration of models)
The outputs are cosine similarity scores for similar model outputs per chunk. They are ranked by score for each model, restricted to the top 20 results.

In [1]:
import os
import sys
from pathlib import Path
import io
import gc
import time
import warnings
import subprocess
import importlib

from unidecode import unidecode
import langdetect
from fuzzywuzzy import fuzz
import torch
from huggingface_hub import login
import numpy as np
import spacy
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from matplotlib import pyplot as plt


sys.path.append('../')
from src.settings import settings as s
import src.document_cleaning as dc
import src.translation_model as tm
from src.utils import cosine_similarity, vector_calculation

#  automatic linebreaks and multi-line cells.
pd.set_option("display.colheader_justify", "left")
pd.set_option('display.max_colwidth', 5000)

# login to HF
os.environ['HUGGINGFACE_TOKEN']  
# NOTE raises exception if not env.variable doesnt exist (compared to os.envrion.get and its shortcut os.getenv)

/home/a-buch/Documents/TUB_DWN/_PROJECTS/CI-impacts-information-retrieval/.venv/lib/python3.12/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

Running on local machine

'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'

### Direct CI impacts: LLM 1 vs domain-expertise

In [2]:
#  Suppress future warnings from PyTorch
warnings.filterwarnings("ignore", category=FutureWarning)


#  Define data dir where tags.csv and domain-expertise derived tag lists are found 
VALID_DATA_FILENAME = s.VALID_DATA_FILENAME
PATH_VALID_DATA = s.PATH_VALID_DATA
PATH_EVAL_RESULT = s.PATH_EVAL_RESULT
LLM_DATA_FILEPATH = Path(s.PATH_LLM_DATA / s.LLM_DATA_FILENAME)
SIMILARITY_LLM_FILENAME = s.SIMILARITY_LLM_FILENAME

df_valid = pd.read_csv(
    PATH_VALID_DATA / VALID_DATA_FILENAME,
    usecols=["publication_id", "ci1_type", "ci1_damage", "ci1_location", "sentence_reference"]
)
print(len(df_valid))
## pre-process: 
# remove undone entries
df_valid = df_valid[~df_valid.astype(str).apply(lambda x: x.str.contains("xx")).any(axis=1)]
# remove further location info (e.g. that entry is a town, Landkreis, Bavaria etc.)
df_valid["ci1_location"] = df_valid["ci1_location"].replace(r"\s*\(.*\)", "", regex=True).str.strip()
df_valid = df_valid.dropna(subset=["publication_id"], how="all") # drop rows where citation info is missing
print(len(df_valid))


## prediction data
df_pred = pd.read_csv(
    LLM_DATA_FILEPATH,
    #usecols=["citation_id", "chunk_id", "infrastructure_type", "damage", "location", "chunk_text"]
)

df_pred

## citation alignment
# print(df_pred["citation_id"])
# df_pred["citation_id"] = df_pred["citation_id"].map(dc.extract_citation_info) # FIXME as used with new funct returning author, year, title
# df_pred["citation_id"] = df_pred["citation_id"].apply(dc.extract_citation_info)
# print(df_pred["citation_id"])

141
134

,citation_id,chunk_id,infrastructure_type,damage,location,ci_entity,geo_entity,case_type,chunk_text
0,Karakatsani 2023,0,roads,severely damaged,Thessaly plain,National roads,plain,NaN,"The economic impact of the recent devastating floods in Greece The economic impact of the recent devastating floods in Greece The briefing presents the economic impact of the damages caused by the storm “Daniel”. The floods caused by the heavy rainfall, especially in Thessaly plain -accounting for approximately 15% of Greece’s agricultural land- resulted to a massive destruction in agriculture, infrastructure and residences, which is expected to negatively affect the Greek economy in short and mid-term. Fears for food shortages and increase of product prices have been raised. In addition, increase of fiscal costs, imports and unemployment may also affect the economy in the upcoming years. The extent of the impact to the economy is not yet know. Before the country recovered from the wildfires of August and the consequent huge forest disaster, a weather stormy phenomenon named Daniel hit the country. Specifically, in the beginning of September, rainfall of unprecedented intensity fell mainly in central Greece and especially in Thessaly plain, causing floods throughout the territory. Thousands of acres of crops and livestock farms were destroyed. Properties and houses were lost under ton of waters. National roads were closed, bridges collapsed, and some parts of the railway network were highly damaged dividing the country in two. Evidently, the massive destruction of agricultural"
1,Karakatsani 2023,0,bridges,collapsed,central Greece,NaN,NaN,NaN,"The economic impact of the recent devastating floods in Greece The economic impact of the recent devastating floods in Greece The briefing presents the economic impact of the damages caused by the storm “Daniel”. The floods caused by the heavy rainfall, especially in Thessaly plain -accounting for approximately 15% of Greece’s agricultural land- resulted to a massive destruction in agriculture, infrastructure and residences, which is expected to negatively affect the Greek economy in short and mid-term. Fears for food shortages and increase of product prices have been raised. In addition, increase of fiscal costs, imports and unemployment may also affect the economy in the upcoming years. The extent of the impact to the economy is not yet know. Before the country recovered from the wildfires of August and the consequent huge forest disaster, a weather stormy phenomenon named Daniel hit the country. Specifically, in the beginning of September, rainfall of unprecedented intensity fell mainly in central Greece and especially in Thessaly plain, causing floods throughout the territory. Thousands of acres of crops and livestock farms were destroyed. Properties and houses were lost under ton of waters. National roads were closed, bridges collapsed, and some parts of the railway network were highly damaged dividing the country in two. Evidently, the massive destruction of agricultural"
2,Karakatsani 2023,0,railway,highly damaged,Thessaly plain,NaN,NaN,NaN,"The economic impact of the recent devastating floods in Greece The economic impact of the recent devastating floods in Greece The briefing presents the economic impact of the damages caused by the storm “Daniel”. The floods caused by the heavy rainfall, especially in Thessaly plain -accounting for approximately 15% of Greece’s agricultural land- resulted to a massive destruction in agriculture, infrastructure and residences, which is expected to negatively affect the Greek economy in short and mid-term. Fears for food shortages and increase of product prices have been raised. In addition, increase of fiscal costs, imports and unemployment may also affect the economy in the upcoming years. The extent of the impact to the economy is not yet know. Before the country recovered from the wildfires of August and the consequent huge forest disaster, a weather stormy phenomenon named Daniel hit the country. Specifically, in the beginning of September, rainfall of unprecedented intensity fell mainly in central Greece and especially in Thessaly plain, causing floods throughout the territory. Thousands of acres of crops and livestock farms were destroyed. Properties and houses were lost under ton of waters. National roads were closed, bridges collapsed, and some parts of the railway network were highly damaged dividing the country in two. Evidently, the massive destruction of agricultural"
3,Karakatsani 2023,0,ports,destroyed,Thessaly plain,NaN,NaN,NaN,"The economic impact of the recent devastating floods in Greece The economic impact of the recent devastating floods in Greece The briefing presents the economic impact of the damages caused by the storm “Daniel”. The floods caused by the heavy rainfall, especially in Thessaly plain -accounting for approximately 15% of Greece’s agricultural land- resulted to a massive destruction in agriculture, infrastructure and residences, which is expected to negatively affect the Greek economy in short and mid-term. Fears for food shortages and increase of product prices have been raised. In addition, increase of fiscal costs, imports and unemployment may also affect the economy in the upcoming years. The extent of the impact to the economy is not yet know. Before the country recovered from the wildfires of August and the consequent huge forest disaster, a weather stormy phenomenon named Daniel hit the country. Specifically, in the beginning of September, rainfall of unprecedented intensity fell mainly in central Greece and especially in Thessaly plain, causing floods throughout the territory. Thousands of acres of crops and livestock farms were destroyed. Properties and houses were lost under ton of waters. National roads were closed, bridges collapsed, and some parts of the railway network were highly damaged dividing the country in two. Evidently, the massive destruction of agricultural"
4,Karakatsani 2023,0,airports,disrupted,central Greece,NaN,NaN,NaN,"The economic impact of the recent devastating floods in Greece The economic impact of the recent devastating floods in Greece The briefing presents the economic impact of the damages caused by the storm “Daniel”. The floods caused by the heavy rainfall, especially in Thessaly plain -accounting for approximately 15% of Greece’s agricultural land- resulted to a massive destruction in agriculture, infrastructure and residences, which is expected to negatively affect the Greek economy in short and mid-term. Fears for food shortages and increase of product prices have been raised. In addition, increase of fiscal costs, imports and unemployment may also affect the economy in the upcoming years. The extent of the impact to the economy is not yet know. Before the country recovered from the wildfires of August and the consequent huge forest disaster, a weather stormy phenomenon named Daniel hit the country. Specifically, in the beginning of September, rainfall of unprecedented intensity fell mainly in central Greece and especially in Thessaly plain, causing floods throughout the territory. Thousands of acres of crops and livestock farms were destroyed. Properties and houses were lost under ton of waters. National roads were closed, bridges collapsed, and some parts of the railway network were highly damaged dividing the country in two. Evidently, the massive destruction of agricultural"
...,...,...,...,...,...,...,...,...,...
1630,Gilbody Dickerson 2024,10,healthcare facility,outages,elsewhere in Europe,NaN,NaN,NaN,"Both teams were due to play in the Copa del Rey on Wednesday night.Other midweek games could also be cancelled, along with Saturday'sleague match between Valencia and Madrid.Scientists have warned that increased episodes of extreme weather, likeflash floods, or the wildfires seen elsewhere in Europe in the summer, arelikely linked to human-driven climate change.Meteorologists believe the warming of the Mediterranean, whichincreases water evaporation, plays a key role in making torrential rainsmore severe.Related TopicsClimate ChangeExtreme WeatherSpainAbout Sky NewsAbout UsSky News ProfilesSky News DistributionSky News Library SalesSite MapEditorial GuidelinesSky News BoardSky News ServicesSky News RSSSky News For Your PhoneSky News RadioSky ChannelsSky WitnessSky AtlanticMore Sky SitesNOWSky Up Academy Studios 1/3/26, 10:51 PM © 2026 Sky UKSky ArtsSky CinemaSky SportsSky GroupSky BetSky.comSky News ArabiaAdvertise With UsTerms &amp; ConditionsPrivacy &amp; CookiesPrivacy OptionsAccessibilityContact Us"
1631,Gilbody Dickerson 2024,10,healthcare facility,heavily destroyed,elsewhere in Europe,NaN,NaN,NaN,"Both teams were due to play in the Copa del Rey on Wednesday night.Other midweek games could also be cancelled, along with Saturday'sleague match between Valencia and Madrid.Scientists have warned that increased episodes of extreme weather, likeflash floods, or the wildfires seen elsewhere in Europe in the summer, arelikely linked to human-driven climate change.Meteorologists believe the warming of the Mediterranean, whichincreases water evaporation, plays a key role in making torrential rainsmore severe.Related TopicsClimate ChangeExtreme WeatherSpainAbout Sky NewsAbout UsSky News ProfilesSky News DistributionSky News Library SalesSite MapEditorial GuidelinesSky News BoardSky News ServicesSky News RSSSky News For Your PhoneSky News RadioSky ChannelsSky WitnessSky AtlanticMore Sky SitesNOWSky Up Academy Studios 1/3/26, 10:51 PM © 2026 Sky UKSky ArtsSky CinemaSky SportsSky GroupSky BetSky.comSky News ArabiaAdvertise With UsTerms &amp; ConditionsPrivacy &amp; CookiesPrivacy OptionsAccessibilityContact Us"
1632,Gilbody Dickerson 2024,10,healthcare facility,severely damaged,elsewhere in Europe,NaN,NaN,NaN,"Both teams were due to play in the Copa del Rey on Wednesday night.Other midweek games could also be cancelled, along with Saturday'sleague match between Valencia and Madrid.Scientists have warned that increased episodes of extreme weather, likeflash floods, or the wildfires seen elsewhere in Europe in the summer, arelikely linked to human-driven climate change.Meteorologists believe the warming of the Mediterranean, whichincreases water evaporation, plays a key role in making torrential rainsmore severe.Related TopicsClimate ChangeExtreme WeatherSpainAbout Sky NewsAbout UsSky News ProfilesSky News DistributionSky News Library SalesSite MapEditorial GuidelinesSky News BoardSky News ServicesSky News RSSSky News For Your PhoneSky News RadioSky ChannelsSky WitnessSky AtlanticMore Sky SitesNOWSky Up Academy Studios 1/3/26, 10:51 PM © 2026 Sky UKSky ArtsSky CinemaSky SportsSky GroupSky BetSky.comSky News ArabiaAdvertise With UsTerms &amp; ConditionsPrivacy &amp; CookiesPrivacy OptionsAccessibilityContact Us"
1633,Gilbody Dickerson 2024,10,healthcare facility,disrupted,elsewhere in Europe,NaN,NaN,NaN,"Both teams were due to play in the Copa del Rey on Wednesday night.Other midweek games could also be cancelled, along with Saturday'sleague match between Valencia and Madrid.Scientists have warned that increased episodes of extreme weather, likeflash floods, or the wildfires seen elsewhere in Europe in the summer, arelikely linked to human-driven climate change.Meteorologists believe the warming of the Mediterranean, whichincreases water evaporation, plays a key role in making torrential rainsmore severe.Related TopicsClimate ChangeExtreme WeatherSpainAbout Sky NewsAbout UsSky News ProfilesSky News DistributionSky News Library SalesSite MapEditorial GuidelinesSky News BoardSky News ServicesSky News RSSSky News For Your PhoneSky News RadioSky ChannelsSky WitnessSky AtlanticMore Sky SitesNOWSky Up Academy Studios 1/3/26, 10:51 PM © 2026 Sky UKSky ArtsSky CinemaSky SportsSky GroupSky BetSky.comSky News ArabiaAdvertise With UsTerms &amp; ConditionsPrivacy &amp; CookiesPrivacy OptionsAccessibilityContact Us"
1634,Gilbody Dickerson 2024,10,healthcare facility,outages,elsewhere in Europe,NaN,NaN,NaN,"Both teams were due to play in the Copa del Rey on Wednesday night.Other midweek games could also be cancelled, along with Saturday'sleague match between Valencia and Madrid.Scientists have warned that increased episodes of extreme weather, likeflash floods, or the wildfires seen elsewhere in Europe in the summer, arelikely linked to human-driven climate change.Meteorologists believe the warming of the Mediterranean, whichincreases water evaporation, plays a key role in making torrential rainsmore severe.Related TopicsClimate ChangeExtreme WeatherSpainAbout Sky NewsAbout UsSky News ProfilesSky News DistributionSky News Library SalesSite MapEditorial GuidelinesSky News BoardSky News ServicesSky News RSSSky News For Your PhoneSky News RadioSky ChannelsSky WitnessSky AtlanticMore Sky SitesNOWSky Up Academy Studios 1/3/26, 10:51 PM © 2026 Sky UKSky ArtsSky CinemaSky SportsSky GroupSky BetSky.comSky News ArabiaAdvertise With UsTerms &amp; ConditionsPrivacy &amp; CookiesPrivacy OptionsAccessibilityContact Us"

#### AS FUNC: Evaluate on same documents that were passed to LLM

In [3]:
#  TODO make as global var

PARSED_TEXT_DIR = Path(s.PATH_DATA / "parsed_documents/")

docs_list_sample = [
        Path(PARSED_TEXT_DIR, "Karakatsani 2023 - Greece economy briefing The economic impact of the recent devastating floods in Greece_cleaned.md"),
        Path(PARSED_TEXT_DIR, "Lloyd's List 2024 - Port of Valencia reopens after devastating floods_cleaned.md"),
        Path(PARSED_TEXT_DIR, "Containerlift 2024 - Valencia Port Resumes Operations Following Devastating Flooding in Spain - Containerlift.co.uk - Transport_Lifting_Shipping_cleaned.md"), 
        Path(PARSED_TEXT_DIR, "ABC 2024 - Traffic jams and flight delays due to heavy rain and lightning storm in Malaga_cleaned.md"),
        Path(PARSED_TEXT_DIR, "Koks 2022 - Brief communication_cleaned.md"),
        Path(PARSED_TEXT_DIR, "European Investment Bank 2025 - Spain_ EIB lends €50 million to Iberdrola to rebuild and climate-proof flood-hit power infrastructure in Valencia_cleaned.md"),
        Path(PARSED_TEXT_DIR, "Wilson 2024 - Flash floods in Spain sweep away cars, disrupt trains and leave several missing _ AP News_cleaned.md"),     
        Path(PARSED_TEXT_DIR, "Wildhagen 2013 - Hochwasser_ Wie die Flut Unternehmen lahmlegt_cleaned.md"),

        Path(PARSED_TEXT_DIR, "ABC 2024 - Traffic jams and flight delays due to heavy rain and lightning storm in Malaga_cleaned.md"),
        Path(PARSED_TEXT_DIR, "EFE 2024 - The DANA storm, live_ The death toll rises to 158_cleaned.md"),
        Path(PARSED_TEXT_DIR, "Ferlita 2023 - Incendi in Sicilia, ecco cosa accade_cleaned.md"),
        Path(PARSED_TEXT_DIR, "Gilbody Dickerson 2024 - Spain floods_ At least 95 people killed including British man near Malaga _ World News _ Sky News_cleaned.md"),

]

In [4]:
citation_list = []

for i in docs_list_sample:
    a, y, t = dc.extract_citation_info(i.name)
    citation_list.append(a + y)

df_valid = df_valid[df_valid["publication_id"].isin(citation_list)]

In [5]:
df_pred[~df_pred["ci_entity"].isna()]

,citation_id,chunk_id,infrastructure_type,damage,location,ci_entity,geo_entity,case_type,chunk_text
0,Karakatsani 2023,0,roads,severely damaged,Thessaly plain,National roads,plain,NaN,"The economic impact of the recent devastating floods in Greece The economic impact of the recent devastating floods in Greece The briefing presents the economic impact of the damages caused by the storm “Daniel”. The floods caused by the heavy rainfall, especially in Thessaly plain -accounting for approximately 15% of Greece’s agricultural land- resulted to a massive destruction in agriculture, infrastructure and residences, which is expected to negatively affect the Greek economy in short and mid-term. Fears for food shortages and increase of product prices have been raised. In addition, increase of fiscal costs, imports and unemployment may also affect the economy in the upcoming years. The extent of the impact to the economy is not yet know. Before the country recovered from the wildfires of August and the consequent huge forest disaster, a weather stormy phenomenon named Daniel hit the country. Specifically, in the beginning of September, rainfall of unprecedented intensity fell mainly in central Greece and especially in Thessaly plain, causing floods throughout the territory. Thousands of acres of crops and livestock farms were destroyed. Properties and houses were lost under ton of waters. National roads were closed, bridges collapsed, and some parts of the railway network were highly damaged dividing the country in two. Evidently, the massive destruction of agricultural"
44,Karakatsani 2023,3,railway,partially destroyed,Thessaly plain,National highway,Thessaly plain,NaN,"water. Thus, the heartland of Greek agriculture is in a great extend destroyed and experts warn that the destruction of crops and soil quality will take years to recover. It is worth noting that a quarter of the country’s wheat and barley, 30 percent of cotton, a third of chickpeas, pistachios and lentils, a fifth of the hay used in livestock farming and half of the industrial tomato production was grown in Thessaly plain. Thus, it is expected that the massive destruction may result in shortages as well as increase in product prices (5). Furthermore, the storm resulted to the partial destruction of main roads, such as the National highway. The railway network has also been destroyed in some parts. According to the Minister of Infrastructure and Transportation, Christos Staikouras, the cost for repairing the damages in the railways will exceed 150 mil euros (6). The financial cost and the impact to the Greek economy From the above it is evident that the financial cost of repairing the damages brought by the storm “Daniel” is extremely high. According to government sources initially the cost of the damages in Thessaly was estimated approximately around 1.5 bil euros. However, new"
45,Karakatsani 2023,3,highway,heavily damaged,Thessaly plain,The railway network,Thessaly plain,NaN,"water. Thus, the heartland of Greek agriculture is in a great extend destroyed and experts warn that the destruction of crops and soil quality will take years to recover. It is worth noting that a quarter of the country’s wheat and barley, 30 percent of cotton, a third of chickpeas, pistachios and lentils, a fifth of the hay used in livestock farming and half of the industrial tomato production was grown in Thessaly plain. Thus, it is expected that the massive destruction may result in shortages as well as increase in product prices (5). Furthermore, the storm resulted to the partial destruction of main roads, such as the National highway. The railway network has also been destroyed in some parts. According to the Minister of Infrastructure and Transportation, Christos Staikouras, the cost for repairing the damages in the railways will exceed 150 mil euros (6). The financial cost and the impact to the Greek economy From the above it is evident that the financial cost of repairing the damages brought by the storm “Daniel” is extremely high. According to government sources initially the cost of the damages in Thessaly was estimated approximately around 1.5 bil euros. However, new"
84,Karakatsani 2023,6,broadband,outages,Thessaly,the roadshow,Athens,NaN,"economic consequences of the floods in the Greek economy. According to the conclusions of the roadshow organized by HSBC in Athens on the 11-13 September, international investors consider the fiscal cost of the floods to be manageable, with economic growth remaining consistently strong, while high interest rates have so far not much been negatively affected. The target of primary surplus of 0.7% of GDP this year is expected to be achieved, given the budget’s outperformance up to now, as well as the 2.5 bil euros EU’s economic support to the country (9). According to Nikos Vettas, the General Director of the Foundation for Economic and Industrial Research (IOBE) the economic consequences of the floods may paradoxically not directly impact the economy at all. He argues that when a forest burns or a house floods, GDP does not automatically decrease, while on the contrary government spending on restoring the damages can increase GDP. However, he stressed that on the long run the economy will be negatively affected from natural disasters such as floods and fires, as capital and natural resources have been destroyed and will take years or ever to return to the level they were before The damages caused by the recent floods and especially the destruction of the Thessaly"
168,Lloyd's List 2024,0,harbor,severely damaged,Valencia,Spain’s second-biggest port,VALENCIA,NaN,"Port of Valencia reopens after devastating ﬂoods :: Lloyd's List Take Lloyd's List on the go. 🌍 Access trusted maritime insights anytime, anywhere. 👉 We use cookies to improve your website experience. To learn about our use of cookies and how you can manage your cookie settings, please see our Cookie Policy. By continuing to use the website, you consent to our use of cookies. This copy is for your personal, non-commercial use. For high-quality copies or electronic reprints for distribution to colleagues or customers, please call UK support at +44 (0)20 3377 3996 / The port’s three terminals reopened this morning after being closed following flooding in the region Spain’s second-biggest port was forced to halt container operations after a year’s worth of rain fell in just eight hours, causing devastating floods in the region that have killed more than 200 so far THE MSC TERMINAL VALENCIA (PICTURED), OPENED AT 0800 HRS WEDNESDAY AND WILL REMAIN VALENCIA’S three container terminals resumed operations this morning, after devastating floods in the region had disrupted traffic at Spain’s second-biggest port. Cosco Shipping Ports Terminal, MSC Terminal Valencia and the APMT terminal have now all reopened"
...,...,...,...,...,...,...,...,...,...
1395,Ferlita 2023,3,railway,heavily destroyed,Railway network,the airport,Catania,NaN,"monetary, the damage is enormous: the National Civil Aviation Authority estimates an overall investment for plants and maintenance of about 200 thousand euros. The Mec (Customer electoral movement), instead, estimates an expenditure of about 40 million of euro per day due to the closure of the port of call due to the fire. The total of damages, would amount to more than 80 million euros. The fire took place last Sunday night at the airport Vincenzo Bellini in Catania and, after two days of incessant work for the shutdown of the fire, from the terminal C are resumed arrivals and departures. Meanwhile, they enter into also action the men of the Nia(Nucleo fire investigation) to establish the causes of the fire even if it is assumed a Short circuit that occurred in the air conditioning system. The runway of the arson fire is not excluded. Fires in Sicily, that's what happens -The Editorial Board 16 December 2025 Yemen, the war and the spectators concerned 15 December 2025 Dialogue with two young Israeli conscientious objectors 11 December 2025 Trump's geopolitics: raw materials, not ideal 4 December 2025 Pope Leo XIV, after Turkey and Lebanon, will go to Algeria"
1396,Ferlita 2023,3,power,severely damaged,Power grid,Vincenzo Bellini,Catania,NaN,"monetary, the damage is enormous: the National Civil Aviation Authority estimates an overall investment for plants and maintenance of about 200 thousand euros. The Mec (Customer electoral movement), instead, estimates an expenditure of about 40 million of euro per day due to the closure of the port of call due to the fire. The total of damages, would amount to more than 80 million euros. The fire took place last Sunday night at the airport Vincenzo Bellini in Catania and, after two days of incessant work for the shutdown of the fire, from the terminal C are resumed arrivals and departures. Meanwhile, they enter into also action the men of the Nia(Nucleo fire investigation) to establish the causes of the fire even if it is assumed a Short circuit that occurred in the air conditioning system. The runway of the arson fire is not excluded. Fires in Sicily, that's what happens -The Editorial Board 16 December 2025 Yemen, the war and the spectators concerned 15 December 2025 Dialogue with two young Israeli conscientious objectors 11 December 2025 Trump's geopolitics: raw materials, not ideal 4 December 2025 Pope Leo XIV, after Turkey and Lebanon, will go to Algeria"
1560,Gilbody Dickerson 2024,5,roads,severely damaged,Utiel,Spain's emergency response units,ofUtiel,NaN,"Cars piled up after being swept away by floods. Pic: APA watermark on a wall shows how high floodwatersreached in Letur. Pic: Reuters 1/3/26, 10:51 PM 'Trapped like rats'Radio and TV stations received hundreds of calls for help from peopletrapped or searching for loved ones, as emergency services were unableto reach all locations.More than 1,000 soldiers from Spain's emergency response units havebeen deployed to help.""Yesterday was the worst day of my life,"" Ricardo Gabaldon, the mayor ofUtiel, a town in Valencia, told national broadcaster RTVE. He said severalpeople were still missing in his town.Firefighters rescue drivers from floods""We were trapped like rats,"" Mr Gabaldon said. ""Cars and trash containerswere flowing down the streets. The water was rising to three metres.""0:16 1/3/26, 10:51 PM"
1567,Gilbody Dickerson 2024,6,motorway,highly damaged,Letur,a motorway,Valencia,NaN,"While the rain subsided in Valencia by late Wednesday morning, stormswere forecast to continue on Thursday, according to Spain's nationalweather service.'It was mayhem'A British couple told Sky News they had been stuck in their car for almost10 hours.Vitalij Farafonov and his wife were visiting Valencia on a yoga retreat whenthey were diverted by police from a motorway at around 8pm last night.He said: ""It was mayhem as we counted nine or 10 overturned lorries on ahalf mile stretch of the motorway.""We've never seen anything like it.""Emergency workers help a woman in Letur. Pic: EuropaPress via AP 1/3/26, 10:51 PM"
1571,Gilbody Dickerson 2024,7,metro,disrupted,Barcelona,a random rural road,the Midlands,NaN,"This was the scene following floods in Llombai, Valencia.Pic: ReutersMr Farafonov said he and his wife were stuck ""on a random rural road inbetween what were beautiful orange groves"".""We can finally see flashing blue lights so people do know where we are,""he added. ""As I say, we are the lucky ones.""The couple, who are originally from the Midlands but now live inLuxembourg, have four children who are safe in Barcelona with relatives. 1/3/26, 10:51 PM Cars are swept away by the water in Alora. Pic: APA helicopter rescue is carried out in Alora. Pic: AP'Half a year's rain' 1/3/26, 10:51 PM"

In [6]:
df_pred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1635 entries, 0 to 1634
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   citation_id          1635 non-null   object
 1   chunk_id             1635 non-null   int64
 2   infrastructure_type  1635 non-null   object
 3   damage               1635 non-null   object
 4   location             1635 non-null   object
 5   ci_entity            84 non-null     object
 6   geo_entity           84 non-null     object
 7   case_type            0 non-null      float64
 8   chunk_text           1635 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 115.1+ KB

In [7]:
df_pred.loc[df_pred["citation_id"]== "Krausmann 2014"] # Krausmann -> large hallucinations when chunk-text is title or contact info (i.e when not about CI /impacts)

Empty DataFrame
Columns: [citation_id, chunk_id, infrastructure_type, damage, location, ci_entity, geo_entity, case_type, chunk_text]
Index: []

#### As FUNC. postprocess -make CI gsubgroups

###### Improve similarity calculation
As all similarity measures - no matter which embedding model or kind of cosine similarity measure were not sufficient eg. port ~ power to similar to port~harbor

Thus, it might be better to first group ci impacts into subgroups e.g .based on HARCI-EU categories,as some kind of postprocessing step before applying the similarity measurements

In [8]:
ci_patterns = pd.read_json("./ner_patterns.jsonl/patterns", lines=True)

In [9]:
import re

# load regular expressions and subgroups from NER patterns as dict
# for general cases and all special cases with "LOWER"-pattern
regexes_1 = [
        {ci_patterns["pattern"][i][0]["TEXT"]["REGEX"] : ci_patterns["subgroup_name"][i]}
          for i in range(len(ci_patterns)) 
            if len(ci_patterns["pattern"][i])==1 
]
regexes_2 = [
    {ci_patterns["pattern"][i][0]["TEXT"]["REGEX"] + " " + ci_patterns["pattern"][i][1]["LOWER"] : ci_patterns["subgroup_name"][i] }
      for i in range(len(ci_patterns))
        if len(ci_patterns["pattern"][i])==2
]
regexes = regexes_1 + regexes_2

In [10]:
for i, r in enumerate(regexes):

    # get regex pattern for CI type (key) and its subgroup (value)
    # NOTE, nice shortcut: get key containing regex by unpacking each dict into list, then get key
    pattern = [*r][0]
    subgroup = r[pattern]

    # assign subgroups to CI records, na=False to remove all records which not match patterns
    mask = df_pred["infrastructure_type"].str.contains(pattern, regex=True, na=False)
    df_pred.loc[mask, "infrastructure_group"] = subgroup
df_pred
    # assign subgroups to CI records, na=False to remove all records which not match patterns
    mask = df_valid["ci1_type"].str.contains(pattern, regex=True, na=False)
    df_valid.loc[mask, "ci1_group"] = subgroup
    
df_pred

print(df_pred.infrastructure_group.isna().sum())
print(df_pred.infrastructure_group.value_counts())
# df_pred.infrastructure_group.unique()

print(df_valid.ci1_group.isna().sum())
print(df_valid.ci1_group.value_counts())
# df_pred.infrastructure_group.unique()

IndentationError: unexpected indent (2566967784.py, line 13)

In [ ]:
print("Removing all records which have another or erroneous CI entry")

df_pred = df_pred[~df_pred.infrastructure_group.isna()]
df_valid = df_valid[~df_valid.ci1_group.isna()]

Removing all records which have another or erroneous CI entry

#### Load spaCy language model

In [ ]:
## load english model with word vectors included

print(f"Try loading spaCy language model ({s.SPACY_MODEL}) for remote instance (e.g., cluster)")
try: 
    nlp = spacy.load(s.SPACY_MODEL)
except (OSError, ValueError):
    print(f"spaCy language model '{s.SPACY_MODEL}' not found. Downloading ...")
    subprocess.check_call(["uv", "pip", "install", "spacy-transformers"])
    subprocess.check_call(["uv", "run", "python", "-m", "spacy", "download", s.SPACY_MODEL])
    nlp = spacy.load(s.SPACY_MODEL)

# NOTE: en_core_web_lg can only return word vectors, while en_core_web_trf return contextual vectors (as transformer-based)

# !uv run python -m spacy download en_core_web_lg
# nlp = spacy.load("en_core_web_lg")

Try loading spaCy language model (en_core_web_trf) for remote instance (e.g., cluster)

In [ ]:
# ## unify citation column

# # get corresponding document from df_vald
# citation_pattern = r"(.*?)(\d{4})(.*)" # split at first occurrence of year
# # df_pred["publication_id"] = df_pred["citation"].map(dc.extract_citation_info)
# df_pred["citation"].map(dc.extract_citation_info)
# # df_pred = df_pred.rename({"citation": "publiation_id"})
# # df_pred.drop("citation", inplace=True)
# df_pred
# # try:
# #     authors, year, _ = re.findall(citation_pattern, filename)[0]
# #     citation = f"{authors} {year}"

#### Select records which have text references

In [ ]:

print(len(df_pred), len(df_valid))
df_pred = df_pred[~df_pred["chunk_text"].isna()].reset_index(drop=True)
df_valid = df_valid[~df_valid["sentence_reference"].isna()].reset_index(drop=True)
print(len(df_pred), len(df_valid))

1112 66
1112 66

#### Translation of validation sentences

In [ ]:

for entry in df_valid.itertuples():
    
    src_language = langdetect.detect(str(entry.sentence_reference))
    
    if src_language != "en":
        supported_languages = ["fr", "de", "es", "it", "itc", "nl"]
        if src_language not in supported_languages:
            print(f"Unsupported source language: {src_language}. Continue with original version of the sentence in validation set ")
            continue 

        print(f"\n ######## -------- Translating {entry.publication_id}: {src_language} --> en -------- ######## \n")

        # # clean up before applying translator
        # gc.collect()
        # torch.cuda.empty_cache()  # mainly after training needed, small effect when LLM applied only for inference
        # torch.no_grad()
        
        # overwrite original sentence(s) with translated versions
        translated_sentence = tm.translate_2_english(src_language, str(entry.sentence_reference))
        df_valid.loc[df_valid.index[df_valid["sentence_reference"] == entry.sentence_reference], "sentence_reference"] = translated_sentence

 ######## -------- Translating Ferlita 2023: it --> en -------- ########

/home/a-buch/Documents/TUB_DWN/_PROJECTS/CI-impacts-information-retrieval/notebooks/huggingface_mirror/hub
Using device: cuda
Using locally saved model from /home/a-buch/Documents/TUB_DWN/_PROJECTS/CI-impacts-information-retrieval/notebooks/huggingface_mirror/hub

AcceleratorError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

#### Postprocess (text cleaning)

In [ ]:
# unicode to ascii representation

for col in ["infrastructure_type", "damage", "ci_entity", "geo_entity"]:
    df_pred[col] = df_pred[col].apply(lambda x: unidecode(x) if isinstance(x, str) else x) # hanlde potential np.nan


for col in ["ci1_type", "ci1_damage", "ci1_location"]:
    df_valid[col] = df_valid[col].apply(lambda x: unidecode(x) if isinstance(x, str) else x) # hanlde potential np.nan

#### Merge prediction entries with potential validation entries (nth:1 pairs)

In [ ]:
print("Match chunk text of each prediction entry with related validation entries (nth:1 pairs)") # getting nth:1 pairs

df_pred_valid_all = pd.DataFrame()
threshold = 75

# find for each prediction entry all validation entries for respective chunk 
# these validation entries are candidates from which the most similar one to the pred. entry is taken to calc. model performance (e.g. recall) 
# including also entries where pred_info or valid_info is missing (e.g FNs, FPs)
for _, pred_entry in df_pred.iterrows():
    for _, valid_entry in df_valid.iterrows():  # all validation entries of all docs

        if valid_entry.sentence_reference is np.nan:
            continue

        # Calculate match score by accounting for partial string matches. 
        # In detail, it calculates the similarity ratio using the shortest string (length n, here: "sentence_reference") against all n-length substrings of the larger string and returns the highest score 
        score = fuzz.partial_ratio(valid_entry['sentence_reference'], pred_entry['chunk_text'])

        if score >= threshold:
            entry_pred_valid = {
                "citation_id": pred_entry["citation_id"],
                "ci_pred": pred_entry["infrastructure_type"],
                "damage_pred": pred_entry["damage"],
                "location_pred": pred_entry["location"],
                "chunk_id_pred": pred_entry["chunk_id"],
                "chunk_text_pred": pred_entry["chunk_text"],
                "ci_valid": valid_entry["ci1_type"],
                "damage_valid": valid_entry["ci1_damage"],
                "location_valid": valid_entry["ci1_location"],
                "sentence_text_valid": valid_entry["sentence_reference"],
                "text_similarity": score
            }
            df_pred_valid_all = pd.concat([df_pred_valid_all, pd.DataFrame([entry_pred_valid])], ignore_index=True)  # n:1 relationship DF
        

# 85 threshold - 778 entries
# 75 threshold - 778 entries

Match chunk text of each prediction entry with related validation entries (nth:1 pairs)

In [ ]:
df_pred_valid_all.info() # 143 -190 entries

## --> FPs are more common compared to FNs, especially for predicting locations, 
# as it is easier to get a prep-valid match when pred.info is actually missing due to larger chunk-text (pred set) compared to sentence-text (valid set)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 775 entries, 0 to 774
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   citation_id          775 non-null    object
 1   ci_pred              775 non-null    object
 2   damage_pred          775 non-null    object
 3   location_pred        775 non-null    object
 4   chunk_id_pred        775 non-null    int64
 5   chunk_text_pred      775 non-null    object
 6   ci_valid             760 non-null    object
 7   damage_valid         670 non-null    object
 8   location_valid       660 non-null    object
 9   sentence_text_valid  775 non-null    object
 10  text_similarity      775 non-null    int64
dtypes: int64(2), object(9)
memory usage: 66.7+ KB

In [ ]:
## entries with lowest similarity
df_pred_valid_all.text_similarity.describe()
# df_pred_valid_all.iloc[df_pred_valid_all.text_similarity.sort_values(ascending=True).index] [["sentence_text_valid", "chunk_text_pred","text_similarity"]]

count    775.000000
mean      99.664516
std        1.346243
min       87.000000
25%      100.000000
50%      100.000000
75%      100.000000
max      100.000000
Name: text_similarity, dtype: float64

#### Calc similarities for all cases where text info in pred and valid set exists

In [ ]:

# ## TODO test to prevent CUDA-OOM when reused
# ## Source: https://spacy.io/usage/embeddings-transformers
# from thinc.api import set_gpu_allocator, require_gpu

# # Use the GPU, with memory allocations directed via PyTorch.
# # This prevents out-of-memory errors that would otherwise occur from competing
# # memory pools.
# set_gpu_allocator("pytorch")
# require_gpu(0)

In [ ]:
columns_valid = ["damage_valid", "location_valid"]
columns_pred = ["damage_pred", "location_pred"]


#  Set similarity threshold (self-defined) when CI case is valid or not FN/FP
similarity_threshold = 0.7


print(" --- For each unique valid case (unique combi: [ci_valid, damage_valid, location_valid, sentence_text]) calculate similarity ---")
print("Using as cosine similarity threshold:", similarity_threshold)

## AIM of evaluation loop below: 
# remove all cases in df_pred_valid_all where pred_entities were wrongly assigned to a valid_entity
## ie keep only pre-valid pairs with highest similarity per unique valid case

# for each impact type (ci, damage, location) assess LLM performance
for column_valid, column_pred in zip(columns_valid, columns_pred):

    df_smltry_all = pd.DataFrame()

    print(f"\n --------- Calculate similarities for entries in column pair: {column_pred} - {column_valid} ------------")


    ## calculate similarities
    for _, entry in df_pred_valid_all.iterrows():

        ## calc similarity when both pred_info and valid_info exist (ie. not NaN)
        if entry[column_pred] and entry[column_valid] is not np.nan:
            pred_impact = entry[column_pred]
            valid_impact = entry[column_valid]

            ## Cosine similarity calc.
            # contextual vectors (transformer-based)
            embedded_list = vector_calculation(pred_impact, valid_impact)
            # calculate cosine similarity for each pred-valid pair
            similarity_score_cos = cosine_similarity(embedded_list[0], embedded_list[1])  # 0-1 value, the higher the more similar

            ## Partial ratio similarity calc. (especially for locations and CI-type  "port infrastructure" <-> "port")
            similarity_score_pr = fuzz.partial_ratio(pred_impact, valid_impact)  


            # store results
            dict_pair = {
                "impact_valid": valid_impact, 
                "impact_pred": pred_impact, 
                "impact_cos_sim": np.round(similarity_score_cos, 2),
                "impact_pr_sim": similarity_score_pr,
                "tp_tn_fp_fn": "tp_tn",
                "citation": entry.citation_id,
                "chunk_text_pred": entry.chunk_text_pred,
                "sentence_text_valid": entry.sentence_text_valid,
                "identifier_valid": f"{entry.ci_valid}_{entry.damage_valid}_{entry.location_valid}", 
                }
            df_smltry_all = pd.concat([df_smltry_all, pd.DataFrame([dict_pair])], ignore_index=True)


    # when no similarity could be calculated
    entries_with_no_similarity = df_smltry_all.loc[df_smltry_all["impact_cos_sim"].isna()]
    print(f" --- Pred-valid pairs where no cos. similarity score could be calculated: {len(entries_with_no_similarity)} ----")
    print(entries_with_no_similarity[["impact_valid", "impact_pred", "impact_cos_sim", "impact_pr_sim", "citation"]])

    print("for each unique valid_cols keep only pred-valid pairs of highest similarity")
    try:
        df_smltry_selmax = df_smltry_all.groupby("identifier_valid").apply(lambda x: x.loc[x["impact_cos_sim"].idxmax()])
    except KeyError:
        print("Removing entries with missing similarity scores")
        df_smltry_selmax = df_smltry_selmax.dropna(subset=["impact_cos_sim"])
        df_smltry_selmax = df_smltry_selmax.groupby("identifier_valid").apply(lambda x: x.loc[x["impact_cos_sim"].idxmax()])
    

    print("calculate performance measures:")

    # TPs 
    tps = df_smltry_selmax.loc[df_smltry_selmax["impact_cos_sim"] >= similarity_threshold]
    
    # FPs - model predicts condition wrongly (ie. predict condition when it is actually absent)
    # get all valid. documents which were also used for LLM inference
    df_valid_pred_same_docs = df_valid[df_valid["publication_id"].isin(df_pred["citation_id"])]
    print(f"Doing evaluation based on {df_valid_pred_same_docs.publication_id.unique().__len__()} existing in both (valid.+pred. set)")
    # get records where model predicted presence of impacts but they actually does not exist
    fps = df_smltry_selmax.loc[df_smltry_selmax["impact_cos_sim"] < similarity_threshold]

    # FNs - CI impact cases not detected by model 
    # NOTE: maybe FNs number is biased as wrong matches more likely as chunk-text (pred set) is longer than sentence text (valid set)
    # get all entries from df_valid_pred_same_docs where corresponding pred_record (in FPs) is missing

    # get all documents in valid_set which does not occur in pred_set or where similarity is too low
    df_valid_pred_missed_docs = df_valid[~df_valid["publication_id"].isin(df_pred["citation_id"])]
    df_valid_pred_low_sim = df_valid_pred_same_docs.loc[~df_valid_pred_same_docs["ci1_location"].isin(fps["impact_valid"])]
    fns = pd.concat([df_valid_pred_missed_docs, df_valid_pred_low_sim], ignore_index=True, axis=0)

    # performance scores
    recall_score = len(tps) / (len(tps) + len(fns))
    precision_score = len(tps) / (len(tps) + len(fps))
    f1_score = 2 * (precision_score * recall_score) / (precision_score + recall_score)


    print(f" ---------- Evaluation statistics: {column_pred}-----------")
    print(f"Recall: {recall_score}, Precision: {precision_score}, F1-score: {f1_score}")


    SIMILARITY_FILENAME = f"{column_pred.replace('_pred', '')}_{SIMILARITY_LLM_FILENAME}"
    SIMILARITY_FILEPATH = Path(PATH_EVAL_RESULT / SIMILARITY_FILENAME)


    print("Saving evaluation statistics, distribution plots, and scores to ", SIMILARITY_FILEPATH.stem, "[.parquet, _stats.json]")
    
    with open(SIMILARITY_FILEPATH, "w") as f:

        # results similarity df (with highest similarity per each valid_identifier) [csv, parquet]
        df_smltry_selmax.to_csv(SIMILARITY_FILEPATH.with_suffix('.csv'), index=False)
        df_smltry_selmax_pyarrow = pa.Table.from_pandas(df_smltry_selmax.astype( dtype="string[pyarrow]"))
        pq.write_table(df_smltry_selmax_pyarrow, SIMILARITY_FILEPATH.with_suffix(".parquet"))

        # results similarity all (all cases where valid_records was used multiple times to calc similairty to preds
        df_smltry_all.to_csv(SIMILARITY_FILEPATH.parent / f"{SIMILARITY_FILEPATH.stem}_allmatches.csv", index=False) 

        # summary statistics
        df_smltry_selmax_stats = pd.DataFrame(
            [{"recall": np.round(recall_score, 2), "precision": np.round(precision_score, 2), "f1_score": np.round(f1_score, 2)}]
        )
        f = SIMILARITY_FILEPATH.parent / f"{SIMILARITY_FILEPATH.stem}_stats.json"  
        df_smltry_selmax_stats.to_json(f, indent=4)
        
        # distribution plots
        df_smltry_selmax.impact_cos_sim.hist(bins=100)
        plt.savefig(SIMILARITY_FILEPATH.parent / f"{SIMILARITY_FILEPATH.stem}_hist.png")
        plt.close()

        df_smltry_all.impact_cos_sim.hist(bins=100)
        plt.savefig(SIMILARITY_FILEPATH.parent / f"{SIMILARITY_FILEPATH.stem}_allmatches_hist.png")
        plt.close()

 --- For each unique valid case (unique combi: [ci_valid, damage_valid, location_valid, sentence_text]) calculate similarity ---
Using as cosine similarity threshold: 0.7

 --------- Calculate similarities for entries in column pair: damage_pred - damage_valid ------------

 --- Pred-valid pairs where no cos. similarity score could be calculated: 0 ----
Empty DataFrame
Columns: [impact_valid, impact_pred, impact_cos_sim, impact_pr_sim, citation]
Index: []
for each unique valid_cols keep only pred-valid pairs of highest similarity
calculate performance measures:
Doing evaluation based on 10 existing in both (valid.+pred. set)
 ---------- Evaluation statistics: damage_pred-----------
Recall: 0.22330097087378642, Precision: 0.4107142857142857, F1-score: 0.2893081761006289
Saving evaluation statistics, distribution plots, and scores to  damage_smlrty_llm_1_updprompt_distanceNER [.parquet, _stats.json]

 --------- Calculate similarities for entries in column pair: location_pred - location_valid ------------
 --- Pred-valid pairs where no cos. similarity score could be calculated: 0 ----
Empty DataFrame
Columns: [impact_valid, impact_pred, impact_cos_sim, impact_pr_sim, citation]
Index: []
for each unique valid_cols keep only pred-valid pairs of highest similarity
calculate performance measures:
Doing evaluation based on 10 existing in both (valid.+pred. set)
 ---------- Evaluation statistics: location_pred-----------
Recall: 0.38666666666666666, Precision: 0.5576923076923077, F1-score: 0.45669291338582674
Saving evaluation statistics, distribution plots, and scores to  location_smlrty_llm_1_updprompt_distanceNER [.parquet, _stats.json]

# Improve similarity calculation
As all similarity measures - nomatter which emebdding model or kind of cosine similarity measure) were not sufficient eg. port ~ power to similar to port~harbor

Thus, it might be better to first group ci impacts into subgroups e.g .based on HARCI-EU categories,as some kind of postprocessing step before applying the similarity measurements

In [ ]:
dd = pd.read_json("./ner_patterns.jsonl/patterns", lines=True)
dd

,label,pattern,subgroup_name,subgroup_name_note
0,CI_TYPE,[{'TEXT': {'REGEX': '.*[Rr]oad.*?'}}],road_others,unsure -if whitespace at beginning correct
1,CI_TYPE,[{'TEXT': {'REGEX': '.*[Aa]ccess road.*?'}}],road_others,NaN
2,CI_TYPE,[{'TEXT': {'REGEX': '.*[Hh]ighway.*'}}],motorways,NaN
3,CI_TYPE,[{'TEXT': {'REGEX': '.*[Mm]otorway.*'}}],motorways,NaN
4,CI_TYPE,[{'TEXT': {'REGEX': '.*[Rr]ail.*'}}],rail,NaN
...,...,...,...,...
97,CI_TYPE,[{'TEXT': {'REGEX': '.*[Mm]edical.*'}}],healthcare_others,NaN
98,CI_TYPE,[{'TEXT': {'REGEX': '.*[Cc]linic.*'}}],healthcare_hospitals_clinics,NaN
99,CI_TYPE,[{'TEXT': {'REGEX': '.*[Hh]ospital.*'}}],healthcare_hospitals_clinics,NaN
100,CI_TYPE,[{'TEXT': {'REGEX': '.*[Ee]mergency.*'}}],healthcare_hospitals_clinics,NaN
101,CI_TYPE,[{'TEXT': {'REGEX': '.*[Ee]mergency.* services'}}],healthcare_hospitals_clinics,NaN

In [ ]:
d = {"label":"CI_TYPE","pattern": [{"TEXT": {"REGEX": ".* [Tt]ransport.*"}}, {"LOWER": "sector"}], "subgroup_name":"transport_others"}
#d["pattern"][0]["TEXT"]["REGEX"] + " " + dd["pattern"][1]["LOWER"]
d["subgroup_name"]

'transport_others'

In [ ]:
import re

# load regular expressions and subgroups from NER patterns as dict
# for general cases and all special cases with "LOWER"-pattern
regexes_1 = [
        {dd["pattern"][i][0]["TEXT"]["REGEX"] : dd["subgroup_name"][i]}
          for i in range(len(dd)) 
            if len(dd["pattern"][i])==1 
]
regexes_2 = [
    {dd["pattern"][i][0]["TEXT"]["REGEX"] + " " + dd["pattern"][i][1]["LOWER"] : dd["subgroup_name"][i] }
      for i in range(len(dd))
        if len(dd["pattern"][i])==2
]
# regexes = regexes_1 | regexes_2
regexes = regexes_1 + regexes_2
regexes

[{'.*[Rr]oad.*?': 'road_others'},
 {'.*[Aa]ccess road.*?': 'road_others'},
 {'.*[Hh]ighway.*': 'motorways'},
 {'.*[Mm]otorway.*': 'motorways'},
 {'.*[Rr]ail.*': 'rail'},
 {'.*[Rr]ailway track.*?': 'rail'},
 {'.*[Ss]tation.*': 'railway_station'},
 {'.*[Mm]etro station.*': 'metro'},
 {'.*[Bb]ridge.*?': 'bridges'},
 {'.*[Aa]irport.*': 'airports'},
 {'.*[Aa]viation.*': 'aviation'},
 {'.*[Aa]viation industry': 'aviation'},
 {'.*[Ss]ea port.*': 'ports'},
 {'.*[Pp]ort.*': 'ports'},
 {'.*[Hh]arbor.*': 'ports'},
 {'.*[Mm]aritime sector': 'maritime'},
 {'.*[Ww]aterway.*': 'inland_waterways'},
 {'.*[Ii]nland waterway.*?': 'inland_waterways'},
 {'.*IWW.*?': 'inland_waterways'},
 {'.*[Ee]lectric.* supply': 'electricity_supply'},
 {'.*[Ee]lectric.* net.*': 'electricity_distribution'},
 {'.*[Ee]lectric.* plant.*': 'powerplants'},
 {'.*[Ee]lectric.* service.*': 'electricity_supply'},
 {'.*[Pp]ower net.*': 'electricity_distribution'},
 {'.*[Pp]ower supply': 'electricity_supply'},
 {'.*[Gg]as pipe.*': 'gas_distribution'},
 {'.*[Hh]ydrocarbon': 'nonrenewable_others'},
 {'.*[Hh]ydrocarbon pipe.*': 'nonrenewable_others'},
 {'.* LNG': 'nonrenewable_others'},
 {'.*[Ll]iquefied [Nn]atural [Gg]as': 'nonrenewable_others'},
 {'.*[Gg]as.* distribution': 'gas_distribution'},
 {'.*[Gg]as.* supply': 'gas_supply'},
 {'.*[Gg]as.* storage': 'gas_storage'},
 {'.*[Pp]ower plant.*': 'powerplants'},
 {'.*[Nn]uclear plant.*': 'powerplants'},
 {'.*[Nn]uclear reactors.*': 'powerplants'},
 {'.*[Ss]olar farm.*': 'renewables'},
 {'.*[Ss]olar park.*': 'renewables'},
 {'.*[Ss]olar panel.*': 'renewables'},
 {'.*[Ww]ind farm.*': 'renewables'},
 {'.*[Ww]ind park.*': 'renewables'},
 {'.*[Cc]harging station.*': 'electricity_distribution'},
 {'.*[Pp]etrol station.*': 'petrol_gas_stations_consumers'},
 {'.*[Ff]illing station.*': 'petrol_gas_stations_consumers'},
 {'.*[Dd]am ': 'waterprotection'},
 {'.*[Dd]ams ': 'waterprotection'},
 {'.*[Dd]ike.*': 'waterprotection'},
 {'.*[Ll]eeve.*': 'waterprotection'},
 {'.*[Rr]eservoir.*': 'waterprotection'},
 {'.*[Ww]ater distribution': 'water_distribution'},
 {'.*[Ww]ater infrastructure': 'water_others'},
 {'.*[Ww]ater network': 'water_others'},
 {'.*[Ww]ater sector.*': 'water_others'},
 {'.*[Ww]ater supply.*': 'water_supply'},
 {'.*[Dd]rinking water.*': 'drinking_water'},
 {'.*[Gg]roundwater.*': 'water_others'},
 {'.*[Ww]ater.* treatment.*': 'wastewater'},
 {'.*[Ww]astewater.*': 'wastewater'},
 {'.*[Ww]aste.*water treatment.*': 'wastewater'},
 {'.*[Ww]aste.*water sector': 'wastewater'},
 {'.*[Dd]rainage.* system.*': 'wastewater'},
 {'.*[Dd]rainage.* network.*': 'wastewater'},
 {'.*[Dd]rainage.* infrastructure': 'wastewater'},
 {'.*[Ss]ewage.* system.*': 'wastewater'},
 {'.*[Ss]ewage.* network': 'wastewater'},
 {'.*[Ss]ewage.* infrastructure': 'wastewater'},
 {'.*[Ss]ewage sector.*': 'wastewater'},
 {'.*[Ss]ewage .*': 'waste_others'},
 {'.*[Ss]olid waste.*': 'waste_others'},
 {'.*[Ss]olid-waste.*': 'waste_others'},
 {'.*[Ww]aste facilit.*': 'waste_others'},
 {'.*[Ww]aste management': 'waste_others'},
 {'.*[Ww]aste sector': 'waste_others'},
 {'.*[Ww]aste.* treatment.*': 'waste_others'},
 {'.*IT*. sector.*': 'it_telecommunication'},
 {'.*IT*. infrastructure.*': 'it_telecommunication'},
 {'.*[Dd]data center.*': 'it_telecommunication'},
 {'.*[Bb]roadband network.*': 'it_telecommunication'},
 {'.*[Cc]ell tower.*': 'it_telecommunication'},
 {'.*[Tt]elecommunication.*': 'it_telecommunication'},
 {'.*[Tt]elecommunication service.*': 'it_telecommunication'},
 {'.*[Tt]elecommunication sector.*': 'it_telecommunication'},
 {'.*[Tt]elecommunication infrastructure.*': 'it_telecommunication'},
 {'.*[Tt]elecommunication mast.*': 'it_telecommunication'},
 {'.*[Hh]eavy industr.*': 'industry_heavy'},
 {'.*[Cc]hemic.* industr.*': 'industry_heavy'},
 {'.*[Rr]efiner.*': 'industry_heavy'},
 {'.*[Ee]ducation.*': 'education_others'},
 {'.*[Ss]chool.*': 'education_school'},
 {'.*[Hh]ealth.*': 'healthcare_others'},
 {'.*[Hh]ealthcare.* facilit.*': 'healthcare_others'},
 {'.*[Mm]edical.*': 'healthcare_others'},
 {'.*[Cc]linic.*': 'healthcare_hospitals_clinics'},
 {'.*[Hh]ospital.*': 'healthcare_hospitals_clinics'},
 {'.*[Ee]mergency.*': 'healthcare_hospitals_clinics'},
 {'.*[Ee]mergency.* services': 'healthcare_hospitals_clinics'},
 {'.*[Tt]ransport.* sector': 'transport_others'},
 {'.*[Tt]ransport.* infrastructure': 'transport_others'},
 {'.*[Ee]lectric.* distribution': 'electricity_distribution'},
 {'.*[Ee]lectric.* sector': 'electricity_others'},
 {'.*[Ee]lectric.* infrastructure': 'electricity_others'},
 {'.*[Ee]lectric.* transmission': 'electricity_distribution'}]

In [ ]:
# # if df_pred["infrastructure_type"].str.contains("[Rr]oads").item():
# #     df_pred["infrastructure_type_postp"] = subgroup

# tt = {
#    '.*[Rr]oad.*?': 'road_others',
#    '.*[Bb]ridge.*?': 'road_others',
# }
# df_pred["infrastructure_type_postp"] =  df_pred["infrastructure_type"]
# # df_pred["infrastructure_type_postp"].map(tt, regex=True)
# def mapping(sector):
#     mapping_dict =  {
#        '.*[Rr]oad.*?': 'road_others',
#        '.*[Bb]ridge.*?': 'road_others',
#     }
#     return mapping_dict[sector]

# df_pred["infrastructure_type"].apply(mapping)
# ##df_pred

In [ ]:
df_pred.infrastructure_type_postp.unique()

array(['road_others', 'bridges', 'rail', 'ports', 'aviation',
       'electricity', 'water', 'healthcare_others', 'education_others',
       'daycare', 'healthcare_hospitals_clinics', 'public services',
       'it_telecommunication', 'IT network', 'IT services',
       'water_others', 'water_supply', 'drinking_water', 'agriculture',
       'properties', 'public_infrastructure', 'motorways', 'metro',
       'electricity_others', 'metro infrastructure', 'electricity access',
       'water access', 'daycare center', 'gas', 'IT', 'airplane', 'train',
       'container yard', 'gas infrastructure', 'power grid',
       'mobile network services', 'wastewater', 'waste_others',
       'powerplants', 'power line', 'metro line', 'power_plant',
       'electricity_infrastructure', 'IT_infrastructure', 'terminal',
       'container_yards', 'water_infrastructure', 'utility', 'food',
       'power', 'general-practitioner practices', 'education_school',
       'university', 'air traffic control', 'drainage', 'power_grid',
       'waterprotection', 'town', 'sierra', 'tower', 'operability',
       'traffic', 'daycare centres', 'daycare center(s)',
       'container yards', 'container terminal', 'storage projects',
       'climate-proof ﬂood-hit power infrastructure', 'transport_others',
       'power transmission', 'supply chain', 'factory', 'IT facility',
       'daycare center facility', 'general-practitioner_practices',
       'public_services', 'railway_station', 'manufacturing', 'dam',
       'chemical_area', 'daycare_center',
       'general_practitioner_practices', 'tourist_attractions',
       'government_buildings', 'tunnel', 'hotel', 'restaurant',
       'cultural center', 'theater', 'concert hall', 'museum', 'library',
       'government building', 'embassy', 'military base', 'prison',
       'universities', 'aircraft', 'shop', 'bank', 'tourism', 'energy',
       'chemical', 'culture', 'government', 'military',
       'gas_distribution'], dtype=object)

In [ ]:
print(df_pred.infrastructure_group.isna().sum())
print(df_pred.infrastructure_group.value_counts())
# df_pred.infrastructure_group.unique()

523
infrastructure_group
ports                           367
road_others                     183
healthcare_others               125
rail                            120
bridges                          55
it_telecommunication             55
education_others                 48
water_supply                     26
aviation                         25
healthcare_hospitals_clinics     21
motorways                        16
education_school                 14
water_others                     12
waste_others                     11
electricity_others                8
drinking_water                    6
powerplants                       6
railway_station                   5
wastewater                        4
waterprotection                   3
transport_others                  1
gas_distribution                  1
Name: count, dtype: int64

In [ ]:
for i, r in enumerate(regexes):

    # get regex pattern for CI type (key) and its subgroup (value)
    # NOTE, nice shortcut: get key containing regex by unpacking each dict into list, then get key
    pattern = [*r][0]
    subgroup = r[pattern]

    # assign subgroups to CI records, na=False to remove all records which not match patterns
    mask = df_pred["infrastructure_type"].str.contains(pattern, regex=True, na=False)
    df_pred.loc[mask, "infrastructure_group"] = subgroup

    # assign subgroups to CI records, na=False to remove all records which not match patterns
    mask = df_valid["ci1_type"].str.contains(pattern, regex=True, na=False)
    df_valid.loc[mask, "ci1_group"] = subgroup
    
df_pred

print(df_pred.infrastructure_group.isna().sum())
print(df_pred.infrastructure_group.value_counts())
# df_pred.infrastructure_group.unique()

print(df_valid.df_valid.isna().sum())
print(df_valid.df_valid.value_counts())
# df_pred.infrastructure_group.unique()

,citation_id,chunk_id,infrastructure_type,damage,location,ci_entity,geo_entity,case_type,chunk_text,infrastructure_type_postp,infrastructure_type_postp2,infrastructure_group
0,Karakatsani 2023,0,roads,severely damaged,Thessaly plain,National roads,plain,NaN,"The economic impact of the recent devastating floods in Greece The economic impact of the recent devastating floods in Greece The briefing presents the economic impact of the damages caused by the storm “Daniel”. The floods caused by the heavy rainfall, especially in Thessaly plain -accounting for approximately 15% of Greece’s agricultural land- resulted to a massive destruction in agriculture, infrastructure and residences, which is expected to negatively affect the Greek economy in short and mid-term. Fears for food shortages and increase of product prices have been raised. In addition, increase of fiscal costs, imports and unemployment may also affect the economy in the upcoming years. The extent of the impact to the economy is not yet know. Before the country recovered from the wildfires of August and the consequent huge forest disaster, a weather stormy phenomenon named Daniel hit the country. Specifically, in the beginning of September, rainfall of unprecedented intensity fell mainly in central Greece and especially in Thessaly plain, causing floods throughout the territory. Thousands of acres of crops and livestock farms were destroyed. Properties and houses were lost under ton of waters. National roads were closed, bridges collapsed, and some parts of the railway network were highly damaged dividing the country in two. Evidently, the massive destruction of agricultural",road_others,roads,road_others
1,Karakatsani 2023,0,bridges,collapsed,central Greece,NaN,NaN,NaN,"The economic impact of the recent devastating floods in Greece The economic impact of the recent devastating floods in Greece The briefing presents the economic impact of the damages caused by the storm “Daniel”. The floods caused by the heavy rainfall, especially in Thessaly plain -accounting for approximately 15% of Greece’s agricultural land- resulted to a massive destruction in agriculture, infrastructure and residences, which is expected to negatively affect the Greek economy in short and mid-term. Fears for food shortages and increase of product prices have been raised. In addition, increase of fiscal costs, imports and unemployment may also affect the economy in the upcoming years. The extent of the impact to the economy is not yet know. Before the country recovered from the wildfires of August and the consequent huge forest disaster, a weather stormy phenomenon named Daniel hit the country. Specifically, in the beginning of September, rainfall of unprecedented intensity fell mainly in central Greece and especially in Thessaly plain, causing floods throughout the territory. Thousands of acres of crops and livestock farms were destroyed. Properties and houses were lost under ton of waters. National roads were closed, bridges collapsed, and some parts of the railway network were highly damaged dividing the country in two. Evidently, the massive destruction of agricultural",bridges,bridges,bridges
2,Karakatsani 2023,0,railway,highly damaged,Thessaly plain,NaN,NaN,NaN,"The economic impact of the recent devastating floods in Greece The economic impact of the recent devastating floods in Greece The briefing presents the economic impact of the damages caused by the storm “Daniel”. The floods caused by the heavy rainfall, especially in Thessaly plain -accounting for approximately 15% of Greece’s agricultural land- resulted to a massive destruction in agriculture, infrastructure and residences, which is expected to negatively affect the Greek economy in short and mid-term. Fears for food shortages and increase of product prices have been raised. In addition, increase of fiscal costs, imports and unemployment may also affect the economy in the upcoming years. The extent of the impact to the economy is not yet know. Before the country recovered from the wildfires of August and the consequent huge forest disaster, a weather stormy phenomenon named Daniel hit the country. Specifically, in the beginning of September, rainfall of unprecedented intensity fell mainly in central Greece and especially in Thessaly plain, causing floods throughout the territory. Thousands of acres of crops and livestock farms were destroyed. Properties and houses were lost under ton of waters. National roads were closed, bridges collapsed, and some parts of the railway network were highly damaged dividing the country in two. Evidently, the massive destruction of agricultural",rail,railway,rail
3,Karakatsani 2023,0,ports,destroyed,Thessaly plain,NaN,NaN,NaN,"The economic impact of the recent devastating floods in Greece The economic impact of the recent devastating floods in Greece The briefing presents the economic impact of the damages caused by the storm “Daniel”. The floods caused by the heavy rainfall, especially in Thessaly plain -accounting for approximately 15% of Greece’s agricultural land- resulted to a massive destruction in agriculture, infrastructure and residences, which is expected to negatively affect the Greek economy in short and mid-term. Fears for food shortages and increase of product prices have been raised. In addition, increase of fiscal costs, imports and unemployment may also affect the economy in the upcoming years. The extent of the impact to the economy is not yet know. Before the country recovered from the wildfires of August and the consequent huge forest disaster, a weather stormy phenomenon named Daniel hit the country. Specifically, in the beginning of September, rainfall of unprecedented intensity fell mainly in central Greece and especially in Thessaly plain, causing floods throughout the territory. Thousands of acres of crops and livestock farms were destroyed. Properties and houses were lost under ton of waters. National roads were closed, bridges collapsed, and some parts of the railway network were highly damaged dividing the country in two. Evidently, the massive destruction of agricultural",ports,ports,ports
4,Karakatsani 2023,0,airports,disrupted,central Greece,NaN,NaN,NaN,"The economic impact of the recent devastating floods in Greece The economic impact of the recent devastating floods in Greece The briefing presents the economic impact of the damages caused by the storm “Daniel”. The floods caused by the heavy rainfall, especially in Thessaly plain -accounting for approximately 15% of Greece’s agricultural land- resulted to a massive destruction in agriculture, infrastructure and residences, which is expected to negatively affect the Greek economy in short and mid-term. Fears for food shortages and increase of product prices have been raised. In addition, increase of fiscal costs, imports and unemployment may also affect the economy in the upcoming years. The extent of the impact to the economy is not yet know. Before the country recovered from the wildfires of August and the consequent huge forest disaster, a weather stormy phenomenon named Daniel hit the country. Specifically, in the beginning of September, rainfall of unprecedented intensity fell mainly in central Greece and especially in Thessaly plain, causing floods throughout the territory. Thousands of acres of crops and livestock farms were destroyed. Properties and houses were lost under ton of waters. National roads were closed, bridges collapsed, and some parts of the railway network were highly damaged dividing the country in two. Evidently, the massive destruction of agricultural",ports,airports,ports
...,...,...,...,...,...,...,...,...,...,...,...,...
1630,Gilbody Dickerson 2024,10,healthcare facility,outages,elsewhere in Europe,NaN,NaN,NaN,"Both teams were due to play in the Copa del Rey on Wednesday night.Other midweek games could also be cancelled, along with Saturday'sleague match between Valencia and Madrid.Scientists have warned that increased episodes of extreme weather, likeflash floods, or the wildfires seen elsewhere in Europe in the summer, arelikely linked to human-driven climate change.Meteorologists believe the warming of the Mediterranean, whichincreases water evaporation, plays a key role in making torrential rainsmore severe.Related TopicsClimate ChangeExtreme WeatherSpainAbout Sky NewsAbout UsSky News ProfilesSky News DistributionSky News Library SalesSite MapEditorial GuidelinesSky News BoardSky News ServicesSky News RSSSky News For Your PhoneSky News RadioSky ChannelsSky WitnessSky AtlanticMore Sky SitesNOWSky Up Academy Studios 1/3/26, 10:51 PM © 2026 Sky UKSky ArtsSky CinemaSky SportsSky GroupSky BetSky.comSky News ArabiaAdvertise With UsTerms &amp; ConditionsPrivacy &amp; CookiesPrivacy OptionsAccessibilityContact Us",healthcare_others,healthcare facility,healthcare_others
1631,Gilbody Dickerson 2024,10,healthcare facility,heavily destroyed,elsewhere in Europe,NaN,NaN,NaN,"Both teams were due to play in the Copa del Rey on Wednesday night.Other midweek games could also be cancelled, along with Saturday'sleague match between Valencia and Madrid.Scientists have warned that increased episodes of extreme weather, likeflash floods, or the wildfires seen elsewhere in Europe in the summer, arelikely linked to human-driven climate change.Meteorologists believe the warming of the Mediterranean, whichincreases water evaporation, plays a key role in making torrential rainsmore severe.Related TopicsClimate ChangeExtreme WeatherSpainAbout Sky NewsAbout UsSky News ProfilesSky News DistributionSky News Library SalesSite MapEditorial GuidelinesSky News BoardSky News ServicesSky News RSSSky News For Your PhoneSky News RadioSky ChannelsSky WitnessSky AtlanticMore Sky SitesNOWSky Up Academy Studios 1/3/26, 10:51 PM © 2026 Sky UKSky ArtsSky CinemaSky SportsSky GroupSky BetSky.comSky News ArabiaAdvertise With UsTerms &amp; ConditionsPrivacy &amp; CookiesPrivacy OptionsAccessibilityContact Us",healthcare_others,healthcare facility,healthcare_others
1632,Gilbody Dickerson 2024,10,healthcare facility,severely damaged,elsewhere in Europe,NaN,NaN,NaN,"Both teams were due to play in the Copa del Rey on Wednesday night.Other midweek games could also be cancelled, along with Saturday'sleague match between Valencia and Madrid.Scientists have warned that increased episodes of extreme weather, likeflash floods, or the wildfires seen elsewhere in Europe in the summer, arelikely linked to human-driven climate change.Meteorologists believe the warming of the Mediterranean, whichincreases water evaporation, plays a key role in making torrential rainsmore severe.Related TopicsClimate ChangeExtreme WeatherSpainAbout Sky NewsAbout UsSky News ProfilesSky News DistributionSky News Library SalesSite MapEditorial GuidelinesSky News BoardSky News ServicesSky News RSSSky News For Your PhoneSky News RadioSky ChannelsSky WitnessSky AtlanticMore Sky SitesNOWSky Up Academy Studios 1/3/26, 10:51 PM © 2026 Sky UKSky ArtsSky CinemaSky SportsSky GroupSky BetSky.comSky News ArabiaAdvertise With UsTerms &amp; ConditionsPrivacy &amp; CookiesPrivacy OptionsAccessibilityContact Us",healthcare_others,healthcare facility,healthcare_others
1633,Gilbody Dickerson 2024,10,healthcare facility,disrupted,elsewhere in Europe,NaN,NaN,NaN,"Both teams were due to play in the Copa del Rey on Wednesday night.Other midweek games could also be cancelled, along with Saturday'sleague match between Valencia and Madrid.Scientists have warned that increased episodes of extreme weather, likeflash floods, or the wildfires seen elsewhere in Europe in the summer, arelikely linked to human-driven climate change.Meteorologists believe the warming of the Mediterranean, whichincreases water evaporation, plays a key role in making torrential rainsmore severe.Related TopicsClimate ChangeExtreme WeatherSpainAbout Sky NewsAbout UsSky News ProfilesSky News DistributionSky News Library SalesSite MapEditorial GuidelinesSky News BoardSky News ServicesSky News RSSSky News For Your PhoneSky News RadioSky ChannelsSky WitnessSky AtlanticMore Sky SitesNOWSky Up Academy Studios 1/3/26, 10:51 PM © 2026 Sky UKSky ArtsSky CinemaSky SportsSky GroupSky BetSky.comSky News ArabiaAdvertise With UsTerms &amp; ConditionsPrivacy &amp; CookiesPrivacy OptionsAccessibilityContact Us",healthcare_others,healthcare facility,healthcare_others
1634,Gilbody Dickerson 2024,10,healthcare facility,outages,elsewhere in Europe,NaN,NaN,NaN,"Both teams were due to play in the Copa del Rey on Wednesday night.Other midweek games could also be cancelled, along with Saturday'sleague match between Valencia and Madrid.Scientists have warned that increased episodes of extreme weather, likeflash floods, or the wildfires seen elsewhere in Europe in the summer, arelikely linked to human-driven climate change.Meteorologists believe the warming of the Mediterranean, whichincreases water evaporation, plays a key role in making torrential rainsmore severe.Related TopicsClimate ChangeExtreme WeatherSpainAbout Sky NewsAbout UsSky News ProfilesSky News DistributionSky News Library SalesSite MapEditorial GuidelinesSky News BoardSky News ServicesSky News RSSSky News For Your PhoneSky News RadioSky ChannelsSky WitnessSky AtlanticMore Sky SitesNOWSky Up Academy Studios 1/3/26, 10:51 PM © 2026 Sky UKSky ArtsSky CinemaSky SportsSky GroupSky BetSky.comSky News ArabiaAdvertise With UsTerms &amp; ConditionsPrivacy &amp; CookiesPrivacy OptionsAccessibilityContact Us",healthcare_others,healthcare facility,healthcare_others

In [ ]:
df_valid.ci1_group.unique()

array(['ports', 'road_others', 'electricity_others', 'motorways', nan,
       'rail', 'bridges', 'gas_distribution', 'waste_others',
       'wastewater', 'water_others', 'drinking_water', 'water_supply',
       'it_telecommunication', 'healthcare_others',
       'healthcare_hospitals_clinics', 'education_school'], dtype=object)

In [ ]:


# # Transport
# sb_local_roads = {}

# sb_roads_national_importance = {}

# sb_roads_motorways = {}

# sb_railways = {}
# sb_inland_waterways = {}
# sb_ports = {}
# sb_airports = {}

# # Energy
# sb_nonrenewable_powerplants = {}
# sb_nonrenewable_others = {}

# sb_renewable = {}
# sb_electricity_distribution = {}

# sb_gas_distribution = {}

# # Telecommunication & IT
# sb_broadband = {}    # IT
# sb_telecommunication = {}

# # Industry
# sb_industry_heavy = {}  # metal. mineral, chemical industry or refineries

# # Waste
# sb_treatment_wastewater = {}
# sb_treatment_waste_others = {}

# # social
# sb_schools = {}
# sb_education_others = {}

# sb_medical_practices = {}
# sb_hospitals = {}
# sb_health_others = {}

# sb_daycare = {}

In [ ]:
# s = "dyke" to s2 = "levee", s3 = "dam"
# bge-m3: 0.48  0.54
# all-MIniLM-L6-v2: 0.34 , 0.36  (similar all-mpnet-base-v2)
# gensim word2vec: 0.39 0.40


# s1 = "aviation" s2 = "air traffic"
# word vector spacy: 0.45
# contextual vector spacy: 0.68
# bge-m3: 0.76
# all-MIniLM-L6-v2: xx  (all-mpnet-base-v2: 0.79)
# gensim word2vec: 


# s1 = "power" s2 = "electricity"
# word vector spacy: 0.61
# contextual vector spacy: 0.66
# bge-m3: 
# all-MIniLM-L6-v2: xx   (all-mpnet-base-v2: 0.43)
# gensim word2vec: 0.58


# s1 = "electricity infrastructure" s2 = "electricity"
# word vector spacy: 0.87
# contextual vector spacy: 0.71
# bge-m3: 
# all-MIniLM-L6-v2:   xx  (all-mpnet-base-v2: 0.63)
# gensim word2vec: 


# s1 = "transportation" s2 = "transport infrastructure"
# word vector spacy: 
# contextual vector spacy: 
# bge-m3: 
# all-MIniLM-L6-v2:   xx  (all-mpnet-base-v2: 0.84)
# gensim word2vec: 

# s1 = "port" s2 = "power"  s3= harbour
# bge-m3: 0.58, 0.50
# all-MIniLM-L6-v2: 0.33 , 0.56  (similar all-mpnet-base-v2)
# gensim word2vec: 0.14 0.59

# s1 = "electricity" s2 = "transportation" 
# bge-m3:  0.64
# all-MIniLM-L6-v2:   (all-mpnet-base-v2: 0.47)
# gensim word2vec: 0.33

tensor([[0.5883]])

In [ ]:
# # print(cos_sim(model_scs["transportation"], model_scs["transport infrastructure"]))
# # print(cos_sim(model_scs["electricity infrastructure"], model_scs["electricity"]))
# # print(cos_sim(model_scs["power plant"], model_scs["electricity"]))
# print(cos_sim(model_scs["power"], model_scs["electricity"]))
# print(cos_sim(model_scs["aviation"], model_scs["air traffic"]))
# # identical to model_scs.similarity("port", "power"))


# # similarity_score = 1-distance.cosine(model.encode([s1])[0], model.encode([s2])[0])

### Analyse evaluation results

In [ ]:
df_smltry_selmax#.info()

In [ ]:
## find out for which docs model performed bad (or good)
## based on this info try to improve model 

df_smltry_selmax.dropna(subset=["impact_cos_sim"]).groupby("citation").apply(lambda x: x.loc[x["impact_cos_sim"].idxmax()]).sort_values(by="impact_cos_sim", ascending=True)
## check EFE, Wilson, European Investment Bank, Containerlift, Lloyds List, Gilbody Dickerson

In [ ]:
## check entries of worst performace docs for damage
df_smltry_selmax.loc[df_smltry_selmax["citation"].isin(["Khazai 2023", "ABC 2024", "Containerlift 2024", "Lloyds List 2024", "Ferlita 2023"])]

In [ ]:
## check entries of worst performance docs for Ci tyes
df_smltry_selmax.loc[df_smltry_selmax["citation"].isin(["EFE 2024", "Containerlift 2024", "Lloyds List 2024", "Wilson 2024", "Gilbody Dickerson 2024", "European Investment Bank 2025"])].head(50)


## For each validation entry, search for all prediction cases of the same chunk

In [ ]:
## get same impact entries
columns_valid = ["ci1_type", "ci1_damage", "ci1_location"]
columns_pred = ["infrastructure_type", "damage", "location"]


for column_valid, column_pred in zip(columns_valid, columns_pred):

    print(f" --------- Processing column pair: {column_valid} - {column_pred} ------------")
    
    df_valid_pred_all = pd.DataFrame()
    citations_list = []

    ## for each validation record
    for i in range(len(df_valid)):
        
        highest_similarity_score = 0.00
        
        ## needed to traceback info when entry is missing in pred. DS
        # chunk_id_value_valid = df_valid.chunk_id[i]

        # select nth validation record and check that it has value
        df_valid_entry = df_valid.iloc[i]
        if df_valid_entry[column_valid] is np.nan:
            continue
        
        citation_str = df_valid_entry.publication_id
        citations_list.append(citation_str)


        # get all corresponding prediction records
        df_pred_entries = df_pred[df_pred["citation_id"].isin([citation_str])]

        #  handle on NANs
        df_pred_entries[column_pred] = np.where(df_pred_entries[column_pred].isna(), "nan", df_pred_entries[column_pred])
        # df_pred_entries[column_pred] = df_pred_entries[column_pred].astype(str)
        # remove double whitespaces
        # df_pred_doc[column_pred] = df_pred_doc[column_pred].replace("  ", " ")
        # df_valid_entries[column_valid] = df_valid_entries[column_valid].replace("  ", " ")


        # vector of validiation entry 
        valid_impact = df_valid_entry[column_valid]
        valid_vec = nlp(valid_impact).vector

        # print(" ------- Searching for citation:", citation_str, " in predictions ------- ")

        # Compute similarity between each validation CI impact case and all potential predicted CI impact cases (cross-product)
        for j in range(len(df_pred_entries[column_pred])):

            if df_pred_entries[column_pred].iloc[j] == "nan":
                continue

            pred_impact = df_pred_entries[column_pred].iloc[j]

            pred_vec = nlp(pred_impact).vector
            similarity_score = cosine_similarity(valid_vec, pred_vec)  # 0-1 value, the higher the more similar
            # print(f"Similarity {i}-{j}: {similarity_score}")

            # print(f"Searching for highest similarity ... ")
            ## get only pair with highest similarity
            if similarity_score > highest_similarity_score:
                
                highest_similarity_score = similarity_score
                
                dict_pair = {
                    "impact_valid": valid_impact, 
                    "impact_pred": pred_impact, 
                    "similarity": highest_similarity_score,
                    "citation": citation_str,
                    "chunk_id_pred": (df_pred.chunk_id[i],  df_pred.chunk_id[j])
                }
            else:
                continue

        df_valid_pred_all = pd.concat([df_valid_pred_all, pd.DataFrame([dict_pair])], ignore_index=True)


    print(f" ---------- Evaluation summary statistics - {column_pred}: -----------")
    print(df_valid_pred_all.similarity.describe())

    

    SIMILARITY_FILENAME = f'{column_pred}_{SIMILARITY_LLM_FILENAME}'
    SIMILARITY_FILEPATH = Path(PATH_EVAL_RESULT / SIMILARITY_FILENAME)

    print("Saving evaluation statistics, distribution plots, and scores to ", SIMILARITY_FILEPATH.stem, "[.parquet, _stats.json]")
    with open(SIMILARITY_FILEPATH, 'w') as f:
        # results
        df_valid_pred_all.to_csv(SIMILARITY_FILEPATH.with_suffix('.csv'), index=False)
        df_valid_pred_all_pyarrow = pa.Table.from_pandas(df_valid_pred_all)
        pq.write_table(df_valid_pred_all_pyarrow, SIMILARITY_FILEPATH)   
        #   summary statistics
        df_valid_pred_all_stats = df_valid_pred_all.describe()
        f = SIMILARITY_FILEPATH.parent / f"{SIMILARITY_FILEPATH.stem}_stats.json"  
        df_valid_pred_all_stats.to_json(f, indent=4)
        # distribution plots
        df_valid_pred_all.similarity.hist(bins=100).to_file(SIMILARITY_FILEPATH.parent / f"{SIMILARITY_FILEPATH.stem}_hist.png")



    # similarity_threshold = 0.75
    # df_valid_pred_all['is_similar'] = df_valid_pred_all['similarity'] <= similarity_threshold
    # print(f"Number of similar impact cases (similarity >= {similarity_threshold}): {df_valid_pred_all['is_similar'].sum()} out of {len(df_valid_pred_all)}\n")

    # df_valid_pred_all =  df_valid_pred_all[df_valid_pred_all['similarity'] <= similarity_threshold]

    # SIMILARITY_FILENAME = f'{column_pred}_lower75_{SIMILARITY_LLM_FILENAME}'
    # SIMILARITY_FILEPATH = Path(PATH_EVAL_RESULT / SIMILARITY_FILENAME)

    # with open(SIMILARITY_FILEPATH, 'w') as f:
    #     # results
    #     df_valid_pred_all.to_csv(SIMILARITY_FILEPATH.with_suffix('.csv'), index=False)
    #     df_valid_pred_all_pyarrow = pa.Table.from_pandas(df_valid_pred_all)
    #     pq.write_table(df_valid_pred_all_pyarrow, SIMILARITY_FILEPATH)  
    #     #   summary statistics
    #     df_valid_pred_all_stats = df_valid_pred_all.describe()
    #     f = SIMILARITY_FILEPATH.parent / f"{SIMILARITY_FILEPATH.stem}_stats.json"  
    #     df_valid_pred_all_stats.to_json(f, indent=4)

In [ ]:
# df_valid_pred_all[df_valid_pred_all['similarity'] <= 0.75]

# df_valid_pred_all.similarity.hist(bins=100)

In [ ]:
columns_pred

In [ ]:
LLM_DATA_FILEPATH

### Load parquet file

In [ ]:

columns_pred = ["infrastructure_type", "damage", "location"]

In [ ]:
column_pred = "infrastructure_type"
SIMILARITY_FILENAME = f'llm1_similarity_{column_pred}_75.parquet'
SIMILARITY_FILEPATH = Path(PATH_EVAL_RESULT / SIMILARITY_FILENAME)

with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    df = pd.read_parquet(SIMILARITY_FILEPATH, engine='pyarrow')
    display(df)

## Archive

In [ ]:
## Aim 
## for all identical valid entries ie. with same [ci_valid	damage_valid	location_valid	sentence_text_valid]
## get the match to pred_entity with highest similarity

In [ ]:
    # ## calc for each entry with the same chunk_text the similarity between valid_impact and pred_impact
    # ## means we calc also the False Negatives (ie. where valid entry exists but no prediction)


    # # iterate over groups of entities which refer to the same valid case (i.e. which are identical in valid_columns)
    # # TODO iterate over unqiue cases in df_valid (instead of using grouper)
    # grouper = df_pred_valid_all[["ci_valid", "damage_valid", "location_valid", "sentence_text_valid"]].drop_duplicates()
    # for group in grouper.itertuples():
    #     df_pred_valid_group = df_pred_valid_all[df_pred_valid_all[["ci_valid", "damage_valid", "location_valid", "sentence_text_valid"]] == group[["ci_valid", "damage_valid", "location_valid", "sentence_text_valid"]]]

    #     # calc. similarities to pred_entities
    #     for i, entry in df_pred_valid_group.iterrows():

    #         highest_similarity_score = 0 

    #         if entry[column_pred].iloc[i] == "nan":
    #             continue
            
    #         # calc embeddings
    #         pred_impact = entry[column_pred].iloc[i]
    #         pred_vec = nlp(pred_impact).vector

    #         valid_impact = entry[column_valid].iloc[i] # is unique for each group
    #         valid_vec = nlp(valid_impact).vector
    #         print(valid_impact, "valid_impact")
            
    #         similarity_score = cosine_similarity(valid_vec, pred_vec)  # 0-1 value, the higher the more similar
    #         # print(f"Similarity {i}-{j}: {similarity_score}")

    #         ## return only pred-valid-pair with highest similarity
    #         if similarity_score > highest_similarity_score:
                
    #             highest_similarity_score = similarity_score
                
    #             entry["impact_similarity"] = highest_similarity_score

    # ## FNs
    # # # calc FN when valid_info exists but not corresponding pred_info
    # ## number of FNs is small due that wrong matching with any chunk-text is more likely due to its text size comapred sentence-level (valid set) 
    # elif entry[column_pred] is np.nan:
    #     similarity_score = 0
    #     dict_pair = {
    #         "impact_valid": valid_impact, 
    #         "impact_pred": pred_impact, 
    #         "impact_similarity": similarity_score,
    #         "tp_tn_fp_fn": "fn",
    #         "citation": entry.citation_id,
    #         "chunk_text_pred": entry.chunk_text_pred,
    #         "sentence_text_valid": entry.sentence_text_valid,
    #         }
    #     df_smltry_selmax = pd.concat([df_smltry_selmax, pd.DataFrame([dict_pair])], ignore_index=True)

    # ## FPs
    # elif entry[column_valid] is np.nan:
    #     similarity_score = 0
    #     dict_pair = {
    #         "impact_valid": valid_impact, 
    #         "impact_pred": pred_impact, 
    #         "impact_similarity": similarity_score,
    #         "tp_tn_fp_fn": "fp",
    #         "citation": entry.citation_id,
    #         "chunk_text_pred": entry.chunk_text_pred,
    #         "sentence_text_valid": entry.sentence_text_valid,
    #         }
    #     df_smltry_selmax = pd.concat([df_smltry_selmax, pd.DataFrame([dict_pair])], ignore_index=True)

In [ ]:
# ## get same impact entries
# columns_valid = ["ci1_type", "ci1_damage", "ci1_location"]
# columns_pred = ["infrastructure_type", "damage", "location"]



## iterate over predictions and search for each prediction reocrds for corresponding valid cases 

# for column_valid, column_pred in zip(columns_valid, columns_pred):

#     print(f" --------- Processing column pair: {column_valid} - {column_pred} ------------")
    
#     df_valid_pred_all = pd.DataFrame()
#     citations_list = []

#     ## for each validation record
#     for i in range(len(df_valid)):
        
#         highest_similarity_score = 0.00
        
#         ## needed to traceback info when entry is missing in pred. DS
#         # chunk_id_value_valid = df_valid.chunk_id[i]

#         # select nth validation record
#         df_valid_entry = df_valid.iloc[i]
#         citation_str = df_valid_entry.publication_id
#         citations_list.append(citation_str)
#         print(" ------- Searching for citation:", citation_str, " in predictions ------- ")


#         # get all corresponding prediction records
#         df_pred_entries = df_pred[df_pred["citation_id"].isin([citation_str])]
#         #  handle on NANs
#         df_pred_entries[column_pred] = np.where(df_pred_entries[column_pred].isna(), "nan", df_pred_entries[column_pred])
#         # df_pred_entries[column_pred] = df_pred_entries[column_pred].astype(str)
#         # remove double whitespaces
#         # df_pred_doc[column_pred] = df_pred_doc[column_pred].replace("  ", " ")
#         # df_valid_entries[column_valid] = df_valid_entries[column_valid].replace("  ", " ")

#         # skip when validation entry ha no value
#         if df_valid_entry[column_valid] is np.nan:
#             continue

#         # vector of validiation entry 
#         valid_impact = df_valid_entry[column_valid]
#         valid_vec = nlp(valid_impact).vector


#         # Compute similarity between each predicted impact case and all potential validation impact cases (cross-product)
#         # print(f"Searching for highest similarity of`{pred_impact}` in validation set ... ")
#         for j in range(len(df_pred_entries[column_pred])):

#             if df_pred_entries[column_pred].iloc[j] == "nan":
#                 continue

#             pred_impact = df_pred_entries[column_pred].iloc[j]

#             pred_vec = nlp(pred_impact).vector
#             similarity_score = cosine_similarity(valid_vec, pred_vec)  # 0-1 value, the higher the more similar
#             # print(f"Similarity {i}-{j}: {similarity_score}")

#             ## get only pair with highest similarity
#             if similarity_score > highest_similarity_score:
                
#                 highest_similarity_score = similarity_score
                
#                 dict_pair = {
#                     "impact_valid": valid_impact, 
#                     "impact_pred": pred_impact, 
#                     "similarity": highest_similarity_score,
#                     "citation": citation_str,
#                     "chunk_id_pred": df_pred.chunk_id[i]
#                 }
#             else:
#                 continue

#         df_valid_pred_all = pd.concat([df_valid_pred_all, pd.DataFrame([dict_pair])], ignore_index=True)


#     print(" ---------- Evaluation summary statistics: -----------")
#     print(df_valid_pred_all.similarity.describe())



#     SIMILARITY_FILENAME = f'{SIMILARITY_LLM_FILENAME}_{column_pred}.parquet'
#     SIMILARITY_FILEPATH = Path(PATH_EVAL_RESULT / SIMILARITY_FILENAME)

#     print("Saving evaluation statistics and scores to ", SIMILARITY_FILEPATH.stem, "[.parquet, _stats.json]")
#     with open(SIMILARITY_FILEPATH, 'w') as f:
#         # results
#         df_valid_pred_all_pyarrow = pa.Table.from_pandas(df_valid_pred_all)
#         pq.write_table(df_valid_pred_all_pyarrow, SIMILARITY_FILEPATH)   
#         #   summary statistics
#         df_valid_pred_all_stats = df_valid_pred_all.describe()
#         f = SIMILARITY_FILEPATH.parent / f"{SIMILARITY_FILEPATH.stem}_stats.json"  
#         df_valid_pred_all_stats.to_json(f, indent=4)



#     similarity_threshold = 0.75
#     df_valid_pred_all['is_similar'] = df_valid_pred_all['similarity'] >= similarity_threshold
#     print(f"Number of similar impact cases (similarity >= {similarity_threshold}): {df_valid_pred_all['is_similar'].sum()} out of {len(df_valid_pred_all)}")

#     SIMILARITY_FILENAME = f'{SIMILARITY_LLM_FILENAME}_{column_pred}_75.parquet'
#     SIMILARITY_FILEPATH = Path(PATH_EVAL_RESULT / SIMILARITY_FILENAME)

#     with open(SIMILARITY_FILEPATH, 'w') as f:
#         # results
#         df_valid_pred_all_pyarrow = pa.Table.from_pandas(df_valid_pred_all)
#         pq.write_table(df_valid_pred_all_pyarrow, SIMILARITY_FILEPATH)  
#         #   summary statistics
#         df_valid_pred_all_stats = df_valid_pred_all.describe()
#         f = SIMILARITY_FILEPATH.parent / f"{SIMILARITY_FILEPATH.stem}_stats.json"  
#         df_valid_pred_all_stats.to_json(f, indent=4)

In [ ]:

# #  Define folder for handling and writing outputs
# def write_to_file(data, out_folder, filename):
#     """Convert output to DataFrame and write to file"""
#     df = pd.DataFrame(list(data), columns=['tag', 'sts_score'])
#     #  Sort the DataFrame by similarity (explicitly)
#     df = df.sort_values(by='sts_score', ascending=False)
#     #  Assign integers to ranking
#     df['rank'] = df['sts_score'].rank(method='first', ascending=False).astype(int)
#     #  Only keep the first 20 resulting tags
#     df = df.head(50)
#     #  Save to file
#     df.to_csv(out_folder / f'{filename}_output.csv', index=False)

# #  Fill run metrics to dictionary
# def handle_metrics(metrics, model_name, length, end_time, start_time):
#     print(f'-> Took {end_time - start_time:.2f} seconds. Number of tags: {length}.')
#     metrics.append({
#         'modelname': model_name,
#         'runtime': round(end_time - start_time, 2),
#         'tagcount': length
#     })
#     return metrics

# class CPU_Unpickler(pickle.Unpickler):
#     """Fix for having issues with loading models on CPU"""
#     def find_class(self, module, name):
#         if module == 'torch.storage' and name == '_load_from_bytes':
#             return lambda b: torch.load(io.BytesIO(b), map_location='cpu')
#         else: return super().find_class(module, name)